import { changePassword, login, logout, me } from "./api/auth";
import { API_BASE_URL, markUx, reportUxSequence, startApiTrace, stopApiTrace } from "./api/client";
import {
  adminResetPassword,
  assignRole,
  createUser,
  getAdminOverview,
  listUsers,
  replaceUserRoles,
  unlockUser,
  updateUser,
} from "./api/iam";
import {
  listAuditEvents,
  listNotifications,
  markNotificationRead,
  subscribeOperationsStream,
} from "./api/notifications";
import {
  activateDocumentProfileSchema,
  createDocumentProfile,
  createProcessArea,
  createSubject,
  deleteDocumentProfile,
  deleteProcessArea,
  deleteSubject,
  downloadProfileTemplateDocx,
  getDocumentProfileBundle,
  getDocumentProfileGovernance,
  getDocumentProfileSchema,
  listDocumentDepartments,
  listDocumentFamilies,
  listDocumentProfileSchemas,
  listDocumentProfiles,
  listDocumentTypes,
  listProcessAreas,
  listSubjects,
  updateDocumentProfile,
  updateDocumentProfileGovernance,
  updateProcessArea,
  updateSubject,
  upsertDocumentProfileSchema,
} from "./api/registry";
import { listApprovals, transitionWorkflow } from "./api/workflow";

export type { OperationsStreamSnapshot } from "./api/notifications";
export { markUx, reportUxSequence, startApiTrace, stopApiTrace };

export const api = {
  currentApiBaseUrl: API_BASE_URL,
  login,
  logout,
  me,
  changePassword,
  listUsers,
  createUser,
  updateUser,
  assignRole,
  replaceUserRoles,
  adminResetPassword,
  unlockUser,
  getAdminOverview,
  listDocumentTypes,
  listDocumentFamilies,
  listDocumentProfiles,
  createDocumentProfile,
  updateDocumentProfile,
  deleteDocumentProfile,
  getDocumentProfileBundle,
  getDocumentProfileSchema,
  listDocumentProfileSchemas,
  upsertDocumentProfileSchema,
  activateDocumentProfileSchema,
  getDocumentProfileGovernance,
  updateDocumentProfileGovernance,
  listProcessAreas,
  listDocumentDepartments,
  createProcessArea,
  updateProcessArea,
  deleteProcessArea,
  listSubjects,
  createSubject,
  updateSubject,
  deleteSubject,
  listApprovals,
  transitionWorkflow,
  downloadProfileTemplateDocx,
  listNotifications,
  listAuditEvents,
  markNotificationRead,
  subscribeOperationsStream,
};
