//go:build go1.22

// Package registryapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package registryapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ActiveDocumentResponseApprovalState.
const (
	Approved    ActiveDocumentResponseApprovalState = "approved"
	Cancelled   ActiveDocumentResponseApprovalState = "cancelled"
	Draft       ActiveDocumentResponseApprovalState = "draft"
	Rejected    ActiveDocumentResponseApprovalState = "rejected"
	Scheduled   ActiveDocumentResponseApprovalState = "scheduled"
	UnderReview ActiveDocumentResponseApprovalState = "under_review"
)

// Valid indicates whether the value is a known member of the ActiveDocumentResponseApprovalState enum.
func (e ActiveDocumentResponseApprovalState) Valid() bool {
	switch e {
	case Approved:
		return true
	case Cancelled:
		return true
	case Draft:
		return true
	case Rejected:
		return true
	case Scheduled:
		return true
	case UnderReview:
		return true
	default:
		return false
	}
}

// Defines values for ControlledDocumentStatus.
const (
	ControlledDocumentStatusActive     ControlledDocumentStatus = "active"
	ControlledDocumentStatusObsolete   ControlledDocumentStatus = "obsolete"
	ControlledDocumentStatusSuperseded ControlledDocumentStatus = "superseded"
)

// Valid indicates whether the value is a known member of the ControlledDocumentStatus enum.
func (e ControlledDocumentStatus) Valid() bool {
	switch e {
	case ControlledDocumentStatusActive:
		return true
	case ControlledDocumentStatusObsolete:
		return true
	case ControlledDocumentStatusSuperseded:
		return true
	default:
		return false
	}
}

// Defines values for ControlledDocumentVisibilityScope.
const (
	Company    ControlledDocumentVisibilityScope = "company"
	Restricted ControlledDocumentVisibilityScope = "restricted"
)

// Valid indicates whether the value is a known member of the ControlledDocumentVisibilityScope enum.
func (e ControlledDocumentVisibilityScope) Valid() bool {
	switch e {
	case Company:
		return true
	case Restricted:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplateFieldSlotNodeResponseFieldKind.
const (
	Scalar DocumentTemplateFieldSlotNodeResponseFieldKind = "scalar"
)

// Valid indicates whether the value is a known member of the DocumentTemplateFieldSlotNodeResponseFieldKind enum.
func (e DocumentTemplateFieldSlotNodeResponseFieldKind) Valid() bool {
	switch e {
	case Scalar:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplateFieldSlotNodeResponseType.
const (
	FieldSlot DocumentTemplateFieldSlotNodeResponseType = "field-slot"
)

// Valid indicates whether the value is a known member of the DocumentTemplateFieldSlotNodeResponseType enum.
func (e DocumentTemplateFieldSlotNodeResponseType) Valid() bool {
	switch e {
	case FieldSlot:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplateLabelNodeResponseType.
const (
	Label DocumentTemplateLabelNodeResponseType = "label"
)

// Valid indicates whether the value is a known member of the DocumentTemplateLabelNodeResponseType enum.
func (e DocumentTemplateLabelNodeResponseType) Valid() bool {
	switch e {
	case Label:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplatePageNodeResponseType.
const (
	Page DocumentTemplatePageNodeResponseType = "page"
)

// Valid indicates whether the value is a known member of the DocumentTemplatePageNodeResponseType enum.
func (e DocumentTemplatePageNodeResponseType) Valid() bool {
	switch e {
	case Page:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplateRepeatSlotNodeResponseFieldKind.
const (
	Repeat DocumentTemplateRepeatSlotNodeResponseFieldKind = "repeat"
)

// Valid indicates whether the value is a known member of the DocumentTemplateRepeatSlotNodeResponseFieldKind enum.
func (e DocumentTemplateRepeatSlotNodeResponseFieldKind) Valid() bool {
	switch e {
	case Repeat:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplateRepeatSlotNodeResponseType.
const (
	RepeatSlot DocumentTemplateRepeatSlotNodeResponseType = "repeat-slot"
)

// Valid indicates whether the value is a known member of the DocumentTemplateRepeatSlotNodeResponseType enum.
func (e DocumentTemplateRepeatSlotNodeResponseType) Valid() bool {
	switch e {
	case RepeatSlot:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplateRichSlotNodeResponseFieldKind.
const (
	Rich DocumentTemplateRichSlotNodeResponseFieldKind = "rich"
)

// Valid indicates whether the value is a known member of the DocumentTemplateRichSlotNodeResponseFieldKind enum.
func (e DocumentTemplateRichSlotNodeResponseFieldKind) Valid() bool {
	switch e {
	case Rich:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplateRichSlotNodeResponseType.
const (
	RichSlot DocumentTemplateRichSlotNodeResponseType = "rich-slot"
)

// Valid indicates whether the value is a known member of the DocumentTemplateRichSlotNodeResponseType enum.
func (e DocumentTemplateRichSlotNodeResponseType) Valid() bool {
	switch e {
	case RichSlot:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplateSectionFrameNodeResponseType.
const (
	SectionFrame DocumentTemplateSectionFrameNodeResponseType = "section-frame"
)

// Valid indicates whether the value is a known member of the DocumentTemplateSectionFrameNodeResponseType enum.
func (e DocumentTemplateSectionFrameNodeResponseType) Valid() bool {
	switch e {
	case SectionFrame:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplateTableSlotNodeResponseFieldKind.
const (
	Table DocumentTemplateTableSlotNodeResponseFieldKind = "table"
)

// Valid indicates whether the value is a known member of the DocumentTemplateTableSlotNodeResponseFieldKind enum.
func (e DocumentTemplateTableSlotNodeResponseFieldKind) Valid() bool {
	switch e {
	case Table:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplateTableSlotNodeResponseType.
const (
	TableSlot DocumentTemplateTableSlotNodeResponseType = "table-slot"
)

// Valid indicates whether the value is a known member of the DocumentTemplateTableSlotNodeResponseType enum.
func (e DocumentTemplateTableSlotNodeResponseType) Valid() bool {
	switch e {
	case TableSlot:
		return true
	default:
		return false
	}
}

// Defines values for ListControlledDocumentsParamsStatus.
const (
	ListControlledDocumentsParamsStatusActive     ListControlledDocumentsParamsStatus = "active"
	ListControlledDocumentsParamsStatusObsolete   ListControlledDocumentsParamsStatus = "obsolete"
	ListControlledDocumentsParamsStatusSuperseded ListControlledDocumentsParamsStatus = "superseded"
)

// Valid indicates whether the value is a known member of the ListControlledDocumentsParamsStatus enum.
func (e ListControlledDocumentsParamsStatus) Valid() bool {
	switch e {
	case ListControlledDocumentsParamsStatusActive:
		return true
	case ListControlledDocumentsParamsStatusObsolete:
		return true
	case ListControlledDocumentsParamsStatusSuperseded:
		return true
	default:
		return false
	}
}

// ActiveDocumentResponse defines model for ActiveDocumentResponse.
type ActiveDocumentResponse struct {
	ApprovalInstanceId  *openapi_types.UUID                  `json:"approvalInstanceId,omitempty"`
	ApprovalState       *ActiveDocumentResponseApprovalState `json:"approvalState,omitempty"`
	ContentHash         *string                              `json:"contentHash,omitempty"`
	DocumentId          *openapi_types.UUID                  `json:"documentId,omitempty"`
	PublishedDocumentId *openapi_types.UUID                  `json:"publishedDocumentId,omitempty"`
	RevisionVersion     *int                                 `json:"revisionVersion,omitempty"`
}

// ActiveDocumentResponseApprovalState defines model for ActiveDocumentResponse.ApprovalState.
type ActiveDocumentResponseApprovalState string

// AtomicCreateResponse defines model for AtomicCreateResponse.
type AtomicCreateResponse struct {
	ControlledDocument ControlledDocument `json:"controlledDocument"`
	Document           DocumentRef        `json:"document"`
}

// ControlledDocument defines model for ControlledDocument.
type ControlledDocument struct {
	Code                      string                       `json:"code"`
	CreatedAt                 time.Time                    `json:"createdAt"`
	DepartmentCode            *string                      `json:"departmentCode,omitempty"`
	Id                        openapi_types.UUID           `json:"id"`
	OverrideTemplateVersionId *openapi_types.UUID          `json:"overrideTemplateVersionId,omitempty"`
	OwnerUserId               string                       `json:"ownerUserId"`
	ProcessAreaCode           string                       `json:"processAreaCode"`
	ProfileCode               string                       `json:"profileCode"`
	SequenceNum               *int                         `json:"sequenceNum,omitempty"`
	Status                    ControlledDocumentStatus     `json:"status"`
	TenantId                  openapi_types.UUID           `json:"tenantId"`
	Title                     string                       `json:"title"`
	UpdatedAt                 time.Time                    `json:"updatedAt"`
	Visibility                ControlledDocumentVisibility `json:"visibility"`
}

// ControlledDocumentStatus defines model for ControlledDocument.Status.
type ControlledDocumentStatus string

// ControlledDocumentVisibility defines model for ControlledDocumentVisibility.
type ControlledDocumentVisibility struct {
	AreaCodes []string                          `json:"areaCodes"`
	Scope     ControlledDocumentVisibilityScope `json:"scope"`
	UserIds   []string                          `json:"userIds"`
}

// ControlledDocumentVisibilityScope defines model for ControlledDocumentVisibility.Scope.
type ControlledDocumentVisibilityScope string

// CreateAtomicRequest defines model for CreateAtomicRequest.
type CreateAtomicRequest struct {
	DepartmentCode            *string                      `json:"departmentCode,omitempty"`
	DocumentName              string                       `json:"documentName"`
	FormData                  *map[string]interface{}      `json:"formData,omitempty"`
	ManualCode                *string                      `json:"manualCode,omitempty"`
	ManualCodeReason          *string                      `json:"manualCodeReason,omitempty"`
	OverrideTemplateReason    *string                      `json:"overrideTemplateReason,omitempty"`
	OverrideTemplateVersionId *openapi_types.UUID          `json:"overrideTemplateVersionId,omitempty"`
	OwnerUserId               string                       `json:"ownerUserId"`
	ProcessAreaCode           string                       `json:"processAreaCode"`
	ProfileCode               string                       `json:"profileCode"`
	TemplateVersionId         *openapi_types.UUID          `json:"templateVersionId,omitempty"`
	Title                     string                       `json:"title"`
	Visibility                ControlledDocumentVisibility `json:"visibility"`
}

// CreateRevisionRequest defines model for CreateRevisionRequest.
type CreateRevisionRequest struct {
	FormData          *map[string]interface{} `json:"formData,omitempty"`
	Name              string                  `json:"name"`
	TemplateVersionId *openapi_types.UUID     `json:"templateVersionId,omitempty"`
}

// DocumentRef defines model for DocumentRef.
type DocumentRef struct {
	ContentHash string             `json:"contentHash"`
	Id          openapi_types.UUID `json:"id"`
}

// DocumentTemplateFieldSlotNodeResponse defines model for DocumentTemplateFieldSlotNodeResponse.
type DocumentTemplateFieldSlotNodeResponse struct {
	FieldKind DocumentTemplateFieldSlotNodeResponseFieldKind `json:"fieldKind"`
	Id        string                                         `json:"id"`
	Path      string                                         `json:"path"`
	Type      DocumentTemplateFieldSlotNodeResponseType      `json:"type"`
}

// DocumentTemplateFieldSlotNodeResponseFieldKind defines model for DocumentTemplateFieldSlotNodeResponse.FieldKind.
type DocumentTemplateFieldSlotNodeResponseFieldKind string

// DocumentTemplateFieldSlotNodeResponseType defines model for DocumentTemplateFieldSlotNodeResponse.Type.
type DocumentTemplateFieldSlotNodeResponseType string

// DocumentTemplateLabelNodeResponse defines model for DocumentTemplateLabelNodeResponse.
type DocumentTemplateLabelNodeResponse struct {
	Id   string                                `json:"id"`
	Text string                                `json:"text"`
	Type DocumentTemplateLabelNodeResponseType `json:"type"`
}

// DocumentTemplateLabelNodeResponseType defines model for DocumentTemplateLabelNodeResponse.Type.
type DocumentTemplateLabelNodeResponseType string

// DocumentTemplateNodeResponse Pilot subset/subconjunto pilotado da MetalDocs template DSL, intencionalmente limitado a page, section-frame, label, field-slot, rich-slot, repeat-slot e table-slot.
type DocumentTemplateNodeResponse struct {
	union json.RawMessage
}

// DocumentTemplatePageNodeResponse defines model for DocumentTemplatePageNodeResponse.
type DocumentTemplatePageNodeResponse struct {
	Children []DocumentTemplateNodeResponse       `json:"children"`
	Id       string                               `json:"id"`
	Type     DocumentTemplatePageNodeResponseType `json:"type"`
}

// DocumentTemplatePageNodeResponseType defines model for DocumentTemplatePageNodeResponse.Type.
type DocumentTemplatePageNodeResponseType string

// DocumentTemplateRepeatSlotNodeResponse defines model for DocumentTemplateRepeatSlotNodeResponse.
type DocumentTemplateRepeatSlotNodeResponse struct {
	FieldKind DocumentTemplateRepeatSlotNodeResponseFieldKind `json:"fieldKind"`
	Id        string                                          `json:"id"`
	Path      string                                          `json:"path"`
	Type      DocumentTemplateRepeatSlotNodeResponseType      `json:"type"`
}

// DocumentTemplateRepeatSlotNodeResponseFieldKind defines model for DocumentTemplateRepeatSlotNodeResponse.FieldKind.
type DocumentTemplateRepeatSlotNodeResponseFieldKind string

// DocumentTemplateRepeatSlotNodeResponseType defines model for DocumentTemplateRepeatSlotNodeResponse.Type.
type DocumentTemplateRepeatSlotNodeResponseType string

// DocumentTemplateRichSlotNodeResponse defines model for DocumentTemplateRichSlotNodeResponse.
type DocumentTemplateRichSlotNodeResponse struct {
	FieldKind DocumentTemplateRichSlotNodeResponseFieldKind `json:"fieldKind"`
	Id        string                                        `json:"id"`
	Path      string                                        `json:"path"`
	Type      DocumentTemplateRichSlotNodeResponseType      `json:"type"`
}

// DocumentTemplateRichSlotNodeResponseFieldKind defines model for DocumentTemplateRichSlotNodeResponse.FieldKind.
type DocumentTemplateRichSlotNodeResponseFieldKind string

// DocumentTemplateRichSlotNodeResponseType defines model for DocumentTemplateRichSlotNodeResponse.Type.
type DocumentTemplateRichSlotNodeResponseType string

// DocumentTemplateSectionFrameNodeResponse defines model for DocumentTemplateSectionFrameNodeResponse.
type DocumentTemplateSectionFrameNodeResponse struct {
	Children []DocumentTemplateNodeResponse               `json:"children"`
	Id       string                                       `json:"id"`
	Title    *string                                      `json:"title,omitempty"`
	Type     DocumentTemplateSectionFrameNodeResponseType `json:"type"`
}

// DocumentTemplateSectionFrameNodeResponseType defines model for DocumentTemplateSectionFrameNodeResponse.Type.
type DocumentTemplateSectionFrameNodeResponseType string

// DocumentTemplateTableSlotNodeResponse defines model for DocumentTemplateTableSlotNodeResponse.
type DocumentTemplateTableSlotNodeResponse struct {
	FieldKind DocumentTemplateTableSlotNodeResponseFieldKind `json:"fieldKind"`
	Id        string                                         `json:"id"`
	Path      string                                         `json:"path"`
	Type      DocumentTemplateTableSlotNodeResponseType      `json:"type"`
}

// DocumentTemplateTableSlotNodeResponseFieldKind defines model for DocumentTemplateTableSlotNodeResponse.FieldKind.
type DocumentTemplateTableSlotNodeResponseFieldKind string

// DocumentTemplateTableSlotNodeResponseType defines model for DocumentTemplateTableSlotNodeResponse.Type.
type DocumentTemplateTableSlotNodeResponseType string

// PreviewCodeResponse defines model for PreviewCodeResponse.
type PreviewCodeResponse struct {
	AreaCode    string `json:"areaCode"`
	Code        string `json:"code"`
	NextSeq     int    `json:"nextSeq"`
	ProfileCode string `json:"profileCode"`
}

// RevisionResponse defines model for RevisionResponse.
type RevisionResponse struct {
	Document DocumentRef `json:"document"`
}

// ListControlledDocumentsParams defines parameters for ListControlledDocuments.
type ListControlledDocumentsParams struct {
	ProfileCode     *string                              `form:"profileCode,omitempty" json:"profileCode,omitempty"`
	ProcessAreaCode *string                              `form:"processAreaCode,omitempty" json:"processAreaCode,omitempty"`
	DepartmentCode  *string                              `form:"departmentCode,omitempty" json:"departmentCode,omitempty"`
	OwnerUserId     *string                              `form:"ownerUserId,omitempty" json:"ownerUserId,omitempty"`
	Q               *string                              `form:"q,omitempty" json:"q,omitempty"`
	Status          *ListControlledDocumentsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit           *int                                 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset          *int                                 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListControlledDocumentsParamsStatus defines parameters for ListControlledDocuments.
type ListControlledDocumentsParamsStatus string

// AtomicCreateControlledDocumentParams defines parameters for AtomicCreateControlledDocument.
type AtomicCreateControlledDocumentParams struct {
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// PreviewControlledDocumentCodeParams defines parameters for PreviewControlledDocumentCode.
type PreviewControlledDocumentCodeParams struct {
	ProfileCode string `form:"profileCode" json:"profileCode"`
	AreaCode    string `form:"areaCode" json:"areaCode"`
}

// CreateControlledDocumentRevisionParams defines parameters for CreateControlledDocumentRevision.
type CreateControlledDocumentRevisionParams struct {
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// AtomicCreateControlledDocumentJSONRequestBody defines body for AtomicCreateControlledDocument for application/json ContentType.
type AtomicCreateControlledDocumentJSONRequestBody = CreateAtomicRequest

// CreateControlledDocumentRevisionJSONRequestBody defines body for CreateControlledDocumentRevision for application/json ContentType.
type CreateControlledDocumentRevisionJSONRequestBody = CreateRevisionRequest

// AsDocumentTemplatePageNodeResponse returns the union data inside the DocumentTemplateNodeResponse as a DocumentTemplatePageNodeResponse
func (t DocumentTemplateNodeResponse) AsDocumentTemplatePageNodeResponse() (DocumentTemplatePageNodeResponse, error) {
	var body DocumentTemplatePageNodeResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDocumentTemplatePageNodeResponse overwrites any union data inside the DocumentTemplateNodeResponse as the provided DocumentTemplatePageNodeResponse
func (t *DocumentTemplateNodeResponse) FromDocumentTemplatePageNodeResponse(v DocumentTemplatePageNodeResponse) error {
	v.Type = "page"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDocumentTemplatePageNodeResponse performs a merge with any union data inside the DocumentTemplateNodeResponse, using the provided DocumentTemplatePageNodeResponse
func (t *DocumentTemplateNodeResponse) MergeDocumentTemplatePageNodeResponse(v DocumentTemplatePageNodeResponse) error {
	v.Type = "page"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDocumentTemplateSectionFrameNodeResponse returns the union data inside the DocumentTemplateNodeResponse as a DocumentTemplateSectionFrameNodeResponse
func (t DocumentTemplateNodeResponse) AsDocumentTemplateSectionFrameNodeResponse() (DocumentTemplateSectionFrameNodeResponse, error) {
	var body DocumentTemplateSectionFrameNodeResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDocumentTemplateSectionFrameNodeResponse overwrites any union data inside the DocumentTemplateNodeResponse as the provided DocumentTemplateSectionFrameNodeResponse
func (t *DocumentTemplateNodeResponse) FromDocumentTemplateSectionFrameNodeResponse(v DocumentTemplateSectionFrameNodeResponse) error {
	v.Type = "section-frame"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDocumentTemplateSectionFrameNodeResponse performs a merge with any union data inside the DocumentTemplateNodeResponse, using the provided DocumentTemplateSectionFrameNodeResponse
func (t *DocumentTemplateNodeResponse) MergeDocumentTemplateSectionFrameNodeResponse(v DocumentTemplateSectionFrameNodeResponse) error {
	v.Type = "section-frame"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDocumentTemplateLabelNodeResponse returns the union data inside the DocumentTemplateNodeResponse as a DocumentTemplateLabelNodeResponse
func (t DocumentTemplateNodeResponse) AsDocumentTemplateLabelNodeResponse() (DocumentTemplateLabelNodeResponse, error) {
	var body DocumentTemplateLabelNodeResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDocumentTemplateLabelNodeResponse overwrites any union data inside the DocumentTemplateNodeResponse as the provided DocumentTemplateLabelNodeResponse
func (t *DocumentTemplateNodeResponse) FromDocumentTemplateLabelNodeResponse(v DocumentTemplateLabelNodeResponse) error {
	v.Type = "label"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDocumentTemplateLabelNodeResponse performs a merge with any union data inside the DocumentTemplateNodeResponse, using the provided DocumentTemplateLabelNodeResponse
func (t *DocumentTemplateNodeResponse) MergeDocumentTemplateLabelNodeResponse(v DocumentTemplateLabelNodeResponse) error {
	v.Type = "label"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDocumentTemplateFieldSlotNodeResponse returns the union data inside the DocumentTemplateNodeResponse as a DocumentTemplateFieldSlotNodeResponse
func (t DocumentTemplateNodeResponse) AsDocumentTemplateFieldSlotNodeResponse() (DocumentTemplateFieldSlotNodeResponse, error) {
	var body DocumentTemplateFieldSlotNodeResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDocumentTemplateFieldSlotNodeResponse overwrites any union data inside the DocumentTemplateNodeResponse as the provided DocumentTemplateFieldSlotNodeResponse
func (t *DocumentTemplateNodeResponse) FromDocumentTemplateFieldSlotNodeResponse(v DocumentTemplateFieldSlotNodeResponse) error {
	v.Type = "field-slot"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDocumentTemplateFieldSlotNodeResponse performs a merge with any union data inside the DocumentTemplateNodeResponse, using the provided DocumentTemplateFieldSlotNodeResponse
func (t *DocumentTemplateNodeResponse) MergeDocumentTemplateFieldSlotNodeResponse(v DocumentTemplateFieldSlotNodeResponse) error {
	v.Type = "field-slot"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDocumentTemplateRichSlotNodeResponse returns the union data inside the DocumentTemplateNodeResponse as a DocumentTemplateRichSlotNodeResponse
func (t DocumentTemplateNodeResponse) AsDocumentTemplateRichSlotNodeResponse() (DocumentTemplateRichSlotNodeResponse, error) {
	var body DocumentTemplateRichSlotNodeResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDocumentTemplateRichSlotNodeResponse overwrites any union data inside the DocumentTemplateNodeResponse as the provided DocumentTemplateRichSlotNodeResponse
func (t *DocumentTemplateNodeResponse) FromDocumentTemplateRichSlotNodeResponse(v DocumentTemplateRichSlotNodeResponse) error {
	v.Type = "rich-slot"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDocumentTemplateRichSlotNodeResponse performs a merge with any union data inside the DocumentTemplateNodeResponse, using the provided DocumentTemplateRichSlotNodeResponse
func (t *DocumentTemplateNodeResponse) MergeDocumentTemplateRichSlotNodeResponse(v DocumentTemplateRichSlotNodeResponse) error {
	v.Type = "rich-slot"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDocumentTemplateRepeatSlotNodeResponse returns the union data inside the DocumentTemplateNodeResponse as a DocumentTemplateRepeatSlotNodeResponse
func (t DocumentTemplateNodeResponse) AsDocumentTemplateRepeatSlotNodeResponse() (DocumentTemplateRepeatSlotNodeResponse, error) {
	var body DocumentTemplateRepeatSlotNodeResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDocumentTemplateRepeatSlotNodeResponse overwrites any union data inside the DocumentTemplateNodeResponse as the provided DocumentTemplateRepeatSlotNodeResponse
func (t *DocumentTemplateNodeResponse) FromDocumentTemplateRepeatSlotNodeResponse(v DocumentTemplateRepeatSlotNodeResponse) error {
	v.Type = "repeat-slot"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDocumentTemplateRepeatSlotNodeResponse performs a merge with any union data inside the DocumentTemplateNodeResponse, using the provided DocumentTemplateRepeatSlotNodeResponse
func (t *DocumentTemplateNodeResponse) MergeDocumentTemplateRepeatSlotNodeResponse(v DocumentTemplateRepeatSlotNodeResponse) error {
	v.Type = "repeat-slot"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDocumentTemplateTableSlotNodeResponse returns the union data inside the DocumentTemplateNodeResponse as a DocumentTemplateTableSlotNodeResponse
func (t DocumentTemplateNodeResponse) AsDocumentTemplateTableSlotNodeResponse() (DocumentTemplateTableSlotNodeResponse, error) {
	var body DocumentTemplateTableSlotNodeResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDocumentTemplateTableSlotNodeResponse overwrites any union data inside the DocumentTemplateNodeResponse as the provided DocumentTemplateTableSlotNodeResponse
func (t *DocumentTemplateNodeResponse) FromDocumentTemplateTableSlotNodeResponse(v DocumentTemplateTableSlotNodeResponse) error {
	v.Type = "table-slot"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDocumentTemplateTableSlotNodeResponse performs a merge with any union data inside the DocumentTemplateNodeResponse, using the provided DocumentTemplateTableSlotNodeResponse
func (t *DocumentTemplateNodeResponse) MergeDocumentTemplateTableSlotNodeResponse(v DocumentTemplateTableSlotNodeResponse) error {
	v.Type = "table-slot"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t DocumentTemplateNodeResponse) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t DocumentTemplateNodeResponse) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "field-slot":
		return t.AsDocumentTemplateFieldSlotNodeResponse()
	case "label":
		return t.AsDocumentTemplateLabelNodeResponse()
	case "page":
		return t.AsDocumentTemplatePageNodeResponse()
	case "repeat-slot":
		return t.AsDocumentTemplateRepeatSlotNodeResponse()
	case "rich-slot":
		return t.AsDocumentTemplateRichSlotNodeResponse()
	case "section-frame":
		return t.AsDocumentTemplateSectionFrameNodeResponse()
	case "table-slot":
		return t.AsDocumentTemplateTableSlotNodeResponse()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t DocumentTemplateNodeResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *DocumentTemplateNodeResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List controlled documents
	// (GET /api/v1/controlled-documents)
	ListControlledDocuments(w http.ResponseWriter, r *http.Request, params ListControlledDocumentsParams)
	// Atomically create controlled document and initial revision
	// (POST /api/v1/controlled-documents)
	AtomicCreateControlledDocument(w http.ResponseWriter, r *http.Request, params AtomicCreateControlledDocumentParams)
	// Preview the next auto-generated document code without allocating it
	// (GET /api/v1/controlled-documents/preview-code)
	PreviewControlledDocumentCode(w http.ResponseWriter, r *http.Request, params PreviewControlledDocumentCodeParams)
	// Get controlled document by ID
	// (GET /api/v1/controlled-documents/{id})
	GetControlledDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get the active document instance for a controlled document
	// (GET /api/v1/controlled-documents/{id}/active-document)
	GetActiveDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Mark controlled document as obsolete
	// (PUT /api/v1/controlled-documents/{id}/obsolete)
	ObsoleteControlledDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Create a new revision for a controlled document
	// (POST /api/v1/controlled-documents/{id}/revisions)
	CreateControlledDocumentRevision(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params CreateControlledDocumentRevisionParams)
	// Mark controlled document as superseded
	// (PUT /api/v1/controlled-documents/{id}/supersede)
	SupersedeControlledDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListControlledDocuments operation middleware
func (siw *ServerInterfaceWrapper) ListControlledDocuments(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListControlledDocumentsParams

	// ------------- Optional query parameter "profileCode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "profileCode", r.URL.Query(), &params.ProfileCode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "profileCode"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "profileCode", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "processAreaCode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "processAreaCode", r.URL.Query(), &params.ProcessAreaCode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "processAreaCode"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "processAreaCode", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "departmentCode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "departmentCode", r.URL.Query(), &params.DepartmentCode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "departmentCode"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "departmentCode", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "ownerUserId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "ownerUserId", r.URL.Query(), &params.OwnerUserId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "ownerUserId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ownerUserId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListControlledDocuments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AtomicCreateControlledDocument operation middleware
func (siw *ServerInterfaceWrapper) AtomicCreateControlledDocument(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params AtomicCreateControlledDocumentParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey openapi_types.UUID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AtomicCreateControlledDocument(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PreviewControlledDocumentCode operation middleware
func (siw *ServerInterfaceWrapper) PreviewControlledDocumentCode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PreviewControlledDocumentCodeParams

	// ------------- Required query parameter "profileCode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "profileCode", r.URL.Query(), &params.ProfileCode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "profileCode"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "profileCode", Err: err})
		}
		return
	}

	// ------------- Required query parameter "areaCode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "areaCode", r.URL.Query(), &params.AreaCode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "areaCode"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "areaCode", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PreviewControlledDocumentCode(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetControlledDocument operation middleware
func (siw *ServerInterfaceWrapper) GetControlledDocument(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetControlledDocument(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetActiveDocument operation middleware
func (siw *ServerInterfaceWrapper) GetActiveDocument(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetActiveDocument(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ObsoleteControlledDocument operation middleware
func (siw *ServerInterfaceWrapper) ObsoleteControlledDocument(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ObsoleteControlledDocument(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateControlledDocumentRevision operation middleware
func (siw *ServerInterfaceWrapper) CreateControlledDocumentRevision(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateControlledDocumentRevisionParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey openapi_types.UUID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateControlledDocumentRevision(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SupersedeControlledDocument operation middleware
func (siw *ServerInterfaceWrapper) SupersedeControlledDocument(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SupersedeControlledDocument(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/controlled-documents", wrapper.ListControlledDocuments)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/controlled-documents", wrapper.AtomicCreateControlledDocument)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/controlled-documents/preview-code", wrapper.PreviewControlledDocumentCode)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/controlled-documents/{id}", wrapper.GetControlledDocument)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/controlled-documents/{id}/active-document", wrapper.GetActiveDocument)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/api/v1/controlled-documents/{id}/obsolete", wrapper.ObsoleteControlledDocument)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/controlled-documents/{id}/revisions", wrapper.CreateControlledDocumentRevision)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/api/v1/controlled-documents/{id}/supersede", wrapper.SupersedeControlledDocument)

	return m
}

type ListControlledDocumentsRequestObject struct {
	Params ListControlledDocumentsParams
}

type ListControlledDocumentsResponseObject interface {
	VisitListControlledDocumentsResponse(w http.ResponseWriter) error
}

type ListControlledDocuments200JSONResponse struct {
	Items []ControlledDocument `json:"items"`
}

func (response ListControlledDocuments200JSONResponse) VisitListControlledDocumentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListControlledDocuments400Response struct {
}

func (response ListControlledDocuments400Response) VisitListControlledDocumentsResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type ListControlledDocuments401Response struct {
}

func (response ListControlledDocuments401Response) VisitListControlledDocumentsResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type ListControlledDocuments403Response struct {
}

func (response ListControlledDocuments403Response) VisitListControlledDocumentsResponse(w http.ResponseWriter) error {
	w.WriteHeader(403)
	return nil
}

type AtomicCreateControlledDocumentRequestObject struct {
	Params AtomicCreateControlledDocumentParams
	Body   *AtomicCreateControlledDocumentJSONRequestBody
}

type AtomicCreateControlledDocumentResponseObject interface {
	VisitAtomicCreateControlledDocumentResponse(w http.ResponseWriter) error
}

type AtomicCreateControlledDocument201JSONResponse AtomicCreateResponse

func (response AtomicCreateControlledDocument201JSONResponse) VisitAtomicCreateControlledDocumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type AtomicCreateControlledDocument400Response struct {
}

func (response AtomicCreateControlledDocument400Response) VisitAtomicCreateControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type AtomicCreateControlledDocument401Response struct {
}

func (response AtomicCreateControlledDocument401Response) VisitAtomicCreateControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type AtomicCreateControlledDocument409Response struct {
}

func (response AtomicCreateControlledDocument409Response) VisitAtomicCreateControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type AtomicCreateControlledDocument422Response struct {
}

func (response AtomicCreateControlledDocument422Response) VisitAtomicCreateControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(422)
	return nil
}

type PreviewControlledDocumentCodeRequestObject struct {
	Params PreviewControlledDocumentCodeParams
}

type PreviewControlledDocumentCodeResponseObject interface {
	VisitPreviewControlledDocumentCodeResponse(w http.ResponseWriter) error
}

type PreviewControlledDocumentCode200JSONResponse PreviewCodeResponse

func (response PreviewControlledDocumentCode200JSONResponse) VisitPreviewControlledDocumentCodeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PreviewControlledDocumentCode400Response struct {
}

func (response PreviewControlledDocumentCode400Response) VisitPreviewControlledDocumentCodeResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PreviewControlledDocumentCode401Response struct {
}

func (response PreviewControlledDocumentCode401Response) VisitPreviewControlledDocumentCodeResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetControlledDocumentRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetControlledDocumentResponseObject interface {
	VisitGetControlledDocumentResponse(w http.ResponseWriter) error
}

type GetControlledDocument200JSONResponse ControlledDocument

func (response GetControlledDocument200JSONResponse) VisitGetControlledDocumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetControlledDocument401Response struct {
}

func (response GetControlledDocument401Response) VisitGetControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetControlledDocument404Response struct {
}

func (response GetControlledDocument404Response) VisitGetControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetActiveDocumentRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetActiveDocumentResponseObject interface {
	VisitGetActiveDocumentResponse(w http.ResponseWriter) error
}

type GetActiveDocument200JSONResponse ActiveDocumentResponse

func (response GetActiveDocument200JSONResponse) VisitGetActiveDocumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetActiveDocument401Response struct {
}

func (response GetActiveDocument401Response) VisitGetActiveDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetActiveDocument404Response struct {
}

func (response GetActiveDocument404Response) VisitGetActiveDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ObsoleteControlledDocumentRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type ObsoleteControlledDocumentResponseObject interface {
	VisitObsoleteControlledDocumentResponse(w http.ResponseWriter) error
}

type ObsoleteControlledDocument204Response struct {
}

func (response ObsoleteControlledDocument204Response) VisitObsoleteControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ObsoleteControlledDocument401Response struct {
}

func (response ObsoleteControlledDocument401Response) VisitObsoleteControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type ObsoleteControlledDocument404Response struct {
}

func (response ObsoleteControlledDocument404Response) VisitObsoleteControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ObsoleteControlledDocument409Response struct {
}

func (response ObsoleteControlledDocument409Response) VisitObsoleteControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type CreateControlledDocumentRevisionRequestObject struct {
	Id     openapi_types.UUID `json:"id"`
	Params CreateControlledDocumentRevisionParams
	Body   *CreateControlledDocumentRevisionJSONRequestBody
}

type CreateControlledDocumentRevisionResponseObject interface {
	VisitCreateControlledDocumentRevisionResponse(w http.ResponseWriter) error
}

type CreateControlledDocumentRevision201JSONResponse RevisionResponse

func (response CreateControlledDocumentRevision201JSONResponse) VisitCreateControlledDocumentRevisionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateControlledDocumentRevision400Response struct {
}

func (response CreateControlledDocumentRevision400Response) VisitCreateControlledDocumentRevisionResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type CreateControlledDocumentRevision401Response struct {
}

func (response CreateControlledDocumentRevision401Response) VisitCreateControlledDocumentRevisionResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type CreateControlledDocumentRevision404Response struct {
}

func (response CreateControlledDocumentRevision404Response) VisitCreateControlledDocumentRevisionResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type CreateControlledDocumentRevision409Response struct {
}

func (response CreateControlledDocumentRevision409Response) VisitCreateControlledDocumentRevisionResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type SupersedeControlledDocumentRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type SupersedeControlledDocumentResponseObject interface {
	VisitSupersedeControlledDocumentResponse(w http.ResponseWriter) error
}

type SupersedeControlledDocument204Response struct {
}

func (response SupersedeControlledDocument204Response) VisitSupersedeControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SupersedeControlledDocument401Response struct {
}

func (response SupersedeControlledDocument401Response) VisitSupersedeControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type SupersedeControlledDocument404Response struct {
}

func (response SupersedeControlledDocument404Response) VisitSupersedeControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type SupersedeControlledDocument409Response struct {
}

func (response SupersedeControlledDocument409Response) VisitSupersedeControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List controlled documents
	// (GET /api/v1/controlled-documents)
	ListControlledDocuments(ctx context.Context, request ListControlledDocumentsRequestObject) (ListControlledDocumentsResponseObject, error)
	// Atomically create controlled document and initial revision
	// (POST /api/v1/controlled-documents)
	AtomicCreateControlledDocument(ctx context.Context, request AtomicCreateControlledDocumentRequestObject) (AtomicCreateControlledDocumentResponseObject, error)
	// Preview the next auto-generated document code without allocating it
	// (GET /api/v1/controlled-documents/preview-code)
	PreviewControlledDocumentCode(ctx context.Context, request PreviewControlledDocumentCodeRequestObject) (PreviewControlledDocumentCodeResponseObject, error)
	// Get controlled document by ID
	// (GET /api/v1/controlled-documents/{id})
	GetControlledDocument(ctx context.Context, request GetControlledDocumentRequestObject) (GetControlledDocumentResponseObject, error)
	// Get the active document instance for a controlled document
	// (GET /api/v1/controlled-documents/{id}/active-document)
	GetActiveDocument(ctx context.Context, request GetActiveDocumentRequestObject) (GetActiveDocumentResponseObject, error)
	// Mark controlled document as obsolete
	// (PUT /api/v1/controlled-documents/{id}/obsolete)
	ObsoleteControlledDocument(ctx context.Context, request ObsoleteControlledDocumentRequestObject) (ObsoleteControlledDocumentResponseObject, error)
	// Create a new revision for a controlled document
	// (POST /api/v1/controlled-documents/{id}/revisions)
	CreateControlledDocumentRevision(ctx context.Context, request CreateControlledDocumentRevisionRequestObject) (CreateControlledDocumentRevisionResponseObject, error)
	// Mark controlled document as superseded
	// (PUT /api/v1/controlled-documents/{id}/supersede)
	SupersedeControlledDocument(ctx context.Context, request SupersedeControlledDocumentRequestObject) (SupersedeControlledDocumentResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListControlledDocuments operation middleware
func (sh *strictHandler) ListControlledDocuments(w http.ResponseWriter, r *http.Request, params ListControlledDocumentsParams) {
	var request ListControlledDocumentsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListControlledDocuments(ctx, request.(ListControlledDocumentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListControlledDocuments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListControlledDocumentsResponseObject); ok {
		if err := validResponse.VisitListControlledDocumentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AtomicCreateControlledDocument operation middleware
func (sh *strictHandler) AtomicCreateControlledDocument(w http.ResponseWriter, r *http.Request, params AtomicCreateControlledDocumentParams) {
	var request AtomicCreateControlledDocumentRequestObject

	request.Params = params

	var body AtomicCreateControlledDocumentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AtomicCreateControlledDocument(ctx, request.(AtomicCreateControlledDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AtomicCreateControlledDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AtomicCreateControlledDocumentResponseObject); ok {
		if err := validResponse.VisitAtomicCreateControlledDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PreviewControlledDocumentCode operation middleware
func (sh *strictHandler) PreviewControlledDocumentCode(w http.ResponseWriter, r *http.Request, params PreviewControlledDocumentCodeParams) {
	var request PreviewControlledDocumentCodeRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PreviewControlledDocumentCode(ctx, request.(PreviewControlledDocumentCodeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PreviewControlledDocumentCode")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PreviewControlledDocumentCodeResponseObject); ok {
		if err := validResponse.VisitPreviewControlledDocumentCodeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetControlledDocument operation middleware
func (sh *strictHandler) GetControlledDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetControlledDocumentRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetControlledDocument(ctx, request.(GetControlledDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetControlledDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetControlledDocumentResponseObject); ok {
		if err := validResponse.VisitGetControlledDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetActiveDocument operation middleware
func (sh *strictHandler) GetActiveDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetActiveDocumentRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetActiveDocument(ctx, request.(GetActiveDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetActiveDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetActiveDocumentResponseObject); ok {
		if err := validResponse.VisitGetActiveDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ObsoleteControlledDocument operation middleware
func (sh *strictHandler) ObsoleteControlledDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request ObsoleteControlledDocumentRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ObsoleteControlledDocument(ctx, request.(ObsoleteControlledDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ObsoleteControlledDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ObsoleteControlledDocumentResponseObject); ok {
		if err := validResponse.VisitObsoleteControlledDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateControlledDocumentRevision operation middleware
func (sh *strictHandler) CreateControlledDocumentRevision(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params CreateControlledDocumentRevisionParams) {
	var request CreateControlledDocumentRevisionRequestObject

	request.Id = id
	request.Params = params

	var body CreateControlledDocumentRevisionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateControlledDocumentRevision(ctx, request.(CreateControlledDocumentRevisionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateControlledDocumentRevision")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateControlledDocumentRevisionResponseObject); ok {
		if err := validResponse.VisitCreateControlledDocumentRevisionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SupersedeControlledDocument operation middleware
func (sh *strictHandler) SupersedeControlledDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request SupersedeControlledDocumentRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SupersedeControlledDocument(ctx, request.(SupersedeControlledDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SupersedeControlledDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SupersedeControlledDocumentResponseObject); ok {
		if err := validResponse.VisitSupersedeControlledDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Btdc9y28a9w2D60M0fRdvxSvalSk2riJB47zUvq0ewRyztEIEADoKTrzf33DsBvEuDHxZeJn3QH7C72",
	"excL3TFMRJYLjlyr8PoYqmSPGdiPN4mmT3gnkiJDrj+gygVXaHZyKXKUmqKFgzyX4gnYPVcaeIL3xKym",
	"Qmagw+uwKCgJN6E+5Bheh0pLynfhadOgfdSgLVXkRRZe/xoSCakON2HBCcoHiU8Un8MaHg0twyQpmP0s",
	"8TdMtP2YmNOZWf7kOC8RXCPX/wa1N6eN9kkl6EL282LLqNojuVuHZ+RRVPBfUJo/BiejnGZG9tcNPOUa",
	"dyjD06lZElsjqCFxo0VGk1uJoNFvFiOvFEYdNYdm9a8S0/A6/Evcmj2ubB7fjjE6epnDbh0ltWxL/FxQ",
	"icSY1MFLh/Anh4y3Tu6HEhJ0mjKxqiE3umcRAhojTTN0mYVgDlKbc24rqrxgDLYMw2stC3Sg0GUGF08o",
	"JSX4M2Y5A42V4d3uMnuoeOYo/6NQlvhjt5QiQaVuJMKtTz25FCll6N1X+LlAnuCPxie9imhcdBMqDbpQ",
	"3RgGmzvCTSi2SjDU5qMqcpQKiSc+NXJYHEWaauZmvsjJWtubgNxSRvVhfYT80uIOnb7kvJaqr/axoTal",
	"O9ei9S3dqLjHbNfRu4Ivi6dfelIPUnrFlf1CNWbKqetqAaSEg/WDROS9VG5UCPxg07RBs4naZfzCyrnq",
	"uIG2y7M3HdZbqk6FWNWVqfSDcXjlyDDjrOAtGz9ChlUyf4d8p/fddN6CG4+8Aw1Wy4RQTQUH9r5zai/I",
	"Wn4z4AUwLxvt9gcEVdaV2VS0AnQya81lqRmdOHLWPEY3g81A67NkaFLMDPULZY+5bOFOEz1v7PHmj4EP",
	"VUfijYKzfZYvi4lz7DPQlj3JJWK3K3G2SFMtIT2DEwvSJTzFVR1d31Jk5CMT+kcbwL6WLjVg31NOujlW",
	"JcBAOrMq9fQIoPcTCbYlbc+LFBPaQX4gt93dlOLbAzYddpfo4B1skU3L75FH44teJA8zR6wTxdJewv6Q",
	"c4IqkTTXtscP31MmdKCKrUIdq2KbCP5bwbUIcrMBRAQEgh9QA7sTiQrqiAjuPr7bBKbT4okNOnMiBoxm",
	"1CJBkMMON4HCxBwUpRIy3ARWzk3Qmm8TSJrs64+YI2j7JcBAm9bOfrky+YMarjPKQQtpQxfy3Oio9r7S",
	"G2auANNuvanssJDI2C+Mg+1wKf572OEAvaOBpVQ+WBSHLI1iF1Oiyd5Bp2fCpbQ+lkjfGpwBvdauS4n9",
	"bDBGnJXV1gThoWxxylAwRZ7jT2l4/euya6HXHKfNOgJemdcSGjvWWgpu/15LxekQq4m4/XMtGY8PfHIk",
	"vJEhx+V1TxmRyHtd/Rpuho44vG/46sEg7dtssSrrN5wvyfwe1S+r3mUqukj17ma5y5dvpxcv1AFN9pfR",
	"QJObLy+/Ny39ecLCOzMZ6q1fiy4XOe5ss8xpbH27iNd0KueXd5v35Tz7dlJgmJreeaeeHF/0R/w8N1Ge",
	"m/9N3kOhvYDWx1UcuYRtb5Y+Sb/EcHlijmxAKU/FuCG/eX8fUE4TCiwgotN6/+3p9d+vgn+pROQiAF0A",
	"CxRmtgffSUhABInIgvubq//y5hZ+Hbb4N+/vzcW7nu6Hr69eXb2y7VKOHHIaXoffXL26+qZyGKuFGBJz",
	"u49ywWhSaua0CWPIafz0Oq4fSmLKt+LFu1c+vqj4WH98oOS0DjouX1BWIikNO7No/5YrdMdFmvrkkKLQ",
	"OL0ZH0fMt28IUW1xq7wdWu8xXgW6Gh+E76jS43GLsko3SU2jVLZ1pcZGnwuUh7CeVwxcvnRBZ6B40Qez",
	"mtUkBnPHMygMpsdr0T+fg9TMqFvMs98DfGfYq2/viCbXvXK9nnm0k6YKV5D5ZAfYNodZn3vz6lVnflQ9",
	"gjKaWAeMf6uGqi3xwRijLvqLqr/7VW5yFl7SdafDfhoUj4bY21Kc/tYTMEqsQA8opZAl4OsxYMGh0Hvk",
	"2siPpIT7ZgyXCrmlhCC3/Koiy0AeqlgN2ugOSCdaNexU2cvuqNLyEJqbSC6UI+S7r6K3rvdGV+TvEQjK",
	"1jHuCWa50MiTQ/Q9lg8XtV7LIWdr1Lm54KcSGZX+pyCHVf4y6Q+Oh4tT3wMMp6eRy77+Yiw4H6Ad3lU9",
	"T13Ixf4xhjOdyIOGR+SBkAERGVBuXCtltOxI3r55M8aqp20PlFuOBv5ZSguMHYJSIJezBsCJaSi0aSjq",
	"N363A8/UtDgvW8SobvScBa7pI4eOXj8YrC1zfj+fnN77MmynUTyX8u9NulMe7GrD/6j02HOuipFA7zEw",
	"HXUAhRbRDrkxdte/jDcEz1TvRaEDYEwYufkusNXwDC+rGiy3d32HenEKra49ld0p+f0580I2dxVSv8mX",
	"ZqG3Yzgu9EMqCj609XforHPB9hDc351vxbhsrqLuXcpn1f7/dH3tFvX8h9qlrPpQKvqhvv04zGvCuIRq",
	"zVuDB6mQAbg84HfYvumnTZdZOIz+UwXwZ4lnh2ZrGciXjDxvh1Cr4aHW5IPBqi4ofYv+APLRXexV0LnI",
	"nGu7uk2wmnE3tb529kPbYVzchpuvvVce/oPDH9wtj6Zgf3in/HZ5HHzB6CmVH0DA8blpiS+SBJtJgjcL",
	"fqwh/sRpsDMP+YryYIfrOQN2x3au5Vhp8G+OJ4LDNqgaIUZNfZ6ElsneSDoJU2ih4AlNVGdUL4PNJSq6",
	"45PArjnrEGSPyWMuKJ/WSBcuPlZjZ1NalBZyWjojFM6Sr4DiI6NbCfJwfzdtBVKUeXL6bHzJhdRm9SUq",
	"JFsCm5N0EiylzJg+aqJyCpQDo/+bZrHTWfmBcgYJ7gUjKCNhY0vFx3zOUztYajHgErrlbxImYSQmgist",
	"i0TPwFXNSXyU5vuclerfZERLmFCoDO0YEptRF8GmQiYYSWQIahnGHkHqLYJeBL2IcvmwMQ1TbOdyRbde",
	"+aHs7156ABSyGCRClGG2Ran2NB/4j2HQFKjumoYXwUV2sKhqai8+JoLgyQOSQkbZ6HVqtD1NpBo6qZnt",
	"ZUQqqJhgCgXTUT3IG6BVq8qzHKuD0pjFWwb80Qfz9KYX6wloYGLngx7Xqv5eW6sSwVO6m4Z1VaohTEGG",
	"PjeAqEqDWgQUH/lpMWAlDK5AmKqrixCdRXYKs6w0ORNAxgVnHnEVhv392mJwZ76cQqh+EbcY3lUQ5+HP",
	"UlY/92kNyb5KaO2Xe9tV1PcqC2icN8anbjNS6H2c7IHvMMpBqWchSXeLiR3lgwVR6O5KVjtknVYjR45r",
	"9toXVzWx5UEeZMZmfZDsRuvxsTODPy2DircFJwwXAu/EE0reaYbnEHrOsgy403ba20ObgOfwa1eyQTbE",
	"UYV9tVS+dY8thtm+3TjknsX4aP58jwePcodYKj62PxY9TW52g2Ax4DBaiHjmg1j0ENlK8axQRkioFjJy",
	"S9NHSQRjsBXlXTlmInlcA2/yMI69a4TTDfdpoFqGZcAOx/FActBtEZ2Bba8aM4ASuekGFsOXOXUadoXt",
	"OreoacD5U8vMHaVCRnVvMo1Qx1kEylTibNa+U8E+AB30KjNQMaFNS54i6EJilDI7ibBrewRmKkRr/mpF",
	"IthZo1myrTXJKI9NxuwUWLNRqPai1nyPj+XPC0/eDXMLRz2sXy440RYJx3bBO2GZoZY0qaG50DStxpLO",
	"tfjY/Voy1fhCMyNTsdISIavWq/9giroXht5aP/cqNC3qKF1qZGi4PcQZIVmk9kDEc9Qx1rOQjykTz96U",
	"WDmiWgivJXBFG1XYXzLLp3qqZ5Nn3cWEp0+n/wcAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
