//go:build go1.22

// Package distributionapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package distributionapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionCookieScopes sessionCookieContextKey = "sessionCookie.Scopes"
)

// Defines values for DistributionRecipientSource.
const (
	AreaGrant    DistributionRecipientSource = "area_grant"
	CompanyScope DistributionRecipientSource = "company_scope"
	UserGrant    DistributionRecipientSource = "user_grant"
)

// Valid indicates whether the value is a known member of the DistributionRecipientSource enum.
func (e DistributionRecipientSource) Valid() bool {
	switch e {
	case AreaGrant:
		return true
	case CompanyScope:
		return true
	case UserGrant:
		return true
	default:
		return false
	}
}

// CursorPage defines model for CursorPage.
type CursorPage struct {
	HasMore    bool    `json:"has_more"`
	NextCursor *string `json:"next_cursor"`
}

// DistributionAreaCoverage defines model for DistributionAreaCoverage.
type DistributionAreaCoverage struct {
	AreaCode string `json:"area_code"`
	AreaName string `json:"area_name"`

	// Total Active members of this area obligated via area_grant. The sum across areas need not equal total_targets (user_grant-only and company_scope users belong to no area; multi-area users count once per area). Empty array for company-scope documents.
	Total int `json:"total"`
}

// DistributionRecipient defines model for DistributionRecipient.
type DistributionRecipient struct {
	// AreaCode Granting area code; null unless source is area_grant.
	AreaCode *string `json:"area_code"`

	// AreaName Area label resolved via metaldocs.v_process_area_name (ADR-0041); null unless source is area_grant.
	AreaName *string `json:"area_name"`

	// Name User display name, resolved via the iam UserDisplayNameReader port (ADR-0029).
	Name string `json:"name"`

	// Source How the user became obligated. Distinct-by-user precedence user_grant > area_grant > company_scope (ADR-0040 / ADR-0042).
	Source DistributionRecipientSource `json:"source"`
	UserId string                      `json:"user_id"`
}

// DistributionRecipientSource How the user became obligated. Distinct-by-user precedence user_grant > area_grant > company_scope (ADR-0040 / ADR-0042).
type DistributionRecipientSource string

// DistributionRecipientsResponse defines model for DistributionRecipientsResponse.
type DistributionRecipientsResponse struct {
	Items []DistributionRecipient `json:"items"`
	Page  CursorPage              `json:"page"`
}

// DistributionSummaryResponse defines model for DistributionSummaryResponse.
type DistributionSummaryResponse struct {
	// TotalTargets Distinct count of users obligated by the controlled document — the coverage denominator. The numerator is out of M2 scope (ADR-0042).
	TotalTargets int `json:"total_targets"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	// Code Machine-readable per-field reason (ADR 0089 field namespace)
	Code string `json:"code"`

	// Field JSON pointer or dot path
	Field   string `json:"field"`
	Message string `json:"message"`
}

// Problem defines model for Problem.
type Problem struct {
	// Code Machine-readable code, `<family>.<name>` (RFC 9457 extension). Families are semantic, never module-named: auth 401 · conflict 409 · internal 500 · notfound 404 · permission 403 · precondition 412 · ratelimit 429 · request 400 · state 409 · validation 422. Full catalog: wiki/references/problem-codes.md
	Code     string        `json:"code"`
	Detail   *string       `json:"detail,omitempty"`
	Errors   *[]FieldError `json:"errors,omitempty"`
	Instance *string       `json:"instance,omitempty"`
	Status   int           `json:"status"`
	Title    string        `json:"title"`
	Type     *string       `json:"type,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Problem

// Forbidden defines model for Forbidden.
type Forbidden = Problem

// InternalServerError defines model for InternalServerError.
type InternalServerError = Problem

// NotFound defines model for NotFound.
type NotFound = Problem

// Unauthorized defines model for Unauthorized.
type Unauthorized = Problem

// sessionCookieContextKey is the context key for sessionCookie security scheme
type sessionCookieContextKey string

// ListDocumentDistributionRecipientsParams defines parameters for ListDocumentDistributionRecipients.
type ListDocumentDistributionRecipientsParams struct {
	// Cursor Opaque forward keyset cursor from a prior page's page.next_cursor.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Distribution coverage summary — total obligated audience for a controlled document
	// (GET /documents/{id}/distribution)
	GetDocumentDistribution(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// By-area obligated totals for a controlled document (denominator only)
	// (GET /documents/{id}/distribution/coverage)
	GetDocumentDistributionCoverage(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Obligated audience for a controlled document (denominator only)
	// (GET /documents/{id}/distribution/recipients)
	ListDocumentDistributionRecipients(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params ListDocumentDistributionRecipientsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetDocumentDistribution operation middleware
func (siw *ServerInterfaceWrapper) GetDocumentDistribution(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDocumentDistribution(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDocumentDistributionCoverage operation middleware
func (siw *ServerInterfaceWrapper) GetDocumentDistributionCoverage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDocumentDistributionCoverage(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDocumentDistributionRecipients operation middleware
func (siw *ServerInterfaceWrapper) ListDocumentDistributionRecipients(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDocumentDistributionRecipientsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDocumentDistributionRecipients(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/documents/{id}/distribution", wrapper.GetDocumentDistribution)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/documents/{id}/distribution/coverage", wrapper.GetDocumentDistributionCoverage)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/documents/{id}/distribution/recipients", wrapper.ListDocumentDistributionRecipients)

	return m
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type InternalServerErrorApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type GetDocumentDistributionRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetDocumentDistributionResponseObject interface {
	VisitGetDocumentDistributionResponse(w http.ResponseWriter) error
}

type GetDocumentDistribution200JSONResponse DistributionSummaryResponse

func (response GetDocumentDistribution200JSONResponse) VisitGetDocumentDistributionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDocumentDistribution401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetDocumentDistribution401ApplicationProblemPlusJSONResponse) VisitGetDocumentDistributionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetDocumentDistribution403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response GetDocumentDistribution403ApplicationProblemPlusJSONResponse) VisitGetDocumentDistributionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetDocumentDistribution404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetDocumentDistribution404ApplicationProblemPlusJSONResponse) VisitGetDocumentDistributionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetDocumentDistribution500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response GetDocumentDistribution500ApplicationProblemPlusJSONResponse) VisitGetDocumentDistributionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetDocumentDistributionCoverageRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetDocumentDistributionCoverageResponseObject interface {
	VisitGetDocumentDistributionCoverageResponse(w http.ResponseWriter) error
}

type GetDocumentDistributionCoverage200JSONResponse []DistributionAreaCoverage

func (response GetDocumentDistributionCoverage200JSONResponse) VisitGetDocumentDistributionCoverageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDocumentDistributionCoverage401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetDocumentDistributionCoverage401ApplicationProblemPlusJSONResponse) VisitGetDocumentDistributionCoverageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetDocumentDistributionCoverage403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response GetDocumentDistributionCoverage403ApplicationProblemPlusJSONResponse) VisitGetDocumentDistributionCoverageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetDocumentDistributionCoverage404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetDocumentDistributionCoverage404ApplicationProblemPlusJSONResponse) VisitGetDocumentDistributionCoverageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetDocumentDistributionCoverage500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response GetDocumentDistributionCoverage500ApplicationProblemPlusJSONResponse) VisitGetDocumentDistributionCoverageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListDocumentDistributionRecipientsRequestObject struct {
	Id     openapi_types.UUID `json:"id"`
	Params ListDocumentDistributionRecipientsParams
}

type ListDocumentDistributionRecipientsResponseObject interface {
	VisitListDocumentDistributionRecipientsResponse(w http.ResponseWriter) error
}

type ListDocumentDistributionRecipients200JSONResponse DistributionRecipientsResponse

func (response ListDocumentDistributionRecipients200JSONResponse) VisitListDocumentDistributionRecipientsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListDocumentDistributionRecipients400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response ListDocumentDistributionRecipients400ApplicationProblemPlusJSONResponse) VisitListDocumentDistributionRecipientsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListDocumentDistributionRecipients401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListDocumentDistributionRecipients401ApplicationProblemPlusJSONResponse) VisitListDocumentDistributionRecipientsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListDocumentDistributionRecipients403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response ListDocumentDistributionRecipients403ApplicationProblemPlusJSONResponse) VisitListDocumentDistributionRecipientsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListDocumentDistributionRecipients404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response ListDocumentDistributionRecipients404ApplicationProblemPlusJSONResponse) VisitListDocumentDistributionRecipientsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListDocumentDistributionRecipients500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response ListDocumentDistributionRecipients500ApplicationProblemPlusJSONResponse) VisitListDocumentDistributionRecipientsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Distribution coverage summary — total obligated audience for a controlled document
	// (GET /documents/{id}/distribution)
	GetDocumentDistribution(ctx context.Context, request GetDocumentDistributionRequestObject) (GetDocumentDistributionResponseObject, error)
	// By-area obligated totals for a controlled document (denominator only)
	// (GET /documents/{id}/distribution/coverage)
	GetDocumentDistributionCoverage(ctx context.Context, request GetDocumentDistributionCoverageRequestObject) (GetDocumentDistributionCoverageResponseObject, error)
	// Obligated audience for a controlled document (denominator only)
	// (GET /documents/{id}/distribution/recipients)
	ListDocumentDistributionRecipients(ctx context.Context, request ListDocumentDistributionRecipientsRequestObject) (ListDocumentDistributionRecipientsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetDocumentDistribution operation middleware
func (sh *strictHandler) GetDocumentDistribution(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetDocumentDistributionRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDocumentDistribution(ctx, request.(GetDocumentDistributionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDocumentDistribution")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDocumentDistributionResponseObject); ok {
		if err := validResponse.VisitGetDocumentDistributionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDocumentDistributionCoverage operation middleware
func (sh *strictHandler) GetDocumentDistributionCoverage(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetDocumentDistributionCoverageRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDocumentDistributionCoverage(ctx, request.(GetDocumentDistributionCoverageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDocumentDistributionCoverage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDocumentDistributionCoverageResponseObject); ok {
		if err := validResponse.VisitGetDocumentDistributionCoverageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListDocumentDistributionRecipients operation middleware
func (sh *strictHandler) ListDocumentDistributionRecipients(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params ListDocumentDistributionRecipientsParams) {
	var request ListDocumentDistributionRecipientsRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDocumentDistributionRecipients(ctx, request.(ListDocumentDistributionRecipientsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDocumentDistributionRecipients")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDocumentDistributionRecipientsResponseObject); ok {
		if err := validResponse.VisitListDocumentDistributionRecipientsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Drdcts21q9yhl9nPrslRdlx5vviXqVJ02a3TTxxepVkXYg8lFCDAAOAilXZM32Ivsve76P0SXYOAP5J",
	"lOR0djyzuze2gPODA+D8g+soU2WlJEprovN1pNFUShp0g29Y/gY/1mgsjTIlLUr3k1WV4BmzXMm00mom",
	"sPzqF6MkwUy2wJLRry80FtF59D9pt0TqoSa98FTR3d1dHOVoMs0rYhedR7QkNzxjCrhcMsFzFt3F0Qul",
	"ZzzPUT6kLJdYQoW65MYwRVK8lBa1ZOIS9RL1t1or/ZDy0ILAnQwKcgUG9ZLnSpNor5R9oWqZP+xdZbU2",
	"CiRTgJJW1Sx3B/WTZLVdKM1/xQeV6BVTwGpaimdOlLs4MHUq/YzE1RdsjjSqtKpQW+7VfcHMVam0g9hV",
	"hdF5NFNKIJO0IYk39srt1t24rIVgM4HRudU1xg2BsZrLuVtVkx5r2v27AXHcLfShpVOzXzCztM5zTjxm",
	"Ne3nqUb2TC1Rj8rLNLKrTOV9gZv1Yw+VrByHWmWZIMjw9J5mli8RSixnqA2oAuyCGyBeoGaCz5nFHJac",
	"uamruWbSTuDtAsHUJbBMK+OxDUjEHKSygB9rJsAteGWZnqM1cFQb1J48UVKsgMkc6KKZXF2ZTFUIhGFg",
	"hkLJOVgFUjnGX0NZC8sTJ5LHyVQtLSiZIdmqwzqewLdlZVfAtGYrKJRuuCeee66yuiSdmkRxVHLJy7qM",
	"zqftfZCNzVFvXWR35v0Tbs7z0H2+wYxXPJjBnsscXsp3dExczv01EM7XQOoHtRRoDBhV6wwh3FO4lCg+",
	"pKIbKrKhCLSUYDMUoNEosQzXXqJlIleZmSyvKq0yNOaqZQNHT5+/SabTs5Pjf5GE48L9ZFBDzk0l2AoI",
	"JR4KaRcInJVAeM892itW4htkOWqolLaNpKdPjkmOrXW9wNsrf68+Oe6keDDDjDbd2sUE6K65zGwyWyUO",
	"pdKYYY6kmp3Gw/t6On2EvbNoZoYW0JzmFFIIP0+duChJWYMyOgZRHHX8ozgaMOqpZbdDh87zEeewofEN",
	"YriMeKcJhDO7tw2YNyHX2DYGbrEc/tgXDcYt7K6Vw/kAGlfBje5j1gsQmyfhhQlsDm3zsi5Lple79zhw",
	"iNua1qhS492K4Ow6LzxbOVV0QVcJgXnr1OCP334PMB87IEepSi6ZVdq7a1mXqGlIRqlqt8CPpzBUPK9t",
	"n+Edh3saO6IXHEXepk3DExn3fj+ybMElJhpZTr6CfHxSEBugOKOkExem0/9/An6a9NFULMPjMdN2ONvL",
	"/OXy9SuolMutQGnIlYWK2cUYixKNCaq033b8WnEUrKWhGzuYJqX5s6dCaDH87BxJVrCSi5V3KhM/RYfi",
	"J36GozcvnsGTs8f/B3hjURqu5PEEXhARR+ejwWBJQSeLQeISNZQqrwUmxCU/pwRrAWfTE/jH30n/CsEz",
	"C2fTJzTmIUOGx9MpjaWyBaWlcDY9o3FIp7mScDZ95GY0Zkrm3Lq5k1Oa08yi4CW3cHbq2GpfiMCZ52os",
	"s9gs6YsET356OoEXFHoyZplQ83P4xK95qrFATX7YNClnQidmJmXuLNqS0NF59Lcj2ttts6nbZje3zTZu",
	"O/lv+4LfthLfBlFvnYy3nXDH799P3rHk1w/0Z5o8+fDl0VXz86vjL78YU7UcLeNiNIVDsqL7e8me5Y24",
	"Ri6NZTIbTxZpI7VboGQ33hc8fvKk5xnOpiO+IY4st2JH+ukm1lGhdMlsdB7VmkeHkmjPrhUnmNW2MZHE",
	"VJdwu7qkzXs7Mugu7ZlS13zEoC49GDIHB25M7X3sxevLt5CyiqfLk5SUIxVqziV5Rk6EnqAJj+dRmyFd",
	"hRW7fbGK/xVXvmrhslAjadfFS+CSZ5wJKu9+JF7PVWbgaHlCOS35ZwXMUkZtsHTGNteMauVMlfDy6eS9",
	"W88ffNTRP714GcXRErXxC51MppMp3YSqULKKR+fRo8l08sgbw8KdWMqqSqslE2mOAudOhwlwF4+D0jXP",
	"7zbhXM7Uzfak1zYiCT+vRmlH0dKMfon7YjsflydGsPtSGMvmNOn+u5mCGZsUSn9iOv/zXDQuOX5Klqhz",
	"ntk/z8fwuVRFsXUXWtUWd8yOXk4PlObIqPhjFhusOuc2xWVoDW1OpXhDmfRuSLr2//s3ux8rzdUnKRRr",
	"j5isLVswOcekYsZ8UnoAcoa4MaFq258psT8KFmnG5tJ1+NWTt8utkrZg3ANKM43OFBLX7bix+3CroA0h",
	"vu/EW+8Xx1+euzpsZw/iq5lRAu3BhZ3K9o9sN6apK9QG281sHliHTv57e7a3z83NBXVNekFqH1o42R1Y",
	"Olvw5S4WtVWGLZHiZ8ntAaRKI1niONbAR23CFphdu1zTHERI18Fp010Y69tTYySqHD/tATRdCz7TTK+u",
	"dp523itiKArM0XUrKCV1uv0yj86j79A+D2T9osdFD81KtEiZybu1D5Ehjw4B0tWSXVz3lX/X9+tSgtph",
	"buYEH+Jhk/p0Ot3TX/y8vuK+Am6k16iuKYKeTU928W0FTQftUEf06DBR1/J2FGeHKdoe8F0cPfYHs59g",
	"rJ/tEii/+1CINmfSFZQB7itNqvp6hSl5edfyKJQGNlag0rWyOWlINFC3D3F0k9BB/ZpkrGIzLrglGfpI",
	"Eyp5nIz7NDfNem3Tz1Hhtt36b6DKn90dGfSTt6qA/1IF/2aVbPS3nUKb3eoLR71+CigpVscPoNG6bZzt",
	"1OkfuBlV6q7n9hBqHW9WNa8r9rF27oDyZ7jGlUEL/jkECq1KYFBprjRUbI7/a9y/Se/NpC22PtaoV52g",
	"7YtKJ9yIMGOUrlIfELal7QkVs21pezLS9HqoEDTSKt1jpPcwht6D7n++Xb/+jID0cBZde8XYkcWFmihX",
	"2U1Sa7EXqcqLcXjBBeXKSatwIzgbBcAGtBIsw4USOepEVaG4r3amjD10cxhjHyfXUDNW15ndhbA7tW9q",
	"lWTBKVFe7ccy6VrTeOcxh3IwZZlzhPuRCqUzTDQKZOYA6gKZtjNkdj/afl6+A7ADWM92Fi+90yuQ2Vpj",
	"Ugin5m5ugUxQHd1VSGGGFLo5UM7KlOUllymlEj2ODqCRJeH9eMErsweUrsPb0l26bh+V7noErX1x7PO5",
	"rnhvRFUYGXdqJKvMQtlRmNXIyh5EK4HJDv4E64/r0Ozvxp2et+N0VovrrUkul9xu0XYb3w1Jx89wE4s2",
	"aDebI6OIW5sawmspVNZsoESredagS2V5EaLZ6JzTjoQJMQqspQO7d6xRhGCWbdvHIBXpWw2EpqebkqCq",
	"3p4vC5b00v4BjAyGiYbEshslVblyKjk+ma772tjCivBIsmt+B1mlVcHFNlkzf4AsgNMcC1YLm1gsK9EF",
	"kWZoNscDRx4eRLZwzMpYLNOZYPJ6C9jrygwnNxopm8A6bz3QBii0M8x+aLqWd4cxdvV89pKM9njuRTFs",
	"+Owj8QG8EorlvTh+mOJeqFU9E9ws7oE5yAAOI36exMMYtBfTBaSkUDppLqylkqyz8DBK1/6H797rLgiO",
	"wvtdaKuusdMsN2g1uPcq5Oqejfegdx8orTcum/SFkTuFKLz8RAQN+eCupyNKCv13Z65X8sdvv4PrUMfg",
	"+9Kx+8rJvcvXWqO0zTciaoaTrjQhNtF2EfUyJ97WfyrFsgyNgZJJNsf2yd/59Bicq4+hH91iaNrcXghX",
	"8PYiTG95zsqR1d+6E3eZtE1cAx98THXs/CWYwSbIAWzzuQxXAG3hapzoLPPfOTS+3bFt7guC9+7xb69y",
	"bAm6w6SX5WdKFnxe+/Uc55D7gMt9emwHmCO8m+IaWnWPoVH1GEINF444aPpw9d5andfet04IBe6QmnAQ",
	"+0/s/DpN5OlzDkQjjJ9t9+9B8AKzVSYwfIWXIzAhVLYp8OhryB7ZQ+Eo5wPtC840hqYnHUO/Ooh3KNS+",
	"Fcc2lY+2LZsPY0aalVsV4Ne9j2Qqpq8xj4efYTWS9avDbeEuUCdt6wb6mQ+4t1EnE2U/YGpdMJJEcGMh",
	"hX7iBCmUTF+77z2OJ3Ch1S+YkfyufTKn/Un3Yugf11ylSxttziPpLnlWy1x0H/k8Op7AJYrCfxjZ29cw",
	"7dvpEpybhZxnNN20hP3VJzkWXGIOGmvjvlJZE+87SML3bksmavcFk7Hk2CfwrK2oE78nzOHIrTCh8A6p",
	"X+6qW27ifeDxBL5h2TXKHPz3pBYuL5KTvlH42LC9j6eNofrX0Bjah9jYOZ5EFUVQyxGTsZpJ474AGbi/",
	"JsyNKKtWxnR66pPdgWejiRHCH/gSJXl9koT0gLuRCx/9tX3FFo214YLLZQK+f/v2AkKa36NVM4qATVPj",
	"7sPdPwMAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
