-- 0268_drop_legacy_template_family.sql  [HOLDING — NOT YET APPLIABLE]
-- DB-01 (P1) / DB-10 (P2): drop the legacy template family (public.templates,
-- public.template_versions) and the legacy public.signoffs table.
--
-- ============================================================================
-- WHY THIS FILE LIVES IN db/migrations/_pending/, NOT db/migrations/
-- ============================================================================
-- Files in db/migrations/ auto-apply at QA boot. This DROP is gated on a
-- runtime proof that has not been collected yet: docgenv2.LegacyTemplateReadCount()
-- (internal/platform/docgenv2/templates_reader.go) observed at zero across a
-- full QA run window, confirming FanoutTemplateReader's legacy fallback branch
-- took zero live traffic after the ARC-01 canonical-first flip (2026-07-01,
-- commit 4160018e). Moving this file into db/migrations/ is only safe once
-- BOTH of the following are true:
--   1. The runtime proof above is collected and recorded (zero legacy hits
--      across the QA run window — see LegacyTemplateReadCount()).
--   2. The docgenv2 legacy fallback reader code path is deleted in the SAME
--      change-set as the move (see "Deletion inventory" below) — this
--      migration and that code deletion land together, not the migration
--      alone. Landing the DROP first while FanoutTemplateReader.secondary
--      still references template_versions/templates would turn every
--      not-found-in-canonical lookup into a hard DB error instead of a clean
--      fallback-then-404, changing failure behavior for any residual caller.
--
-- ============================================================================
-- PREMISE VERIFICATION (CODE-PREP phase, 2026-07-03 — runtime truth, not
-- assumed from docs)
-- ============================================================================
-- public.templates / public.template_versions (DB-01):
--   - Canonical-first since ARC-01 (4160018e): docgenv2.FanoutTemplateReader
--     tries templates_template_version first, falls back to the legacy pair
--     ONLY on sql.ErrNoRows from the canonical reader (see
--     internal/platform/docgenv2/templates_reader.go:83-104).
--   - Legacy pair has exactly one live Go writer left after this change-set:
--     tests/integration/testdb/fixtures.go InsertDraftDocument — migrated in
--     this same change-set onto templates_template / templates_template_version
--     (mirrors TST-01 commit 1ac5e530). Zero legacy writers remain in
--     application or test code after this migration lands.
--   - Zero application-code readers of the legacy pair remain outside
--     internal/platform/docgenv2/template_reader.go's TemplateReader (the
--     fallback-only secondary reader), which is deleted alongside this
--     migration per the gating condition above.
--
-- public.signoffs (DB-10):
--   - Does NOT exist in the current canonical baseline
--     (db/baseline/0001_current_schema.sql) — grep-confirmed zero CREATE TABLE
--     for a bare "signoffs" table anywhere in the live schema. Only
--     public.approval_signoffs is live.
--   - internal/test/e2e_seed.go's reset handler previously carried
--     `DELETE FROM signoffs WHERE tenant_id = $1` in its per-tenant reset
--     statement list; every execution hit isUndefinedTable(execErr) and was
--     swallowed by the loop's `continue` — a permanent no-op since at least
--     the baseline this repo was cloned from. Removed from the reset list in
--     this same change-set (internal/test/e2e_seed.go).
--   - Zero runtime writers/readers anywhere in the tree (grep across
--     internal/ and tests/ for bare `signoffs` finds only: the removed reset
--     line, the approval_signoffs family, and the literal `/signoffs` HTTP
--     route path segment in the approval module's generated API — an
--     unrelated URL token, not a table reference).
--   - The DROP TABLE IF EXISTS below is therefore a safety-net no-op for this
--     table in every environment observed so far, kept only in case some
--     unaudited environment still carries a stray public.signoffs from very
--     old local state.
--
-- ============================================================================
-- INVENTORY: objects that die with these tables (verified against
-- db/baseline/0001_current_schema.sql — the canonical baseline per
-- scripts/export-schema-baseline.ps1)
-- ============================================================================
-- public.templates:
--   - PK: templates_pkey (id)
--   - UNIQUE: templates_tenant_key_unique (tenant_id, key)
--   - INDEX: idx_templates_tenant (tenant_id)
--   - RLS: ROW LEVEL SECURITY enabled + FORCE; POLICY tenant_isolation
--   - Outbound FK: fk_templates_current_published -> public.template_versions(id) DEFERRABLE
--   - Trigger coverage: none beyond RLS (no trg_require_cap_asserted on this
--     legacy table — confirmed no CASE branch for TG_TABLE_NAME = 'templates'
--     in enforce_capability_asserted())
--   - No inbound FK from any other table (grep-confirmed against baseline)
--
-- public.template_versions:
--   - PK: template_versions_pkey (id)
--   - UNIQUE: template_versions_template_num_unique (template_id, version_num)
--   - INDEX: idx_one_draft_per_template (template_id) WHERE status = 'draft' (partial unique)
--   - Outbound FK: template_versions_template_id_fkey -> public.templates(id) ON DELETE CASCADE
--   - Inbound FK: public.templates.current_published_version_id references this
--     table (see above) — DROP order below handles this (templates dropped
--     first via its own statement; CASCADE on template_versions handles the
--     reverse direction if templates is somehow still present).
--   - No RLS, no capability trigger, no other inbound FK.
--
-- public.signoffs: table does not exist in the current baseline (see premise
--   verification above) — no owned objects to inventory. DROP IF EXISTS is a
--   pure safety net.
--
-- No sequences are owned by either template_versions or templates (both use
-- gen_random_uuid() defaults, not identity/serial columns) — nothing to reclaim
-- beyond what CASCADE handles on the tables themselves.
--
-- Drop order: template_versions before templates would violate nothing (its
-- FK to templates is ON DELETE CASCADE, and templates' FK to it is
-- DEFERRABLE), but this migration drops templates first with CASCADE, which
-- also satisfies fk_templates_current_published automatically, then drops
-- template_versions (CASCADE handles the reverse
-- template_versions_template_id_fkey if templates somehow already gone).
-- signoffs has no FK relationship to either and is dropped last.
--
-- ============================================================================
-- DOCS TO UPDATE AT APPLY TIME (not touched by this holding file)
-- ============================================================================
--   - wiki/database/dictionary-index.md: remove rows for `template_versions`
--     (public, wiki/database/tables/template_versions.md) and `templates`
--     (public, wiki/database/tables/templates.md), or mark RETIRED with the
--     applying migration's version, matching the templates_audit_log
--     precedent (0262) at dictionary-index.md:72.
--   - wiki/database/tables/templates.md and
--     wiki/database/tables/template_versions.md: mark RETIRED or delete,
--     per documentation-governance.md convention for dropped tables.
--   - wiki/architecture/data-model.md: remove/update the legacy-family
--     description (grep-confirmed a live reference as of this writing).
--   - wiki/modules/templates-tech-debt.md and any other module tech-debt
--     tracker carrying a DB-01/DB-10 row: close out at apply time with the
--     applying migration's version and the collected LegacyTemplateReadCount
--     evidence.
--   - wiki/references/local-dev-credentials.md: grep-confirmed a reference to
--     the legacy family; verify it is not describing still-live seed data
--     before editing.
--
-- ============================================================================
-- DELETION INVENTORY: docgenv2 legacy fallback reader code (companion change,
-- NOT performed by this file — see gating condition above)
-- ============================================================================
-- When the runtime proof is collected and this migration is promoted out of
-- _pending/, delete in the SAME change-set:
--   - internal/platform/docgenv2/template_reader.go: the entire file (the
--     legacy TemplateReader type, ObjectReader interface use for the legacy
--     schema-key path, NewTemplateReader, GetPublishedVersion querying
--     template_versions/templates).
--   - internal/platform/docgenv2/templates_reader.go: FanoutTemplateReader
--     collapses to just TemplatesTemplateReader — remove the `secondary`
--     field, NewFanoutTemplateReader's second parameter, the sql.ErrNoRows
--     fallback branch in GetPublishedVersion (lines ~83-104), and the
--     legacyTemplateReadTotal atomic counter + LegacyTemplateReadCount()
--     (no longer meaningful once there is no fallback to count).
--   - apps/api/cmd/metaldocs-api/main.go:453-456: simplify docDeps.TplRead
--     wiring from `docgenv2.NewFanoutTemplateReader(NewTemplatesTemplateReader(...),
--     NewTemplateReader(...))` to a direct `docgenv2.NewTemplatesTemplateReader(deps.SQLDB)`
--     (drops the FanoutTemplateReader indirection entirely once there is
--     nothing to fan out to).
--   - internal/platform/docgenv2/template_reader_test.go: delete
--     TestTemplateReader_GetPublishedVersion_ReadsSchemaThroughGuardedReader
--     and TestTemplateReader_GetPublishedVersion_AllowsSystemTemplateTenant
--     (both exercise the deleted TemplateReader type); keep
--     TestTemplatesTemplateReader_GetPublishedVersion_AllowsSystemTemplateTenant
--     (exercises the surviving canonical-only reader) — likely relocate it
--     into templates_reader_test.go once fanout_template_reader_test.go's
--     dual-mock harness is also gone.
--   - internal/platform/docgenv2/fanout_template_reader_test.go: delete
--     entirely (newFanoutUnderTest, canonicalQuery/legacyQuery consts, and
--     all four TestFanoutTemplateReader_* cases) — the type under test no
--     longer exists.
--   - Any remaining LegacyTemplateReadCount() call sites (tests only as of
--     this writing) fall away with the counter's removal.
--
-- ============================================================================
-- SAFETY
-- ============================================================================
-- IF EXISTS on every DROP makes this idempotent and safe to re-run, and safe
-- to no-op in any environment that already lacks one or more of these tables.
-- CASCADE reclaims each table's owned constraints/indexes/policies with it.

BEGIN;

-- DB-01: legacy template family. templates first (CASCADE also satisfies its
-- own outbound FK to template_versions); template_versions second (CASCADE
-- handles template_versions_template_id_fkey if templates is already gone in
-- some partially-migrated environment).
DROP TABLE IF EXISTS public.templates CASCADE;
DROP TABLE IF EXISTS public.template_versions CASCADE;

-- DB-10: legacy signoffs — safety-net no-op in every environment observed so
-- far (table does not exist in the current canonical baseline).
DROP TABLE IF EXISTS public.signoffs CASCADE;

INSERT INTO public.schema_migrations (version, description)
VALUES ('0268', 'DB-01/DB-10: drop legacy template family (public.templates, public.template_versions — canonical templates_template/templates_template_version is the live path since ARC-01 4160018e; docgenv2 legacy fallback reader deleted in the same change-set as this migration''s promotion out of _pending/) and legacy public.signoffs (safety-net no-op; table absent from canonical baseline, confirmed zero runtime writers/readers). GATED: apply only after docgenv2.LegacyTemplateReadCount() is observed at zero across a full QA run window.')
ON CONFLICT (version) DO NOTHING;

COMMIT;
