package main

import (
	"fmt"
	"sort"
	"strings"
)

// EvidenceKind classifies how a REQ was covered, per contract §2.1(a)/(b)/(c).
type EvidenceKind string

const (
	EvidenceTest   EvidenceKind = "test"
	EvidenceCommit EvidenceKind = "commit"
	EvidenceDoc    EvidenceKind = "doc-annotation"
	EvidenceNone   EvidenceKind = "none"
)

// ReportRow is one line of the coverage report.
type ReportRow struct {
	ID       string
	Class    Class
	Evidence EvidenceKind
	Pointer  string
}

// Report is the full coverage join across every extracted REQ ID.
type Report struct {
	Rows []ReportRow
}

// UncoveredMusts returns the sorted IDs of every MUST-classified REQ with
// EvidenceNone — the gate-failing set (contract §2.1/§2.2).
func (r Report) UncoveredMusts() []string {
	var out []string
	for _, row := range r.Rows {
		if row.Class == ClassMust && row.Evidence == EvidenceNone {
			out = append(out, row.ID)
		}
	}
	sort.Strings(out)
	return out
}

// BuildReport joins extracted REQs against the three legitimate evidence
// sources, in priority order test > commit-map > doc-annotation (the order is
// evidence-kind labeling only — any one source is sufficient for coverage,
// per contract §2.1 "≥1 of"). testCitations and mapEntries may be nil/empty.
func BuildReport(reqs []Req, testCitations map[string][]string, mapEntries []MapEntry) Report {
	mapByReq := map[string]MapEntry{}
	for _, e := range mapEntries {
		mapByReq[e.Req] = e
	}

	rep := Report{}
	for _, req := range reqs {
		row := ReportRow{ID: req.ID, Class: req.Class, Evidence: EvidenceNone}

		if files, ok := testCitations[req.ID]; ok && len(files) > 0 {
			row.Evidence = EvidenceTest
			row.Pointer = strings.Join(files, "; ")
		} else if e, ok := mapByReq[req.ID]; ok {
			row.Evidence = EvidenceCommit
			row.Pointer = fmt.Sprintf("commit %s — %s", e.Ref, e.Note)
		} else if req.Annotation != "" {
			row.Evidence = EvidenceDoc
			row.Pointer = req.Annotation
		}

		rep.Rows = append(rep.Rows, row)
	}
	return rep
}

// RenderReport renders the report as the committed markdown artifact
// (wiki/architecture/req-traceability.md). Deterministic byte-for-byte output
// for the same input is required by the anti-rot check in gate.go, so rows
// are emitted in a fixed (extraction) order and every field is normalized.
func RenderReport(rep Report) string {
	var b strings.Builder
	b.WriteString("# REQ Traceability Report (generated)\n\n")
	b.WriteString("> Generated by `go run ./scripts/req-trace -write`. Do not hand-edit — the gate\n")
	b.WriteString("> detects drift between this file and a fresh regeneration and fails as stale.\n")
	b.WriteString("> Local command: `go run ./scripts/req-trace`\n\n")

	must := 0
	should := 0
	may := 0
	uncoveredMust := 0
	for _, row := range rep.Rows {
		switch row.Class {
		case ClassMust:
			must++
			if row.Evidence == EvidenceNone {
				uncoveredMust++
			}
		case ClassShould:
			should++
		case ClassMay:
			may++
		}
	}
	fmt.Fprintf(&b, "**Totals:** %d REQ IDs (%d MUST, %d SHOULD, %d MAY). Uncovered MUST: %d.\n\n",
		len(rep.Rows), must, should, may, uncoveredMust)

	b.WriteString("| REQ ID | Class | Evidence | Pointer |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, row := range rep.Rows {
		pointer := row.Pointer
		if pointer == "" {
			pointer = "—"
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", row.ID, row.Class, row.Evidence, escapePipe(pointer))
	}

	return b.String()
}

func escapePipe(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
