//go:build go1.22

// Package auditapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package auditapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	SessionCookieScopes sessionCookieContextKey = "sessionCookie.Scopes"
)

// Defines values for AuditExportFormat.
const (
	Csv   AuditExportFormat = "csv"
	Jsonl AuditExportFormat = "jsonl"
)

// Valid indicates whether the value is a known member of the AuditExportFormat enum.
func (e AuditExportFormat) Valid() bool {
	switch e {
	case Csv:
		return true
	case Jsonl:
		return true
	default:
		return false
	}
}

// AuditEventItem defines model for AuditEventItem.
type AuditEventItem struct {
	Action       string                 `json:"action"`
	ActorId      string                 `json:"actor_id"`
	Id           string                 `json:"id"`
	OccurredAt   time.Time              `json:"occurred_at"`
	Payload      map[string]interface{} `json:"payload"`
	ResourceId   string                 `json:"resource_id"`
	ResourceType string                 `json:"resource_type"`
	TraceId      string                 `json:"trace_id"`
}

// AuditExportFormat defines model for AuditExportFormat.
type AuditExportFormat string

// AuditExportRequest defines model for AuditExportRequest.
type AuditExportRequest struct {
	// Filter Multi-axis audit filter (mirrors GET /audit/events query params).
	Filter AuditFilter       `json:"filter"`
	Format AuditExportFormat `json:"format"`
}

// AuditExportResponse defines model for AuditExportResponse.
type AuditExportResponse struct {
	ExpiresAt time.Time `json:"expires_at"`
	ExportId  string    `json:"export_id"`
	SignedUrl string    `json:"signed_url"`
	Status    string    `json:"status"`
}

// AuditExportStatusResponse defines model for AuditExportStatusResponse.
type AuditExportStatusResponse struct {
	Error     *string    `json:"error,omitempty"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	ExportId  string     `json:"export_id"`
	SignedUrl string     `json:"signed_url"`
	Status    string     `json:"status"`
}

// AuditFilter Multi-axis audit filter (mirrors GET /audit/events query params).
type AuditFilter struct {
	Action         *string    `json:"action,omitempty"`
	ActorId        *string    `json:"actor_id,omitempty"`
	OccurredAfter  *time.Time `json:"occurred_after,omitempty"`
	OccurredBefore *time.Time `json:"occurred_before,omitempty"`
	Q              *string    `json:"q,omitempty"`
	ResourceId     *string    `json:"resource_id,omitempty"`
	ResourceType   *string    `json:"resource_type,omitempty"`
}

// CursorPage defines model for CursorPage.
type CursorPage struct {
	HasMore    bool    `json:"has_more"`
	NextCursor *string `json:"next_cursor"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	// Code Machine-readable per-field reason (ADR 0089 field namespace)
	Code string `json:"code"`

	// Field JSON pointer or dot path
	Field   string `json:"field"`
	Message string `json:"message"`
}

// ListAuditEventsResponse defines model for ListAuditEventsResponse.
type ListAuditEventsResponse struct {
	Items []AuditEventItem `json:"items"`
	Page  CursorPage       `json:"page"`
	Total *int             `json:"total,omitempty"`
}

// Problem defines model for Problem.
type Problem struct {
	// Code Machine-readable code, `<family>.<name>` (RFC 9457 extension). Families are semantic, never module-named: auth 401 · conflict 409 · internal 500 · notfound 404 · permission 403 · precondition 412 · ratelimit 429 · request 400 · state 409 · validation 422. Full catalog: wiki/references/problem-codes.md
	Code     string        `json:"code"`
	Detail   *string       `json:"detail,omitempty"`
	Errors   *[]FieldError `json:"errors,omitempty"`
	Instance *string       `json:"instance,omitempty"`
	Status   int           `json:"status"`
	Title    string        `json:"title"`
	Type     *string       `json:"type,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Problem

// Forbidden defines model for Forbidden.
type Forbidden = Problem

// InternalServerError defines model for InternalServerError.
type InternalServerError = Problem

// NotFound defines model for NotFound.
type NotFound = Problem

// Unauthorized defines model for Unauthorized.
type Unauthorized = Problem

// sessionCookieContextKey is the context key for sessionCookie security scheme
type sessionCookieContextKey string

// ListAuditEventsParams defines parameters for ListAuditEvents.
type ListAuditEventsParams struct {
	ActorId        *string    `form:"actor_id,omitempty" json:"actor_id,omitempty"`
	Action         *string    `form:"action,omitempty" json:"action,omitempty"`
	ResourceType   *string    `form:"resource_type,omitempty" json:"resource_type,omitempty"`
	ResourceId     *string    `form:"resource_id,omitempty" json:"resource_id,omitempty"`
	OccurredAfter  *time.Time `form:"occurred_after,omitempty" json:"occurred_after,omitempty"`
	OccurredBefore *time.Time `form:"occurred_before,omitempty" json:"occurred_before,omitempty"`

	// Q Free-text search on action / payload summary
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// DownloadAuditExportParams defines parameters for DownloadAuditExport.
type DownloadAuditExportParams struct {
	Token string `form:"token" json:"token"`
}

// ExportAuditEventsJSONRequestBody defines body for ExportAuditEvents for application/json ContentType.
type ExportAuditEventsJSONRequestBody = AuditExportRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Lista eventos de auditoria append-only (multi-axis filter, cursor-paginated)
	// (GET /audit/events)
	ListAuditEvents(w http.ResponseWriter, r *http.Request, params ListAuditEventsParams)
	// Export filtered audit events as CSV or JSONL (signed URL, async if large)
	// (POST /audit/events/export)
	ExportAuditEvents(w http.ResponseWriter, r *http.Request)
	// Read the status of an audit export job
	// (GET /audit/events/export/{export_id})
	GetAuditExportStatus(w http.ResponseWriter, r *http.Request, exportId string)
	// Download the rendered audit export payload via a signed token
	// (GET /audit/events/export/{export_id}/download)
	DownloadAuditExport(w http.ResponseWriter, r *http.Request, exportId string, params DownloadAuditExportParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAuditEvents operation middleware
func (siw *ServerInterfaceWrapper) ListAuditEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAuditEventsParams

	// ------------- Optional query parameter "actor_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "actor_id", r.URL.Query(), &params.ActorId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "actor_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "actor_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "action" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "action", r.URL.Query(), &params.Action, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "action"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "resource_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "resource_type", r.URL.Query(), &params.ResourceType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "resource_type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resource_type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "resource_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "resource_id", r.URL.Query(), &params.ResourceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "resource_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resource_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "occurred_after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "occurred_after", r.URL.Query(), &params.OccurredAfter, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "occurred_after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "occurred_after", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "occurred_before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "occurred_before", r.URL.Query(), &params.OccurredBefore, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "occurred_before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "occurred_before", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAuditEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportAuditEvents operation middleware
func (siw *ServerInterfaceWrapper) ExportAuditEvents(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportAuditEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuditExportStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAuditExportStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "export_id" -------------
	var exportId string

	err = runtime.BindStyledParameterWithOptions("simple", "export_id", r.PathValue("export_id"), &exportId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "export_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuditExportStatus(w, r, exportId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadAuditExport operation middleware
func (siw *ServerInterfaceWrapper) DownloadAuditExport(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "export_id" -------------
	var exportId string

	err = runtime.BindStyledParameterWithOptions("simple", "export_id", r.PathValue("export_id"), &exportId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "export_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DownloadAuditExportParams

	// ------------- Required query parameter "token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "token", r.URL.Query(), &params.Token, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadAuditExport(w, r, exportId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/audit/events", wrapper.ListAuditEvents)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/audit/events/export", wrapper.ExportAuditEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/audit/events/export/{export_id}", wrapper.GetAuditExportStatus)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/audit/events/export/{export_id}/download", wrapper.DownloadAuditExport)

	return m
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type InternalServerErrorApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type ListAuditEventsRequestObject struct {
	Params ListAuditEventsParams
}

type ListAuditEventsResponseObject interface {
	VisitListAuditEventsResponse(w http.ResponseWriter) error
}

type ListAuditEvents200JSONResponse ListAuditEventsResponse

func (response ListAuditEvents200JSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuditEvents400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response ListAuditEvents400ApplicationProblemPlusJSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuditEvents401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListAuditEvents401ApplicationProblemPlusJSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuditEvents403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response ListAuditEvents403ApplicationProblemPlusJSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuditEvents500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response ListAuditEvents500ApplicationProblemPlusJSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ExportAuditEventsRequestObject struct {
	Body *ExportAuditEventsJSONRequestBody
}

type ExportAuditEventsResponseObject interface {
	VisitExportAuditEventsResponse(w http.ResponseWriter) error
}

type ExportAuditEvents202JSONResponse AuditExportResponse

func (response ExportAuditEvents202JSONResponse) VisitExportAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type ExportAuditEvents400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response ExportAuditEvents400ApplicationProblemPlusJSONResponse) VisitExportAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ExportAuditEvents401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ExportAuditEvents401ApplicationProblemPlusJSONResponse) VisitExportAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ExportAuditEvents403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response ExportAuditEvents403ApplicationProblemPlusJSONResponse) VisitExportAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ExportAuditEvents500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response ExportAuditEvents500ApplicationProblemPlusJSONResponse) VisitExportAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuditExportStatusRequestObject struct {
	ExportId string `json:"export_id"`
}

type GetAuditExportStatusResponseObject interface {
	VisitGetAuditExportStatusResponse(w http.ResponseWriter) error
}

type GetAuditExportStatus200JSONResponse AuditExportStatusResponse

func (response GetAuditExportStatus200JSONResponse) VisitGetAuditExportStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuditExportStatus401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetAuditExportStatus401ApplicationProblemPlusJSONResponse) VisitGetAuditExportStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuditExportStatus403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response GetAuditExportStatus403ApplicationProblemPlusJSONResponse) VisitGetAuditExportStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuditExportStatus404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetAuditExportStatus404ApplicationProblemPlusJSONResponse) VisitGetAuditExportStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuditExportStatus500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response GetAuditExportStatus500ApplicationProblemPlusJSONResponse) VisitGetAuditExportStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadAuditExportRequestObject struct {
	ExportId string `json:"export_id"`
	Params   DownloadAuditExportParams
}

type DownloadAuditExportResponseObject interface {
	VisitDownloadAuditExportResponse(w http.ResponseWriter) error
}

type DownloadAuditExport200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response DownloadAuditExport200ApplicationoctetStreamResponse) VisitDownloadAuditExportResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type DownloadAuditExport400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response DownloadAuditExport400ApplicationProblemPlusJSONResponse) VisitDownloadAuditExportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadAuditExport401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response DownloadAuditExport401ApplicationProblemPlusJSONResponse) VisitDownloadAuditExportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadAuditExport403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response DownloadAuditExport403ApplicationProblemPlusJSONResponse) VisitDownloadAuditExportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadAuditExport404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response DownloadAuditExport404ApplicationProblemPlusJSONResponse) VisitDownloadAuditExportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadAuditExport500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response DownloadAuditExport500ApplicationProblemPlusJSONResponse) VisitDownloadAuditExportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Lista eventos de auditoria append-only (multi-axis filter, cursor-paginated)
	// (GET /audit/events)
	ListAuditEvents(ctx context.Context, request ListAuditEventsRequestObject) (ListAuditEventsResponseObject, error)
	// Export filtered audit events as CSV or JSONL (signed URL, async if large)
	// (POST /audit/events/export)
	ExportAuditEvents(ctx context.Context, request ExportAuditEventsRequestObject) (ExportAuditEventsResponseObject, error)
	// Read the status of an audit export job
	// (GET /audit/events/export/{export_id})
	GetAuditExportStatus(ctx context.Context, request GetAuditExportStatusRequestObject) (GetAuditExportStatusResponseObject, error)
	// Download the rendered audit export payload via a signed token
	// (GET /audit/events/export/{export_id}/download)
	DownloadAuditExport(ctx context.Context, request DownloadAuditExportRequestObject) (DownloadAuditExportResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAuditEvents operation middleware
func (sh *strictHandler) ListAuditEvents(w http.ResponseWriter, r *http.Request, params ListAuditEventsParams) {
	var request ListAuditEventsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAuditEvents(ctx, request.(ListAuditEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAuditEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAuditEventsResponseObject); ok {
		if err := validResponse.VisitListAuditEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExportAuditEvents operation middleware
func (sh *strictHandler) ExportAuditEvents(w http.ResponseWriter, r *http.Request) {
	var request ExportAuditEventsRequestObject

	var body ExportAuditEventsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExportAuditEvents(ctx, request.(ExportAuditEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExportAuditEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExportAuditEventsResponseObject); ok {
		if err := validResponse.VisitExportAuditEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuditExportStatus operation middleware
func (sh *strictHandler) GetAuditExportStatus(w http.ResponseWriter, r *http.Request, exportId string) {
	var request GetAuditExportStatusRequestObject

	request.ExportId = exportId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuditExportStatus(ctx, request.(GetAuditExportStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuditExportStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuditExportStatusResponseObject); ok {
		if err := validResponse.VisitGetAuditExportStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DownloadAuditExport operation middleware
func (sh *strictHandler) DownloadAuditExport(w http.ResponseWriter, r *http.Request, exportId string, params DownloadAuditExportParams) {
	var request DownloadAuditExportRequestObject

	request.ExportId = exportId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadAuditExport(ctx, request.(DownloadAuditExportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadAuditExport")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DownloadAuditExportResponseObject); ok {
		if err := validResponse.VisitDownloadAuditExportResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Hrdchu5cvCrdM13LqRzZjiUra0vVq689urEyZ5dlbUnN7uODjjTQ2KFAcYAhhaXYlUeIu+S+zxKniTV",
	"AOaPnCFl1dpJJTcSgf5Bo9HoP8w2ylRZKYnSmuhqG2k0lZIG3eBblr/HjzUaS6NMSYvS/WRVJXjGLFcy",
	"rbRaCCz/9KtRkmAmW2HJ6NcfNBbRVfT/0m6J1ENNeuOpot1uF0c5mkzzithFVxEtyQ3PmAIu10zwnEW7",
	"OLpWesHzHOXXlOUWS6hQl9wYpkiKd9Kilkzcol6j/k5rpb+mPLQgcCeDglyBQb3mudIk2g/KXqta5l/3",
	"rLJaGwWSKUBJq2qWO0X9VbLarpTmv+FXlegHpoDVtBTPnCi7ODB1Jv26zrn9bo3SvrNY0kylVYXacm/y",
	"LPN8tpHdVBhdRcZqLpe0I5ZZpe94PgqcmFZZVmuN+R1zOy+ULulXlDOLieUlRvEhUcU2QjHHkOU5J4GY",
	"uOmJaXWNLZ1a/IqZJTqNRtU6wykZW7iHjGBYzabIHf3Hmms6zp9pv8Pd9fQTN1rcX3IoYrfR3sIfRvbl",
	"z+yhUtpeBwVuI5R1SYJkZh3FEZmP6BF3W+oR93zZ8NALLizqU0bnOF171F3cnuUTiAay72sy8IkbKU5o",
	"4H1w0Ie7wIeKazSfZWroeE4ZjOFLifldrcWAY635GC9jma3NadPp1mxpBkvF/Z2c0Matoz+ik8ZBj+38",
	"f4W2JhV03Rr10EH+pRaWJ+yBG2CEB97u4KzkpCwDf/7uJ0gdKEVylAY+1qg3UDHNSnM+o4v7u/jMzn0U",
	"QdKnHUNLt8BCaXw64cfjbvGZbnM3cgJvKCrqG7YcsckVM3dlkDsQLpQSyCRRSnywdy6oOo3IWgi2ELjn",
	"9CeMpU8cdwuN2cg1R5G3+ctQwkzlOGI4LFtxiYlGlpNIlBglBbEBjcwoCWev376H+fzvXoGflqxEU7EM",
	"z8dOw+EcLvOPtz/+AJVySQ4oDbmyUDG7GmNRojFBx8cV49eK/c46ujHFfM+N7bKEI76FWyyHP04Hgjbx",
	"6IyGac02Puz7nRzj0rMr4qAsc86m5JKXFA/nLVvS35Ii1X7gdsKG1cb23+RWz7UKQovhb7/U8/nLrGAl",
	"Fxv3G2d+iozCT/wNzt5fv4FXl9/8f8AHi9JwJc9ncE1EHA0wjWCwZJTLxSBxjRpKldcCE+KSX1Gmt4LL",
	"+QX8x79DpmQheGbhcv6Kxjyk6vDNfE5jqWxB+TFczi9pHPJ6riRczl+6GY2Zkj7jgsuLFzSnmUXBS27h",
	"8oVjq30WAZeeK/lkbJb01Yonf/FiBte1EJAxy4RaXsEnfs9TjQVqlBmaJvdNSGNmVvqMyJLQ0VX0L2e0",
	"t8dmU4/Nbh6bbTx28j/2BX9sJX4Moj46GR874c5/+WX2M0t++0B/5smrD388u2t+/un8j38Yu2o5WsbF",
	"eCh1cePJN6HneUZuAZfGMpmN56dd0CzZg7f4b169ijv7v5yP3IA4styKiYw3+PTj4XrvDnl2vXjsrsbh",
	"ZSKJqUDidnNLm/f3yKA7tDdK3fORC3XrwZA5OHBjasxhsYGbH28pMFc8XV+kZBypUEsuKR5zIvQEURzR",
	"3YiuohItE7nKzF1YsdsXq/g/4caXT1wW6lCK1zfvgEuecSaozvwL8XqrMgNn64vzGXxnMlUpYLZmgq6o",
	"u2xLzahoz1QJ717PfnHrecVHHf3rm3dRHK1RG7/QxWw+m7uoXqFkFY+uopez+eylvwwrp7GUVZVWaybS",
	"HAUunQ0TYBePg9Itz3f7cC4X6uFw0lsbkYSfd6O0o2hpRr/EU7Gdj8sTI9hTKYxlS5p0/91MwYxNCqU/",
	"MZ0/n4vGNcdPyRp1zjP7fD6Uh6qiODgLrWqLE7Ojh9MDpTlSQrlmFhusXi5K5rBEl7NTbHLn/S6PrvbD",
	"tjMfzUq0SK7p562/Iy6T7a5Ir2TtGg8Hd3+S1t+pz6bcL4qfz+B5ku/l3X0OT8mjT7INaflz+A6d0LVG",
	"TCw+WDDIdLYCJcGrHVIIzQMwdVkyJ8eYUB+fo6A2g/5sShd3B4RtoLqg0NQGqouRRO1DPGy/vpjPj3TO",
	"Pq9jNpXVjnTQCJVBjuBunDL0011BpbnrxF56ucaWa+VPe71jR3JxmmTQMnREL08TdW3hXRx98xTJxlq4",
	"LlQHQ2o0MLZ9YFVFPlxJsYGzsiulfREdgzedpGJLLpnF3FU+bEkuKHJcKE14SGijvyUZq9iCC25pUQed",
	"URrtpBl4vdR3AVxOrsyI9/PdkKH/C9nftyrf/G5mNNJN2w2zIypTdweG/OLLSDBtxB7D5SNsiTJnOYMz",
	"ZgyXLGfn/yes2KsgWCbmodsTWjrMwJvbf6b6murt7+HMt5Tgr++/j4GZjcyAFyCYXuLvasLptm1o7SZj",
	"+Z/RHvT4JgJ66AwE99tvlg1N8pgv/5J+d7pXOfba5DBCVp0zwNaIv6L1Xc4vT1O0b02/n7m+R5aDXSH4",
	"qgpUAUw2RutN+Ve1+FK2mObqk2xeXUaN8m1A6J3oF7TJifzCqnuUX9C4VWbRJsZqZOXQyNsMbsGlT7f2",
	"Vzow5ze0Rp0rcCRcDU0azpwDqr0D+h/ukv+7LkVjdO5iaJR535P7S9HkwWvKTiC48cZOnntX7CrNVkwu",
	"MamYMZ9UV2y2fYe9CVXb/kyJ/VFoQJixuXQbfvUKb/eQrITAPMlVVpeh8psCpZlGZ7+JM+sHewy3CsVv",
	"aGdO4m2Pi+NrVVepYjt7El8tjBJoTy7sKvS+yqYxTV2hNthuZl9hHTo51sPZ3j73Nxeq86TXkzuGFjQ7",
	"gaWzFV9PsaitMmyNdE2ogDqOVGkkMx/HGrRk9mErzO7d04I5iZBuQ4+KzsJY/14zRqLKcW0PoOlW8IVm",
	"enM3qe2ckydd1OEt7QRGmqk1av9icApVY8YrPi1kXvsAMMErBMtcZQ+Jf9ycRqryYhxecEF2lLQBZQRn",
	"73LsQSvBMlwpkaNOVBX6fNWkOnvo5jTGMU6ut26srjM7hTBt9s09TlacjGhzHMukW03jSTUHV5myzMX/",
	"40iF0hkmGgUycwJ1hUzbBTJ7HO04L98MnADWi8mL3dNegczWGpNCuMDl5lbIBMWYznuEGQpYjUI5K1OW",
	"l1ymdC96HB1AI0tKLBeozYpX5ggo3dYGtcsItwS7ozCx6xG0gZNjn899xXsj8lAoM0yNZJVZKTsKa7Ks",
	"BqKVwGSCP8H649p0d9+POztvx+miFvcHk1yuuT2g7TY+DUnHdbiPRRu0+4nDKOLBpobwWgqVNRso0Wqe",
	"NehSWV6ErHV0zllHwoQYBdbSgTNVt0F7iBCuJWvE9w3Ig+DaPO+kJKiqD+fLgiV7rrqF0YVhoiGx7EFJ",
	"VW6cSY5Pptu+NbawIryXTs1PkFVaFVwckjXzJ8gCOM2xYLWwicWyEl0QaYZmfzxw5OFt9ADHbIzFMl0I",
	"Ju8PgL2MZTi5l2TsA10OPAoKod4ch6ZbuTuNMZUPHSUZzX+eRDFMho6R+ABeUbHQi+OnKZ6EWtULwc3q",
	"CZiDDOA04udJPIxBRzFdQEoKpZPmwFoqybobHkbp1v/wD3m6C4Kj8KZb6xCoFDODQWvBvQdi1z7Yexr+",
	"+QOV78ZVh76/4LQQhUfgiKChwpt6RaZSy38L655N/vNf/w1c9RaDr9liYNJXl+7xRtqEvC9UWi1w1nvs",
	"qu0qOnygeZcTb7txTFiWoTFQMsmWSE7SreZ8egzO1cfQj24xNCWgF4JcHPQiTG95zsqR1X9yGvfVcOI6",
	"O+BjqmPnD8EMNkEO4JDPbTgCaBs+xonOMhcfoPHtjm1zXhC8d49/e5RjS9AZJl0V575W4cvar+c4h9wH",
	"XO7TYzvAHOH9NsQkaM09hsbUYwiNyKDiYOnD1XtrdV772DohFDglNeEgducX1mkiT59zIBph/OawtgXB",
	"C8w2mUDHjyINMCFUti/waKfgiOyhESSXA+sLzjSGpl6LoV8dxBMGdWzFsU31qzJosgKnRbqAaiH4ktnQ",
	"36EUEc5ylKrkklmlQUmx+XuQdUlGqjRUTN9jHsPrt++T+fzyxXlfsn4xeSjcDeqkrQqhn/mA+0zCyUTZ",
	"D5haF4wkEdxYSKGfOEEKJdP37tOv8xncaPUrZiR/oVUJS9qfdB8PhDeHQmm30UYfSXfIi1rmAt0HhLSX",
	"l+czuEVRJCZTVd8PDdO+SZfg3Czk3L0VM+0t1R99kmPBJeagsTbug7Ut8d5B4j9KgzUTNYIr+cixz+BN",
	"2ypL/J4whzO3wozCO6R+ubtuuZn3gecz+JZl9yhzd3bALNzeJBezvXbu2D5eNxfVfxgRQ/tNRuwcT6KK",
	"IpjlyJWxmknjPgYbuL8mzI0Yq1bGdHbqk92BZ6OJEcLv+RoleX2ShOyAu5ELH/21fcU2wuDHxuUyAf/w",
	"0083ENL8Hq1aUARsupW7D7v/CgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
