// Command dump-error-codes scans the backend source tree for RFC 9457 Problem
// codes emitted by HTTP handlers and writes them as a sorted JSON array.
//
// The output feeds the frontend coverage test
// (frontend/apps/web/src/lib/api/errorMessages.coverage.test.ts), which fails
// the build if a backend code lacks a Portuguese mapping.
//
// Run: go run ./scripts/dump-error-codes.go
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var (
	// const Foo problem.Code = "value" (callers) or Code = "value" (problem pkg).
	// Captures the identifier so we can drop FieldCode... field-level codes.
	reConstDecl = regexp.MustCompile(`(\w+)\s+(?:problem\.)?Code\s+=\s*"([^"]+)"`)
	// problem.New(status, "code", ...)
	reProblemNewLiteral = regexp.MustCompile(`problem\.New\([^,]+,\s*"([^"]+)"`)
	// httpresponse.WriteError(w, status, "code", ...)
	reWriteErrorLiteral = regexp.MustCompile(`httpresponse\.WriteError\([^,]+,\s*[^,]+,\s*"([^"]+)"`)
	// mapErr-style: return http.StatusXxx, "code"
	reReturnStatusCode = regexp.MustCompile(`return\s+http\.Status[A-Za-z]+,\s*"([^"]+)"`)
	// problem.Write(w, problem.New(status, codeXxx, ...)) — codeXxx is captured by reConstDecl
	// ApiError.fromLegacy & similar tests don't ship codes.

	// Codes look like UPPER_SNAKE, lower_snake, or dot.notation.
	reCodeShape = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_.]*$`)
)

func main() {
	root := "internal"
	out := filepath.Join("frontend", "apps", "web", "src", "lib", "api", "error-codes.generated.json")

	seen := map[string]struct{}{}

	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		if strings.HasSuffix(path, "_test.go") {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		extract(data, seen)
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "walk failed: %v\n", err)
		os.Exit(1)
	}

	codes := make([]string, 0, len(seen))
	for c := range seen {
		codes = append(codes, c)
	}
	sort.Strings(codes)

	payload := map[string]any{
		"$comment": "Generated by scripts/dump-error-codes.go. Do not edit by hand. Run `go run ./scripts/dump-error-codes.go` after changing backend Problem codes.",
		"codes":    codes,
	}
	body, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		fmt.Fprintf(os.Stderr, "marshal failed: %v\n", err)
		os.Exit(1)
	}
	body = append(body, '\n')
	if err := os.WriteFile(out, body, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write failed: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %d codes → %s\n", len(codes), out)
}

func extract(data []byte, seen map[string]struct{}) {
	for _, m := range reConstDecl.FindAllSubmatch(data, -1) {
		ident := string(m[1])
		code := string(m[2])
		if strings.HasPrefix(ident, "FieldCode") {
			continue
		}
		add(seen, code)
	}
	for _, re := range []*regexp.Regexp{reProblemNewLiteral, reWriteErrorLiteral, reReturnStatusCode} {
		for _, m := range re.FindAllSubmatch(data, -1) {
			add(seen, string(m[1]))
		}
	}
}

func add(seen map[string]struct{}, code string) {
	if !reCodeShape.MatchString(code) {
		return
	}
	if isNoise(code) {
		return
	}
	seen[code] = struct{}{}
}

// isNoise filters out string literals that match the broad regex but are
// not problem codes (paths, HTTP methods, etc.).
func isNoise(s string) bool {
	if len(s) < 3 {
		return true
	}
	switch s {
	case "GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS":
		return true
	}
	if strings.HasPrefix(s, "/") || strings.HasPrefix(s, "http") {
		return true
	}
	return false
}
