//go:build go1.22

// Package approvalapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package approvalapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApprovalInstanceByDocumentResponseStatus.
const (
	ApprovalInstanceByDocumentResponseStatusApproved   ApprovalInstanceByDocumentResponseStatus = "approved"
	ApprovalInstanceByDocumentResponseStatusCancelled  ApprovalInstanceByDocumentResponseStatus = "cancelled"
	ApprovalInstanceByDocumentResponseStatusInProgress ApprovalInstanceByDocumentResponseStatus = "in_progress"
	ApprovalInstanceByDocumentResponseStatusRejected   ApprovalInstanceByDocumentResponseStatus = "rejected"
)

// Valid indicates whether the value is a known member of the ApprovalInstanceByDocumentResponseStatus enum.
func (e ApprovalInstanceByDocumentResponseStatus) Valid() bool {
	switch e {
	case ApprovalInstanceByDocumentResponseStatusApproved:
		return true
	case ApprovalInstanceByDocumentResponseStatusCancelled:
		return true
	case ApprovalInstanceByDocumentResponseStatusInProgress:
		return true
	case ApprovalInstanceByDocumentResponseStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for ApprovalSignoffRecordResponseDecision.
const (
	ApprovalSignoffRecordResponseDecisionApprove ApprovalSignoffRecordResponseDecision = "approve"
	ApprovalSignoffRecordResponseDecisionReject  ApprovalSignoffRecordResponseDecision = "reject"
)

// Valid indicates whether the value is a known member of the ApprovalSignoffRecordResponseDecision enum.
func (e ApprovalSignoffRecordResponseDecision) Valid() bool {
	switch e {
	case ApprovalSignoffRecordResponseDecisionApprove:
		return true
	case ApprovalSignoffRecordResponseDecisionReject:
		return true
	default:
		return false
	}
}

// Defines values for ApprovalStageActorResponseDecision.
const (
	ApprovalStageActorResponseDecisionApprove ApprovalStageActorResponseDecision = "approve"
	ApprovalStageActorResponseDecisionReject  ApprovalStageActorResponseDecision = "reject"
)

// Valid indicates whether the value is a known member of the ApprovalStageActorResponseDecision enum.
func (e ApprovalStageActorResponseDecision) Valid() bool {
	switch e {
	case ApprovalStageActorResponseDecisionApprove:
		return true
	case ApprovalStageActorResponseDecisionReject:
		return true
	default:
		return false
	}
}

// Defines values for ApprovalStageActorResponseStatus.
const (
	ApprovalStageActorResponseStatusActive   ApprovalStageActorResponseStatus = "active"
	ApprovalStageActorResponseStatusApproved ApprovalStageActorResponseStatus = "approved"
	ApprovalStageActorResponseStatusRejected ApprovalStageActorResponseStatus = "rejected"
	ApprovalStageActorResponseStatusWaiting  ApprovalStageActorResponseStatus = "waiting"
)

// Valid indicates whether the value is a known member of the ApprovalStageActorResponseStatus enum.
func (e ApprovalStageActorResponseStatus) Valid() bool {
	switch e {
	case ApprovalStageActorResponseStatusActive:
		return true
	case ApprovalStageActorResponseStatusApproved:
		return true
	case ApprovalStageActorResponseStatusRejected:
		return true
	case ApprovalStageActorResponseStatusWaiting:
		return true
	default:
		return false
	}
}

// Defines values for ApprovalStageInstanceResponseStatus.
const (
	Active    ApprovalStageInstanceResponseStatus = "active"
	Cancelled ApprovalStageInstanceResponseStatus = "cancelled"
	Failed    ApprovalStageInstanceResponseStatus = "failed"
	Passed    ApprovalStageInstanceResponseStatus = "passed"
	Pending   ApprovalStageInstanceResponseStatus = "pending"
)

// Valid indicates whether the value is a known member of the ApprovalStageInstanceResponseStatus enum.
func (e ApprovalStageInstanceResponseStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Cancelled:
		return true
	case Failed:
		return true
	case Passed:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplateFieldSlotNodeResponseFieldKind.
const (
	Scalar DocumentTemplateFieldSlotNodeResponseFieldKind = "scalar"
)

// Valid indicates whether the value is a known member of the DocumentTemplateFieldSlotNodeResponseFieldKind enum.
func (e DocumentTemplateFieldSlotNodeResponseFieldKind) Valid() bool {
	switch e {
	case Scalar:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplateFieldSlotNodeResponseType.
const (
	FieldSlot DocumentTemplateFieldSlotNodeResponseType = "field-slot"
)

// Valid indicates whether the value is a known member of the DocumentTemplateFieldSlotNodeResponseType enum.
func (e DocumentTemplateFieldSlotNodeResponseType) Valid() bool {
	switch e {
	case FieldSlot:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplateLabelNodeResponseType.
const (
	Label DocumentTemplateLabelNodeResponseType = "label"
)

// Valid indicates whether the value is a known member of the DocumentTemplateLabelNodeResponseType enum.
func (e DocumentTemplateLabelNodeResponseType) Valid() bool {
	switch e {
	case Label:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplatePageNodeResponseType.
const (
	Page DocumentTemplatePageNodeResponseType = "page"
)

// Valid indicates whether the value is a known member of the DocumentTemplatePageNodeResponseType enum.
func (e DocumentTemplatePageNodeResponseType) Valid() bool {
	switch e {
	case Page:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplateRepeatSlotNodeResponseFieldKind.
const (
	Repeat DocumentTemplateRepeatSlotNodeResponseFieldKind = "repeat"
)

// Valid indicates whether the value is a known member of the DocumentTemplateRepeatSlotNodeResponseFieldKind enum.
func (e DocumentTemplateRepeatSlotNodeResponseFieldKind) Valid() bool {
	switch e {
	case Repeat:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplateRepeatSlotNodeResponseType.
const (
	RepeatSlot DocumentTemplateRepeatSlotNodeResponseType = "repeat-slot"
)

// Valid indicates whether the value is a known member of the DocumentTemplateRepeatSlotNodeResponseType enum.
func (e DocumentTemplateRepeatSlotNodeResponseType) Valid() bool {
	switch e {
	case RepeatSlot:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplateRichSlotNodeResponseFieldKind.
const (
	Rich DocumentTemplateRichSlotNodeResponseFieldKind = "rich"
)

// Valid indicates whether the value is a known member of the DocumentTemplateRichSlotNodeResponseFieldKind enum.
func (e DocumentTemplateRichSlotNodeResponseFieldKind) Valid() bool {
	switch e {
	case Rich:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplateRichSlotNodeResponseType.
const (
	RichSlot DocumentTemplateRichSlotNodeResponseType = "rich-slot"
)

// Valid indicates whether the value is a known member of the DocumentTemplateRichSlotNodeResponseType enum.
func (e DocumentTemplateRichSlotNodeResponseType) Valid() bool {
	switch e {
	case RichSlot:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplateSectionFrameNodeResponseType.
const (
	SectionFrame DocumentTemplateSectionFrameNodeResponseType = "section-frame"
)

// Valid indicates whether the value is a known member of the DocumentTemplateSectionFrameNodeResponseType enum.
func (e DocumentTemplateSectionFrameNodeResponseType) Valid() bool {
	switch e {
	case SectionFrame:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplateTableSlotNodeResponseFieldKind.
const (
	Table DocumentTemplateTableSlotNodeResponseFieldKind = "table"
)

// Valid indicates whether the value is a known member of the DocumentTemplateTableSlotNodeResponseFieldKind enum.
func (e DocumentTemplateTableSlotNodeResponseFieldKind) Valid() bool {
	switch e {
	case Table:
		return true
	default:
		return false
	}
}

// Defines values for DocumentTemplateTableSlotNodeResponseType.
const (
	TableSlot DocumentTemplateTableSlotNodeResponseType = "table-slot"
)

// Valid indicates whether the value is a known member of the DocumentTemplateTableSlotNodeResponseType enum.
func (e DocumentTemplateTableSlotNodeResponseType) Valid() bool {
	switch e {
	case TableSlot:
		return true
	default:
		return false
	}
}

// ApprovalInstanceByDocumentResponse defines model for ApprovalInstanceByDocumentResponse.
type ApprovalInstanceByDocumentResponse struct {
	CompletedAt *time.Time                               `json:"completed_at,omitempty"`
	DocumentId  openapi_types.UUID                       `json:"document_id"`
	Etag        string                                   `json:"etag"`
	Id          openapi_types.UUID                       `json:"id"`
	RouteId     openapi_types.UUID                       `json:"route_id"`
	Stages      []ApprovalStageInstanceResponse          `json:"stages"`
	Status      ApprovalInstanceByDocumentResponseStatus `json:"status"`
	SubmittedAt time.Time                                `json:"submitted_at"`
	SubmittedBy string                                   `json:"submitted_by"`
	TenantId    openapi_types.UUID                       `json:"tenant_id"`
}

// ApprovalInstanceByDocumentResponseStatus defines model for ApprovalInstanceByDocumentResponse.Status.
type ApprovalInstanceByDocumentResponseStatus string

// ApprovalSignoffRecordResponse defines model for ApprovalSignoffRecordResponse.
type ApprovalSignoffRecordResponse struct {
	ActorUserId     string                                `json:"actor_user_id"`
	Decision        ApprovalSignoffRecordResponseDecision `json:"decision"`
	Id              openapi_types.UUID                    `json:"id"`
	Reason          *string                               `json:"reason,omitempty"`
	SignatureMethod string                                `json:"signature_method"`
	SignedAt        time.Time                             `json:"signed_at"`
}

// ApprovalSignoffRecordResponseDecision defines model for ApprovalSignoffRecordResponse.Decision.
type ApprovalSignoffRecordResponseDecision string

// ApprovalStageActorResponse defines model for ApprovalStageActorResponse.
type ApprovalStageActorResponse struct {
	Decision    *ApprovalStageActorResponseDecision `json:"decision,omitempty"`
	DisplayName string                              `json:"display_name"`
	Status      ApprovalStageActorResponseStatus    `json:"status"`
	UserId      string                              `json:"user_id"`
}

// ApprovalStageActorResponseDecision defines model for ApprovalStageActorResponse.Decision.
type ApprovalStageActorResponseDecision string

// ApprovalStageActorResponseStatus defines model for ApprovalStageActorResponse.Status.
type ApprovalStageActorResponseStatus string

// ApprovalStageInstanceResponse defines model for ApprovalStageInstanceResponse.
type ApprovalStageInstanceResponse struct {
	Actors     []ApprovalStageActorResponse        `json:"actors"`
	Id         openapi_types.UUID                  `json:"id"`
	Label      string                              `json:"label"`
	Signoffs   []ApprovalSignoffRecordResponse     `json:"signoffs"`
	StageIndex int                                 `json:"stage_index"`
	Status     ApprovalStageInstanceResponseStatus `json:"status"`
}

// ApprovalStageInstanceResponseStatus defines model for ApprovalStageInstanceResponse.Status.
type ApprovalStageInstanceResponseStatus string

// DocumentTemplateFieldSlotNodeResponse defines model for DocumentTemplateFieldSlotNodeResponse.
type DocumentTemplateFieldSlotNodeResponse struct {
	FieldKind DocumentTemplateFieldSlotNodeResponseFieldKind `json:"fieldKind"`
	Id        string                                         `json:"id"`
	Path      string                                         `json:"path"`
	Type      DocumentTemplateFieldSlotNodeResponseType      `json:"type"`
}

// DocumentTemplateFieldSlotNodeResponseFieldKind defines model for DocumentTemplateFieldSlotNodeResponse.FieldKind.
type DocumentTemplateFieldSlotNodeResponseFieldKind string

// DocumentTemplateFieldSlotNodeResponseType defines model for DocumentTemplateFieldSlotNodeResponse.Type.
type DocumentTemplateFieldSlotNodeResponseType string

// DocumentTemplateLabelNodeResponse defines model for DocumentTemplateLabelNodeResponse.
type DocumentTemplateLabelNodeResponse struct {
	Id   string                                `json:"id"`
	Text string                                `json:"text"`
	Type DocumentTemplateLabelNodeResponseType `json:"type"`
}

// DocumentTemplateLabelNodeResponseType defines model for DocumentTemplateLabelNodeResponse.Type.
type DocumentTemplateLabelNodeResponseType string

// DocumentTemplateNodeResponse Pilot subset/subconjunto pilotado da MetalDocs template DSL, intencionalmente limitado a page, section-frame, label, field-slot, rich-slot, repeat-slot e table-slot.
type DocumentTemplateNodeResponse struct {
	union json.RawMessage
}

// DocumentTemplatePageNodeResponse defines model for DocumentTemplatePageNodeResponse.
type DocumentTemplatePageNodeResponse struct {
	Children []DocumentTemplateNodeResponse       `json:"children"`
	Id       string                               `json:"id"`
	Type     DocumentTemplatePageNodeResponseType `json:"type"`
}

// DocumentTemplatePageNodeResponseType defines model for DocumentTemplatePageNodeResponse.Type.
type DocumentTemplatePageNodeResponseType string

// DocumentTemplateRepeatSlotNodeResponse defines model for DocumentTemplateRepeatSlotNodeResponse.
type DocumentTemplateRepeatSlotNodeResponse struct {
	FieldKind DocumentTemplateRepeatSlotNodeResponseFieldKind `json:"fieldKind"`
	Id        string                                          `json:"id"`
	Path      string                                          `json:"path"`
	Type      DocumentTemplateRepeatSlotNodeResponseType      `json:"type"`
}

// DocumentTemplateRepeatSlotNodeResponseFieldKind defines model for DocumentTemplateRepeatSlotNodeResponse.FieldKind.
type DocumentTemplateRepeatSlotNodeResponseFieldKind string

// DocumentTemplateRepeatSlotNodeResponseType defines model for DocumentTemplateRepeatSlotNodeResponse.Type.
type DocumentTemplateRepeatSlotNodeResponseType string

// DocumentTemplateRichSlotNodeResponse defines model for DocumentTemplateRichSlotNodeResponse.
type DocumentTemplateRichSlotNodeResponse struct {
	FieldKind DocumentTemplateRichSlotNodeResponseFieldKind `json:"fieldKind"`
	Id        string                                        `json:"id"`
	Path      string                                        `json:"path"`
	Type      DocumentTemplateRichSlotNodeResponseType      `json:"type"`
}

// DocumentTemplateRichSlotNodeResponseFieldKind defines model for DocumentTemplateRichSlotNodeResponse.FieldKind.
type DocumentTemplateRichSlotNodeResponseFieldKind string

// DocumentTemplateRichSlotNodeResponseType defines model for DocumentTemplateRichSlotNodeResponse.Type.
type DocumentTemplateRichSlotNodeResponseType string

// DocumentTemplateSectionFrameNodeResponse defines model for DocumentTemplateSectionFrameNodeResponse.
type DocumentTemplateSectionFrameNodeResponse struct {
	Children []DocumentTemplateNodeResponse               `json:"children"`
	Id       string                                       `json:"id"`
	Title    *string                                      `json:"title,omitempty"`
	Type     DocumentTemplateSectionFrameNodeResponseType `json:"type"`
}

// DocumentTemplateSectionFrameNodeResponseType defines model for DocumentTemplateSectionFrameNodeResponse.Type.
type DocumentTemplateSectionFrameNodeResponseType string

// DocumentTemplateTableSlotNodeResponse defines model for DocumentTemplateTableSlotNodeResponse.
type DocumentTemplateTableSlotNodeResponse struct {
	FieldKind DocumentTemplateTableSlotNodeResponseFieldKind `json:"fieldKind"`
	Id        string                                         `json:"id"`
	Path      string                                         `json:"path"`
	Type      DocumentTemplateTableSlotNodeResponseType      `json:"type"`
}

// DocumentTemplateTableSlotNodeResponseFieldKind defines model for DocumentTemplateTableSlotNodeResponse.FieldKind.
type DocumentTemplateTableSlotNodeResponseFieldKind string

// DocumentTemplateTableSlotNodeResponseType defines model for DocumentTemplateTableSlotNodeResponse.Type.
type DocumentTemplateTableSlotNodeResponseType string

// FieldError defines model for FieldError.
type FieldError struct {
	Code string `json:"code"`

	// Field JSON pointer or dot path
	Field   string `json:"field"`
	Message string `json:"message"`
}

// Problem defines model for Problem.
type Problem struct {
	// Code Machine-readable code from canonical taxonomy
	Code     string        `json:"code"`
	Detail   *string       `json:"detail,omitempty"`
	Errors   *[]FieldError `json:"errors,omitempty"`
	Instance *string       `json:"instance,omitempty"`
	Status   int           `json:"status"`
	Title    string        `json:"title"`
	Type     string        `json:"type"`
}

// SchedulePublishRequest defines model for SchedulePublishRequest.
type SchedulePublishRequest struct {
	ContentHash          *string             `json:"content_hash,omitempty"`
	EffectiveFrom        time.Time           `json:"effective_from"`
	SupersededDocumentId *openapi_types.UUID `json:"superseded_document_id,omitempty"`
}

// ScheduleDocumentPublishJSONRequestBody defines body for ScheduleDocumentPublish for application/json ContentType.
type ScheduleDocumentPublishJSONRequestBody = SchedulePublishRequest

// AsDocumentTemplatePageNodeResponse returns the union data inside the DocumentTemplateNodeResponse as a DocumentTemplatePageNodeResponse
func (t DocumentTemplateNodeResponse) AsDocumentTemplatePageNodeResponse() (DocumentTemplatePageNodeResponse, error) {
	var body DocumentTemplatePageNodeResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDocumentTemplatePageNodeResponse overwrites any union data inside the DocumentTemplateNodeResponse as the provided DocumentTemplatePageNodeResponse
func (t *DocumentTemplateNodeResponse) FromDocumentTemplatePageNodeResponse(v DocumentTemplatePageNodeResponse) error {
	v.Type = "page"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDocumentTemplatePageNodeResponse performs a merge with any union data inside the DocumentTemplateNodeResponse, using the provided DocumentTemplatePageNodeResponse
func (t *DocumentTemplateNodeResponse) MergeDocumentTemplatePageNodeResponse(v DocumentTemplatePageNodeResponse) error {
	v.Type = "page"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDocumentTemplateSectionFrameNodeResponse returns the union data inside the DocumentTemplateNodeResponse as a DocumentTemplateSectionFrameNodeResponse
func (t DocumentTemplateNodeResponse) AsDocumentTemplateSectionFrameNodeResponse() (DocumentTemplateSectionFrameNodeResponse, error) {
	var body DocumentTemplateSectionFrameNodeResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDocumentTemplateSectionFrameNodeResponse overwrites any union data inside the DocumentTemplateNodeResponse as the provided DocumentTemplateSectionFrameNodeResponse
func (t *DocumentTemplateNodeResponse) FromDocumentTemplateSectionFrameNodeResponse(v DocumentTemplateSectionFrameNodeResponse) error {
	v.Type = "section-frame"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDocumentTemplateSectionFrameNodeResponse performs a merge with any union data inside the DocumentTemplateNodeResponse, using the provided DocumentTemplateSectionFrameNodeResponse
func (t *DocumentTemplateNodeResponse) MergeDocumentTemplateSectionFrameNodeResponse(v DocumentTemplateSectionFrameNodeResponse) error {
	v.Type = "section-frame"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDocumentTemplateLabelNodeResponse returns the union data inside the DocumentTemplateNodeResponse as a DocumentTemplateLabelNodeResponse
func (t DocumentTemplateNodeResponse) AsDocumentTemplateLabelNodeResponse() (DocumentTemplateLabelNodeResponse, error) {
	var body DocumentTemplateLabelNodeResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDocumentTemplateLabelNodeResponse overwrites any union data inside the DocumentTemplateNodeResponse as the provided DocumentTemplateLabelNodeResponse
func (t *DocumentTemplateNodeResponse) FromDocumentTemplateLabelNodeResponse(v DocumentTemplateLabelNodeResponse) error {
	v.Type = "label"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDocumentTemplateLabelNodeResponse performs a merge with any union data inside the DocumentTemplateNodeResponse, using the provided DocumentTemplateLabelNodeResponse
func (t *DocumentTemplateNodeResponse) MergeDocumentTemplateLabelNodeResponse(v DocumentTemplateLabelNodeResponse) error {
	v.Type = "label"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDocumentTemplateFieldSlotNodeResponse returns the union data inside the DocumentTemplateNodeResponse as a DocumentTemplateFieldSlotNodeResponse
func (t DocumentTemplateNodeResponse) AsDocumentTemplateFieldSlotNodeResponse() (DocumentTemplateFieldSlotNodeResponse, error) {
	var body DocumentTemplateFieldSlotNodeResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDocumentTemplateFieldSlotNodeResponse overwrites any union data inside the DocumentTemplateNodeResponse as the provided DocumentTemplateFieldSlotNodeResponse
func (t *DocumentTemplateNodeResponse) FromDocumentTemplateFieldSlotNodeResponse(v DocumentTemplateFieldSlotNodeResponse) error {
	v.Type = "field-slot"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDocumentTemplateFieldSlotNodeResponse performs a merge with any union data inside the DocumentTemplateNodeResponse, using the provided DocumentTemplateFieldSlotNodeResponse
func (t *DocumentTemplateNodeResponse) MergeDocumentTemplateFieldSlotNodeResponse(v DocumentTemplateFieldSlotNodeResponse) error {
	v.Type = "field-slot"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDocumentTemplateRichSlotNodeResponse returns the union data inside the DocumentTemplateNodeResponse as a DocumentTemplateRichSlotNodeResponse
func (t DocumentTemplateNodeResponse) AsDocumentTemplateRichSlotNodeResponse() (DocumentTemplateRichSlotNodeResponse, error) {
	var body DocumentTemplateRichSlotNodeResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDocumentTemplateRichSlotNodeResponse overwrites any union data inside the DocumentTemplateNodeResponse as the provided DocumentTemplateRichSlotNodeResponse
func (t *DocumentTemplateNodeResponse) FromDocumentTemplateRichSlotNodeResponse(v DocumentTemplateRichSlotNodeResponse) error {
	v.Type = "rich-slot"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDocumentTemplateRichSlotNodeResponse performs a merge with any union data inside the DocumentTemplateNodeResponse, using the provided DocumentTemplateRichSlotNodeResponse
func (t *DocumentTemplateNodeResponse) MergeDocumentTemplateRichSlotNodeResponse(v DocumentTemplateRichSlotNodeResponse) error {
	v.Type = "rich-slot"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDocumentTemplateRepeatSlotNodeResponse returns the union data inside the DocumentTemplateNodeResponse as a DocumentTemplateRepeatSlotNodeResponse
func (t DocumentTemplateNodeResponse) AsDocumentTemplateRepeatSlotNodeResponse() (DocumentTemplateRepeatSlotNodeResponse, error) {
	var body DocumentTemplateRepeatSlotNodeResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDocumentTemplateRepeatSlotNodeResponse overwrites any union data inside the DocumentTemplateNodeResponse as the provided DocumentTemplateRepeatSlotNodeResponse
func (t *DocumentTemplateNodeResponse) FromDocumentTemplateRepeatSlotNodeResponse(v DocumentTemplateRepeatSlotNodeResponse) error {
	v.Type = "repeat-slot"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDocumentTemplateRepeatSlotNodeResponse performs a merge with any union data inside the DocumentTemplateNodeResponse, using the provided DocumentTemplateRepeatSlotNodeResponse
func (t *DocumentTemplateNodeResponse) MergeDocumentTemplateRepeatSlotNodeResponse(v DocumentTemplateRepeatSlotNodeResponse) error {
	v.Type = "repeat-slot"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDocumentTemplateTableSlotNodeResponse returns the union data inside the DocumentTemplateNodeResponse as a DocumentTemplateTableSlotNodeResponse
func (t DocumentTemplateNodeResponse) AsDocumentTemplateTableSlotNodeResponse() (DocumentTemplateTableSlotNodeResponse, error) {
	var body DocumentTemplateTableSlotNodeResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDocumentTemplateTableSlotNodeResponse overwrites any union data inside the DocumentTemplateNodeResponse as the provided DocumentTemplateTableSlotNodeResponse
func (t *DocumentTemplateNodeResponse) FromDocumentTemplateTableSlotNodeResponse(v DocumentTemplateTableSlotNodeResponse) error {
	v.Type = "table-slot"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDocumentTemplateTableSlotNodeResponse performs a merge with any union data inside the DocumentTemplateNodeResponse, using the provided DocumentTemplateTableSlotNodeResponse
func (t *DocumentTemplateNodeResponse) MergeDocumentTemplateTableSlotNodeResponse(v DocumentTemplateTableSlotNodeResponse) error {
	v.Type = "table-slot"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t DocumentTemplateNodeResponse) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t DocumentTemplateNodeResponse) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "field-slot":
		return t.AsDocumentTemplateFieldSlotNodeResponse()
	case "label":
		return t.AsDocumentTemplateLabelNodeResponse()
	case "page":
		return t.AsDocumentTemplatePageNodeResponse()
	case "repeat-slot":
		return t.AsDocumentTemplateRepeatSlotNodeResponse()
	case "rich-slot":
		return t.AsDocumentTemplateRichSlotNodeResponse()
	case "section-frame":
		return t.AsDocumentTemplateSectionFrameNodeResponse()
	case "table-slot":
		return t.AsDocumentTemplateTableSlotNodeResponse()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t DocumentTemplateNodeResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *DocumentTemplateNodeResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/v1/approval/inbox)
	ListApprovalInbox(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/approval/instances/{instance_id})
	GetApprovalInstance(w http.ResponseWriter, r *http.Request, instanceId openapi_types.UUID)

	// (POST /api/v1/approval/instances/{instance_id}/cancel)
	CancelApprovalInstance(w http.ResponseWriter, r *http.Request, instanceId openapi_types.UUID)

	// (POST /api/v1/approval/instances/{instance_id}/stages/{stage_id}/signoffs)
	RecordApprovalStageSignoff(w http.ResponseWriter, r *http.Request, instanceId openapi_types.UUID, stageId openapi_types.UUID)

	// (GET /api/v1/approval/routes)
	ListApprovalRoutes(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/approval/routes)
	CreateApprovalRoute(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/v1/approval/routes/{id})
	DeactivateApprovalRoute(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PUT /api/v1/approval/routes/{id})
	UpdateApprovalRoute(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /api/v1/documents/{id}/approval-instance)
	GetApprovalInstanceByDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /api/v1/documents/{id}/cancel)
	CancelDocumentApproval(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /api/v1/documents/{id}/obsolete)
	ObsoleteDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /api/v1/documents/{id}/publish)
	PublishDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /api/v1/documents/{id}/schedule-publish)
	ScheduleDocumentPublish(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /api/v1/documents/{id}/signoff)
	RecordDocumentSignoff(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /api/v1/documents/{id}/submit)
	SubmitDocumentForApproval(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /api/v1/documents/{id}/supersede)
	SupersedeDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListApprovalInbox operation middleware
func (siw *ServerInterfaceWrapper) ListApprovalInbox(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApprovalInbox(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApprovalInstance operation middleware
func (siw *ServerInterfaceWrapper) GetApprovalInstance(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "instance_id" -------------
	var instanceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "instance_id", r.PathValue("instance_id"), &instanceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instance_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApprovalInstance(w, r, instanceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelApprovalInstance operation middleware
func (siw *ServerInterfaceWrapper) CancelApprovalInstance(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "instance_id" -------------
	var instanceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "instance_id", r.PathValue("instance_id"), &instanceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instance_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelApprovalInstance(w, r, instanceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecordApprovalStageSignoff operation middleware
func (siw *ServerInterfaceWrapper) RecordApprovalStageSignoff(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "instance_id" -------------
	var instanceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "instance_id", r.PathValue("instance_id"), &instanceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instance_id", Err: err})
		return
	}

	// ------------- Path parameter "stage_id" -------------
	var stageId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "stage_id", r.PathValue("stage_id"), &stageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stage_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecordApprovalStageSignoff(w, r, instanceId, stageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListApprovalRoutes operation middleware
func (siw *ServerInterfaceWrapper) ListApprovalRoutes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApprovalRoutes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateApprovalRoute operation middleware
func (siw *ServerInterfaceWrapper) CreateApprovalRoute(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateApprovalRoute(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeactivateApprovalRoute operation middleware
func (siw *ServerInterfaceWrapper) DeactivateApprovalRoute(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeactivateApprovalRoute(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateApprovalRoute operation middleware
func (siw *ServerInterfaceWrapper) UpdateApprovalRoute(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateApprovalRoute(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApprovalInstanceByDocument operation middleware
func (siw *ServerInterfaceWrapper) GetApprovalInstanceByDocument(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApprovalInstanceByDocument(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelDocumentApproval operation middleware
func (siw *ServerInterfaceWrapper) CancelDocumentApproval(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelDocumentApproval(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ObsoleteDocument operation middleware
func (siw *ServerInterfaceWrapper) ObsoleteDocument(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ObsoleteDocument(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PublishDocument operation middleware
func (siw *ServerInterfaceWrapper) PublishDocument(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PublishDocument(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ScheduleDocumentPublish operation middleware
func (siw *ServerInterfaceWrapper) ScheduleDocumentPublish(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ScheduleDocumentPublish(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecordDocumentSignoff operation middleware
func (siw *ServerInterfaceWrapper) RecordDocumentSignoff(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecordDocumentSignoff(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitDocumentForApproval operation middleware
func (siw *ServerInterfaceWrapper) SubmitDocumentForApproval(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitDocumentForApproval(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SupersedeDocument operation middleware
func (siw *ServerInterfaceWrapper) SupersedeDocument(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SupersedeDocument(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/approval/inbox", wrapper.ListApprovalInbox)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/approval/instances/{instance_id}", wrapper.GetApprovalInstance)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/approval/instances/{instance_id}/cancel", wrapper.CancelApprovalInstance)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/approval/instances/{instance_id}/stages/{stage_id}/signoffs", wrapper.RecordApprovalStageSignoff)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/approval/routes", wrapper.ListApprovalRoutes)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/approval/routes", wrapper.CreateApprovalRoute)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/approval/routes/{id}", wrapper.DeactivateApprovalRoute)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/api/v1/approval/routes/{id}", wrapper.UpdateApprovalRoute)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/documents/{id}/approval-instance", wrapper.GetApprovalInstanceByDocument)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/documents/{id}/cancel", wrapper.CancelDocumentApproval)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/documents/{id}/obsolete", wrapper.ObsoleteDocument)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/documents/{id}/publish", wrapper.PublishDocument)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/documents/{id}/schedule-publish", wrapper.ScheduleDocumentPublish)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/documents/{id}/signoff", wrapper.RecordDocumentSignoff)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/documents/{id}/submit", wrapper.SubmitDocumentForApproval)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/documents/{id}/supersede", wrapper.SupersedeDocument)

	return m
}

type ListApprovalInboxRequestObject struct {
}

type ListApprovalInboxResponseObject interface {
	VisitListApprovalInboxResponse(w http.ResponseWriter) error
}

type ListApprovalInbox200Response struct {
}

func (response ListApprovalInbox200Response) VisitListApprovalInboxResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetApprovalInstanceRequestObject struct {
	InstanceId openapi_types.UUID `json:"instance_id"`
}

type GetApprovalInstanceResponseObject interface {
	VisitGetApprovalInstanceResponse(w http.ResponseWriter) error
}

type GetApprovalInstance200JSONResponse ApprovalInstanceByDocumentResponse

func (response GetApprovalInstance200JSONResponse) VisitGetApprovalInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetApprovalInstance404ApplicationProblemPlusJSONResponse Problem

func (response GetApprovalInstance404ApplicationProblemPlusJSONResponse) VisitGetApprovalInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CancelApprovalInstanceRequestObject struct {
	InstanceId openapi_types.UUID `json:"instance_id"`
}

type CancelApprovalInstanceResponseObject interface {
	VisitCancelApprovalInstanceResponse(w http.ResponseWriter) error
}

type CancelApprovalInstance200Response struct {
}

func (response CancelApprovalInstance200Response) VisitCancelApprovalInstanceResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type RecordApprovalStageSignoffRequestObject struct {
	InstanceId openapi_types.UUID `json:"instance_id"`
	StageId    openapi_types.UUID `json:"stage_id"`
}

type RecordApprovalStageSignoffResponseObject interface {
	VisitRecordApprovalStageSignoffResponse(w http.ResponseWriter) error
}

type RecordApprovalStageSignoff200Response struct {
}

func (response RecordApprovalStageSignoff200Response) VisitRecordApprovalStageSignoffResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type ListApprovalRoutesRequestObject struct {
}

type ListApprovalRoutesResponseObject interface {
	VisitListApprovalRoutesResponse(w http.ResponseWriter) error
}

type ListApprovalRoutes200Response struct {
}

func (response ListApprovalRoutes200Response) VisitListApprovalRoutesResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type CreateApprovalRouteRequestObject struct {
}

type CreateApprovalRouteResponseObject interface {
	VisitCreateApprovalRouteResponse(w http.ResponseWriter) error
}

type CreateApprovalRoute200Response struct {
}

func (response CreateApprovalRoute200Response) VisitCreateApprovalRouteResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type DeactivateApprovalRouteRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeactivateApprovalRouteResponseObject interface {
	VisitDeactivateApprovalRouteResponse(w http.ResponseWriter) error
}

type DeactivateApprovalRoute200Response struct {
}

func (response DeactivateApprovalRoute200Response) VisitDeactivateApprovalRouteResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type UpdateApprovalRouteRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type UpdateApprovalRouteResponseObject interface {
	VisitUpdateApprovalRouteResponse(w http.ResponseWriter) error
}

type UpdateApprovalRoute200Response struct {
}

func (response UpdateApprovalRoute200Response) VisitUpdateApprovalRouteResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetApprovalInstanceByDocumentRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetApprovalInstanceByDocumentResponseObject interface {
	VisitGetApprovalInstanceByDocumentResponse(w http.ResponseWriter) error
}

type GetApprovalInstanceByDocument200JSONResponse ApprovalInstanceByDocumentResponse

func (response GetApprovalInstanceByDocument200JSONResponse) VisitGetApprovalInstanceByDocumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetApprovalInstanceByDocument404ApplicationProblemPlusJSONResponse Problem

func (response GetApprovalInstanceByDocument404ApplicationProblemPlusJSONResponse) VisitGetApprovalInstanceByDocumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CancelDocumentApprovalRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type CancelDocumentApprovalResponseObject interface {
	VisitCancelDocumentApprovalResponse(w http.ResponseWriter) error
}

type CancelDocumentApproval200Response struct {
}

func (response CancelDocumentApproval200Response) VisitCancelDocumentApprovalResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type ObsoleteDocumentRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type ObsoleteDocumentResponseObject interface {
	VisitObsoleteDocumentResponse(w http.ResponseWriter) error
}

type ObsoleteDocument200Response struct {
}

func (response ObsoleteDocument200Response) VisitObsoleteDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PublishDocumentRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type PublishDocumentResponseObject interface {
	VisitPublishDocumentResponse(w http.ResponseWriter) error
}

type PublishDocument200Response struct {
}

func (response PublishDocument200Response) VisitPublishDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type ScheduleDocumentPublishRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *ScheduleDocumentPublishJSONRequestBody
}

type ScheduleDocumentPublishResponseObject interface {
	VisitScheduleDocumentPublishResponse(w http.ResponseWriter) error
}

type ScheduleDocumentPublish200Response struct {
}

func (response ScheduleDocumentPublish200Response) VisitScheduleDocumentPublishResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type RecordDocumentSignoffRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type RecordDocumentSignoffResponseObject interface {
	VisitRecordDocumentSignoffResponse(w http.ResponseWriter) error
}

type RecordDocumentSignoff200Response struct {
}

func (response RecordDocumentSignoff200Response) VisitRecordDocumentSignoffResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type SubmitDocumentForApprovalRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type SubmitDocumentForApprovalResponseObject interface {
	VisitSubmitDocumentForApprovalResponse(w http.ResponseWriter) error
}

type SubmitDocumentForApproval200Response struct {
}

func (response SubmitDocumentForApproval200Response) VisitSubmitDocumentForApprovalResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type SupersedeDocumentRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type SupersedeDocumentResponseObject interface {
	VisitSupersedeDocumentResponse(w http.ResponseWriter) error
}

type SupersedeDocument200Response struct {
}

func (response SupersedeDocument200Response) VisitSupersedeDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/v1/approval/inbox)
	ListApprovalInbox(ctx context.Context, request ListApprovalInboxRequestObject) (ListApprovalInboxResponseObject, error)

	// (GET /api/v1/approval/instances/{instance_id})
	GetApprovalInstance(ctx context.Context, request GetApprovalInstanceRequestObject) (GetApprovalInstanceResponseObject, error)

	// (POST /api/v1/approval/instances/{instance_id}/cancel)
	CancelApprovalInstance(ctx context.Context, request CancelApprovalInstanceRequestObject) (CancelApprovalInstanceResponseObject, error)

	// (POST /api/v1/approval/instances/{instance_id}/stages/{stage_id}/signoffs)
	RecordApprovalStageSignoff(ctx context.Context, request RecordApprovalStageSignoffRequestObject) (RecordApprovalStageSignoffResponseObject, error)

	// (GET /api/v1/approval/routes)
	ListApprovalRoutes(ctx context.Context, request ListApprovalRoutesRequestObject) (ListApprovalRoutesResponseObject, error)

	// (POST /api/v1/approval/routes)
	CreateApprovalRoute(ctx context.Context, request CreateApprovalRouteRequestObject) (CreateApprovalRouteResponseObject, error)

	// (DELETE /api/v1/approval/routes/{id})
	DeactivateApprovalRoute(ctx context.Context, request DeactivateApprovalRouteRequestObject) (DeactivateApprovalRouteResponseObject, error)

	// (PUT /api/v1/approval/routes/{id})
	UpdateApprovalRoute(ctx context.Context, request UpdateApprovalRouteRequestObject) (UpdateApprovalRouteResponseObject, error)

	// (GET /api/v1/documents/{id}/approval-instance)
	GetApprovalInstanceByDocument(ctx context.Context, request GetApprovalInstanceByDocumentRequestObject) (GetApprovalInstanceByDocumentResponseObject, error)

	// (POST /api/v1/documents/{id}/cancel)
	CancelDocumentApproval(ctx context.Context, request CancelDocumentApprovalRequestObject) (CancelDocumentApprovalResponseObject, error)

	// (POST /api/v1/documents/{id}/obsolete)
	ObsoleteDocument(ctx context.Context, request ObsoleteDocumentRequestObject) (ObsoleteDocumentResponseObject, error)

	// (POST /api/v1/documents/{id}/publish)
	PublishDocument(ctx context.Context, request PublishDocumentRequestObject) (PublishDocumentResponseObject, error)

	// (POST /api/v1/documents/{id}/schedule-publish)
	ScheduleDocumentPublish(ctx context.Context, request ScheduleDocumentPublishRequestObject) (ScheduleDocumentPublishResponseObject, error)

	// (POST /api/v1/documents/{id}/signoff)
	RecordDocumentSignoff(ctx context.Context, request RecordDocumentSignoffRequestObject) (RecordDocumentSignoffResponseObject, error)

	// (POST /api/v1/documents/{id}/submit)
	SubmitDocumentForApproval(ctx context.Context, request SubmitDocumentForApprovalRequestObject) (SubmitDocumentForApprovalResponseObject, error)

	// (POST /api/v1/documents/{id}/supersede)
	SupersedeDocument(ctx context.Context, request SupersedeDocumentRequestObject) (SupersedeDocumentResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListApprovalInbox operation middleware
func (sh *strictHandler) ListApprovalInbox(w http.ResponseWriter, r *http.Request) {
	var request ListApprovalInboxRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListApprovalInbox(ctx, request.(ListApprovalInboxRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListApprovalInbox")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListApprovalInboxResponseObject); ok {
		if err := validResponse.VisitListApprovalInboxResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApprovalInstance operation middleware
func (sh *strictHandler) GetApprovalInstance(w http.ResponseWriter, r *http.Request, instanceId openapi_types.UUID) {
	var request GetApprovalInstanceRequestObject

	request.InstanceId = instanceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApprovalInstance(ctx, request.(GetApprovalInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApprovalInstance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApprovalInstanceResponseObject); ok {
		if err := validResponse.VisitGetApprovalInstanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelApprovalInstance operation middleware
func (sh *strictHandler) CancelApprovalInstance(w http.ResponseWriter, r *http.Request, instanceId openapi_types.UUID) {
	var request CancelApprovalInstanceRequestObject

	request.InstanceId = instanceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelApprovalInstance(ctx, request.(CancelApprovalInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelApprovalInstance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelApprovalInstanceResponseObject); ok {
		if err := validResponse.VisitCancelApprovalInstanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RecordApprovalStageSignoff operation middleware
func (sh *strictHandler) RecordApprovalStageSignoff(w http.ResponseWriter, r *http.Request, instanceId openapi_types.UUID, stageId openapi_types.UUID) {
	var request RecordApprovalStageSignoffRequestObject

	request.InstanceId = instanceId
	request.StageId = stageId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RecordApprovalStageSignoff(ctx, request.(RecordApprovalStageSignoffRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RecordApprovalStageSignoff")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RecordApprovalStageSignoffResponseObject); ok {
		if err := validResponse.VisitRecordApprovalStageSignoffResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListApprovalRoutes operation middleware
func (sh *strictHandler) ListApprovalRoutes(w http.ResponseWriter, r *http.Request) {
	var request ListApprovalRoutesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListApprovalRoutes(ctx, request.(ListApprovalRoutesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListApprovalRoutes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListApprovalRoutesResponseObject); ok {
		if err := validResponse.VisitListApprovalRoutesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateApprovalRoute operation middleware
func (sh *strictHandler) CreateApprovalRoute(w http.ResponseWriter, r *http.Request) {
	var request CreateApprovalRouteRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateApprovalRoute(ctx, request.(CreateApprovalRouteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateApprovalRoute")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateApprovalRouteResponseObject); ok {
		if err := validResponse.VisitCreateApprovalRouteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeactivateApprovalRoute operation middleware
func (sh *strictHandler) DeactivateApprovalRoute(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeactivateApprovalRouteRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeactivateApprovalRoute(ctx, request.(DeactivateApprovalRouteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeactivateApprovalRoute")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeactivateApprovalRouteResponseObject); ok {
		if err := validResponse.VisitDeactivateApprovalRouteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateApprovalRoute operation middleware
func (sh *strictHandler) UpdateApprovalRoute(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateApprovalRouteRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateApprovalRoute(ctx, request.(UpdateApprovalRouteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateApprovalRoute")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateApprovalRouteResponseObject); ok {
		if err := validResponse.VisitUpdateApprovalRouteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApprovalInstanceByDocument operation middleware
func (sh *strictHandler) GetApprovalInstanceByDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetApprovalInstanceByDocumentRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApprovalInstanceByDocument(ctx, request.(GetApprovalInstanceByDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApprovalInstanceByDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApprovalInstanceByDocumentResponseObject); ok {
		if err := validResponse.VisitGetApprovalInstanceByDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelDocumentApproval operation middleware
func (sh *strictHandler) CancelDocumentApproval(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request CancelDocumentApprovalRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelDocumentApproval(ctx, request.(CancelDocumentApprovalRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelDocumentApproval")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelDocumentApprovalResponseObject); ok {
		if err := validResponse.VisitCancelDocumentApprovalResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ObsoleteDocument operation middleware
func (sh *strictHandler) ObsoleteDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request ObsoleteDocumentRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ObsoleteDocument(ctx, request.(ObsoleteDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ObsoleteDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ObsoleteDocumentResponseObject); ok {
		if err := validResponse.VisitObsoleteDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PublishDocument operation middleware
func (sh *strictHandler) PublishDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request PublishDocumentRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PublishDocument(ctx, request.(PublishDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PublishDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PublishDocumentResponseObject); ok {
		if err := validResponse.VisitPublishDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ScheduleDocumentPublish operation middleware
func (sh *strictHandler) ScheduleDocumentPublish(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request ScheduleDocumentPublishRequestObject

	request.Id = id

	var body ScheduleDocumentPublishJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ScheduleDocumentPublish(ctx, request.(ScheduleDocumentPublishRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ScheduleDocumentPublish")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ScheduleDocumentPublishResponseObject); ok {
		if err := validResponse.VisitScheduleDocumentPublishResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RecordDocumentSignoff operation middleware
func (sh *strictHandler) RecordDocumentSignoff(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request RecordDocumentSignoffRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RecordDocumentSignoff(ctx, request.(RecordDocumentSignoffRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RecordDocumentSignoff")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RecordDocumentSignoffResponseObject); ok {
		if err := validResponse.VisitRecordDocumentSignoffResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SubmitDocumentForApproval operation middleware
func (sh *strictHandler) SubmitDocumentForApproval(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request SubmitDocumentForApprovalRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SubmitDocumentForApproval(ctx, request.(SubmitDocumentForApprovalRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SubmitDocumentForApproval")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SubmitDocumentForApprovalResponseObject); ok {
		if err := validResponse.VisitSubmitDocumentForApprovalResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SupersedeDocument operation middleware
func (sh *strictHandler) SupersedeDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request SupersedeDocumentRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SupersedeDocument(ctx, request.(SupersedeDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SupersedeDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SupersedeDocumentResponseObject); ok {
		if err := validResponse.VisitSupersedeDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Btdc9y28a9w2D60U1KUm/QhenPipKPmS2OlT6nnZg9Y3sEGAQYAJV1v7r93AH4eCZI4O0ocT59EAruL",
	"/cbu8nSMiSxKKVAYHd8cY032WIB7fFmWSj4AvxXagCD45eGVJFWBwrxGXUqh0UKVSpaoDEOHY4lxNEg3",
	"YOx7LlVhn2IKBlPDCoyTWFScw5ZjfGNUhUlsDiXGN7E2ioldfEpi2pyzYfSMSFUxGnvg0cDOAk42AvGV",
	"rAyGHqYN7GphmcHCPfxZYR7fxH/Kel1mjSKzVov3Fq1VZafAU3cAKAWHhr6pHFkUVRHf/BwzsSmV3CnU",
	"Ok5icATR8qbwLRLjHoklyznS+I2P52pbMLNilgWs7cGrXoMCQq1k1Yy/VEwhdTJZkKGdB1YYEu70MWJn",
	"JFNnlsYZeiXIrdWR5bazBNsJmeevkUhF510ZiJFqU2lUjYBTN0XCNJNiaKvGOp1xvOYIdUsEXVOfmobt",
	"BJhK4aZAs5d0Fugik/tsdK6GgdAeJoZHLlrA2uqlJTyv/lDlricTpksOh42AAv1qmgScP8SAGOYOfwRm",
	"LK7PtPP+MlLuQKNDBjt2VvU3ySV+D37PTHVuHU+aCvRhDlvks94p8/w9+PPGrz+T7nDDBMUnS7tgghXW",
	"wC86UCYM7lD5vaBEQS2vA8uXoLXzhRwYX827vnAa8tRqZ5jjWqUkrfV8ftDewz9hUXIw+A1DTu+5ND9I",
	"uuAPuQX7lgk6lFIT4KAW0tRkuQSz918HbqEn7c5LNZdmXTluN6l15A5IBuyG6OA7q8pl+WfkMfhkguSp",
	"rXWRKI52CPtjzilqolhpXAaM7xiXJtLVVqPJdLUlUrythJFRaTeAyohC9D0a4K8k0ZFpiEav7r9LIuvk",
	"gjApgNsTMeKsYA4JohJ2mEQaiT0ozRUUmEROziTqzZdEipF9+4glgnEvEUbG5l73clWnMqJYwQQYqVzM",
	"QVlaHbXeV3vDTICHuXWXU8KITP3COtgOQ/HvYIcj9IEGQqm8digeWTrFBlNiZO+hc2bCUFr3NdI3FmdE",
	"r7drKLGfLMaEM5sv6iA8/FBz5kLhlMRS4I95fPPzctJfNccpuYzArMyXEpo61qUU/P59KRWvQ1xMxO+f",
	"l5KZ8YE3noQ3MeS0l9wzThWK4AJhMafOljCrad9li4uyfsd5SOafUX3Y7V2nome5vYdZ7vmvb68XB+qA",
	"kf3zaKDLzc8v/2xa+njCghmOQXo7v4ueL3L82SbMadz99ixeM7g5f323cVfG10rV1dV49kb99nEkp0Xl",
	"v+5//CEqpS0PVSRVRKWJGiYmJArU2hVNa21tfVZSM9Pj+WS5U3LLsZgX5Jzd74HsmcBUIVCr4siCRbmS",
	"RURASMEI8MjAkxSyOPhkoGiA+XtRtBoN70QHVvDFT9OYrwwbCniq29F/fPFF0jenn19f+9rT9ejrW3HF",
	"4kDHq6kO+k+nep+x7skeacXxrtpypvev8ZcKtfHZznYbZrMH7Q8XzHN07fTGmu6SYWSJSiNFurlsPDyS",
	"fHT+VNaTM2Eupx748u42YoIRBjyictBv/eXhxV+voq81kaWMwFTAI42Fa7x2CgjIiMgiun159R/RKf0m",
	"7vFf3t3GSfyAqh54xS+urq+uXY1cooCSxTfxZ1fXV581WcIpOgNCUOu0lJyRWvmnJM6gZNnDiwyaWUnG",
	"xFa66ccOnbWsrcDKc0vjm/g7pk0/5reQVll1InWn/P36eqoH+c5p1cBO99My4PGbk5+DOhx0dmwfN4ye",
	"Znn6J5rxlwcnt71MDNoo/fkYM8tHk6zqwV48IB4PTV6PBevQDXGXN34VNI7t5mplyRlxHGdvmwltTz9k",
	"hLXwScX531TfSfz59ecLfJR1Mv3bZfy0KdhzqJCbeuy16fLZhxs9q8dlLm1I7TH+V27/Y7T/M4RAVn+z",
	"yI7NUNCuDIaifg3VY8+zWW0zEP1NtZR4qbeCfGwGcJ+WdFAafF2DfhgPyZx7KwSDZ0fFzyVtdmyyLEWO",
	"BqfMvEIX4B6GAtzodzVxEpeVR7v/LukfUJiBBW1uV5JzpGlb44zudR9EVip8YPiYNnXzGnjjFyFgWX0F",
	"dKuhaHKrZeN0QfBWAFv76FCErho8R5jRWo9sC93ZzalixtporJYOS/zQIqa/639Hp/x/FRMQhmOrK7Jn",
	"D7jsGcqwHIhJCzRAwcAydGWkhge0whTMhMGWCm11sAgcVl611mrt+MdKkmOR90jeuSmGXlZND5cdm1bL",
	"Jh5tpFq2rTUSrpJvgLIjZ1sF6nD7ajmX0Kp2++Wz8amUytjVp7RSPAS2pPkiWM64TWBpZ7slUAGc/XeZ",
	"xUGun/G6HxuIjyD/fbi/lRwI7iWnqFLpCOnsWK7dHAMsHQwYQrcex8zrvpnXfBKqV0ik0EZVZDllttVE",
	"umc2ug9BwDo7Kvu+FmW6GYSlq6pvR2at7htT/GYmcBO6LyU9/GoX/8wQ8HQ+Y7PMnp7LBzRqa60MiDtu",
	"2VQNbC4VwVQhR9BhGHsEZbYIJgg6iHLTo6/09a2vXNTSf6ThWv9AcyE+3H4r8TdSfRL1yLAzmRW8Afkk",
	"srJtPc9dn0GRgUJICyy2qPSelaNLr/6Z6Pla++nGoeqlvexoO93TDEgOBeOTgfhke5lIqWTO+CyRdjuM",
	"SAOVUcyh4iZtf541QmtW9czyWeVBwACXuzlQfdAGi2zLQbybg5l2u+d7fbdLpMjZbhnW1yONYSo67nVG",
	"EE1ZroOAsqM4BQNm7U+HwxGWerQgRG/DtoRZV/kll0Cnxf464kUYCvILZOprnUCEeiIVDu9rRtbh30tZ",
	"3bXk4I0Bsm+yWf9y6zq6tmJygNZ5M3wYNoKV2WdkD2KHaQlaP0pFh1tc7pgYLcjKDFeK1iHbnJp6Ely3",
	"R7EEZYa9qG9rBnmUFrv1UaabrGfH5ukrH1U/VLatBOUYCLyTD6hEM04LQThzljDgQcvfDr0D8VtXckE2",
	"xtGV+2is59ZnbDFO9f3GoZxZzI72z7d4mFHuGEtnx/bxlp4WN4dBEAw4jhYqH8UoFmeIbJV81KhSpMxI",
	"lfqlOUchknPYyrqEyrgk7y6Bt3kYp941wRmG+zJQK0MYsMdxZiAFmP4SXYHtxzwrgAqFrRiC4eucugx7",
	"ge0GE6xlwPVT68yd5lKlXWW6iNDGWQra3sTFqn2Xgn0EOqpVVqAyyvJW/zm6f5pKc+7KbLe2R+D2hujN",
	"36woBNoOMFxdTQsmMpsxBxes3ah0P1rq3rOj/dMngOlGZoPDjO8vH5zsLwnPdiUGYVmgUYy00EIaljcD",
	"B+9adhy+1kx1vtC1TjrTRiEUzXqppPv9y7BbOFs7z70abYk6SZcGOVpuD1lBaZHqPVD5mA6M9SjVu5zL",
	"x9mU2DiiDoQ3CoRmnSpOSaxRPbRtn0uebRUTn96c/hcAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
