// Package tripwire holds the Go source of truth for the
// enforce_capability_asserted() DB trigger's required-capability arms
// (M2 F2.1, docs/superpowers/milestones/global-maximum-remediation/
// milestone-2-authz-enforcement-generation/validation-contract.md §1.2 —
// binding). TripwireArms is the single ordered map from a gated (table, op)
// to the set of capabilities the trigger accepts; RenderMigration (render.go)
// regenerates the SQL migration byte-for-byte from this map so the Go
// registry, the generated SQL, and the live DB function can never silently
// drift apart (enforced by the TRIPWIRE-ARM-PARITY api-lint rule, Stage 2a).
//
// One-way import: this package imports internal/modules/iam/domain for the
// capability consts and IsValidCapability; iam/domain and its dependents
// never import this package. No cycle.
package tripwire

import (
	iamdomain "metaldocs/internal/modules/iam/domain"
)

// Op identifies the trigger operation an arm gates. OpAny means the arm
// applies regardless of TG_OP (the CASE branch tests table name only).
type Op string

// Op values recognized by Arm.
const (
	OpInsert Op = "INSERT"
	OpUpdate Op = "UPDATE"
	OpAny    Op = "*"
)

// Arm is one CASE branch of enforce_capability_asserted(): the gated table,
// the operation it applies to (or OpAny), and the ordered set of
// capabilities the trigger accepts (any one present in metaldocs.asserted_caps
// satisfies the branch — match-one, not match-all).
//
// WhenColumn/WhenValue are an OPTIONAL subject discriminator (ADR 0083,
// M3 P3.S2b-3b-0): when set, this Arm applies only to rows where
// NEW.<WhenColumn> = '<WhenValue>', and RenderMigration emits a nested
// CASE NEW.<WhenColumn> inside the (table, op) branch instead of a single
// flat ARRAY assignment. Multiple Arm entries may share the same (Table, Op)
// ONLY if every one of them carries a discriminator — a shared kernel table
// (e.g. approval_instances, ADR 0082) whose required capability differs per
// subject. Discriminated arms' capability sets are NEVER unioned into one
// ARRAY; match-one applies within each subject's own set only. An
// undiscriminated Arm (WhenColumn == "") renders exactly as before this
// field was added — byte-identical, no behavior change.
//
// WhenParentTable/WhenParentKeyCol/WhenParentDiscrimCol (+ WhenValue) are a
// second, OPTIONAL discriminator form (ADR 0083 follow-on, M3
// P3.S2b-3b-iii-a): for a gated table with no direct subject column of its
// own (e.g. approval_signoffs), the subject is resolved via a parent-row
// lookup — SELECT WhenParentDiscrimCol FROM WhenParentTable WHERE id =
// NEW.<WhenParentKeyCol> — and RenderMigration emits a nested
// CASE <looked-up value> WHEN '<WhenValue>' THEN ... inside the (table, op)
// branch. Mutually exclusive with WhenColumn — a single Arm uses exactly one
// discriminator form (parent-lookup arms leave WhenColumn empty). Same
// never-unioned, match-one-within-subject semantics as the NEW-column form.
type Arm struct {
	Table      string
	Op         Op
	Caps       []iamdomain.Capability
	WhenColumn string
	WhenValue  string

	WhenParentTable      string
	WhenParentKeyCol     string
	WhenParentDiscrimCol string
}

// TripwireArms is the binding source of truth for every gated (table, op)
// pair enforced by public.enforce_capability_asserted(). Order is stable and
// mirrors the CASE-branch order in
// archive/migrations/post-baseline-2026-07-fold/0270_*.sql exactly (that
// migration, like every 0257-0315 file, was folded into db/baseline and
// archived on 2026-07-29). The latest rendered SQL is the committed golden
// internal/platform/tripwire/golden/0301_*.sql, generated by cmd/gen-tripwire;
// historically it advanced through
// archive/migrations/post-baseline-2026-07-fold/0279_*.sql. Entry #6 (documents/UPDATE)
// has grown additively across two milestones: 0271 (M2) added document.obsolete
// + membership.manage per M2 validation-contract.md §1.1/§1.2; 0275 (M6 F6.2)
// added document.review per M6 validation-contract.md §3; 0277 (M7 F7.2, ADR
// 0070) added entry #19 (tenants/INSERT gated on tenant.onboard) per M7
// validation-contract.md §5 touchpoint 6; 0279 (M7 F7.3, ADR 0070) added entry
// #20 (tenant_lifecycle_jobs/INSERT gated on tenant.export OR tenant.erase) —
// the intended registry-driven growth path, not drift.
//
// Content MUST equal M2 validation-contract.md §1.2 (18 gated entries) as
// extended by M6 validation-contract.md §3 (documents/UPDATE gains
// document.review), M7 validation-contract.md §5 (tenants/INSERT arm, 19
// entries), M7 §5 (tenant_lifecycle_jobs/INSERT arm, 20 entries), ADR 0083 /
// M3 P3.S2b-3b-0 (approval_instances/INSERT arm #1 splits into two
// subject-discriminated entries — 21 entries total; operator-ratified
// amendment to the GMR M2 validation-contract arm set, flagged HS-7 in the
// prior revision of this file, resolved here), and ADR 0083's follow-on / M3
// P3.S2b-3b-iii-a (approval_signoffs/INSERT arm #2 splits into two
// parent-lookup-discriminated entries — 22 entries total; approval_signoffs
// has no direct subject_kind column, so its discriminator resolves via the
// parent approval_instances row, per ADR 0083 §Consequences), and issue
// #89/A8.1 (ADR 0092 D1: migration 0318 creates metaldocs.capability_bindings
// + metaldocs.roles; migration 0319 — machine-generated, this extension —
// adds their arms, 24 entries total). Any other deviation is HS-7 (see those
// binding clauses).
var TripwireArms = []Arm{
	{ // 1a — ADR 0083: approval_instances is a shared (subject_kind,
		// subject_key) kernel table (ADR 0082). A flat match-one arm here would
		// let a principal holding only template.submit authorize a document
		// insert (or vice versa) — a security regression (ADR 0083 "why the
		// obvious widen is a security regression"). Discriminated on
		// NEW.subject_kind = 'document'; document rows require exactly
		// document.submit.
		Table:      "approval_instances",
		Op:         OpInsert,
		Caps:       []iamdomain.Capability{iamdomain.CapDocumentSubmit},
		WhenColumn: "subject_kind",
		WhenValue:  "document",
	},
	{ // 1b — ADR 0083 companion entry: NEW.subject_kind = 'template'; template
		// rows require exactly template.submit. Never unioned with 1a's set.
		Table:      "approval_instances",
		Op:         OpInsert,
		Caps:       []iamdomain.Capability{iamdomain.CapTemplateSubmit},
		WhenColumn: "subject_kind",
		WhenValue:  "template",
	},
	{ // 2a — ADR 0083 follow-on (M3 P3.S2b-3b-iii-a): approval_signoffs has no
		// direct subject_kind column of its own; its subject is resolved via
		// the parent approval_instances row (NEW.approval_instance_id). Same
		// security property as 1a/1b — a flat match-one arm here would let a
		// principal holding only template.approve authorize a document
		// signoff (or vice versa). Parent subject_kind = 'document' requires
		// exactly document.signoff.
		Table:                "approval_signoffs",
		Op:                   OpInsert,
		Caps:                 []iamdomain.Capability{iamdomain.CapDocumentSignoff},
		WhenParentTable:      "approval_instances",
		WhenParentKeyCol:     "approval_instance_id",
		WhenParentDiscrimCol: "subject_kind",
		WhenValue:            "document",
	},
	{ // 2b — companion entry: parent subject_kind = 'template' requires
		// exactly template.approve. Never unioned with 2a's set.
		Table:                "approval_signoffs",
		Op:                   OpInsert,
		Caps:                 []iamdomain.Capability{iamdomain.CapTemplateApprove},
		WhenParentTable:      "approval_instances",
		WhenParentKeyCol:     "approval_instance_id",
		WhenParentDiscrimCol: "subject_kind",
		WhenValue:            "template",
	},
	{ // 3
		Table: "iam_user_roles",
		Op:    OpAny,
		Caps:  []iamdomain.Capability{iamdomain.CapUserManage},
	},
	{ // 4
		Table: "user_process_areas",
		Op:    OpAny,
		Caps:  []iamdomain.Capability{iamdomain.CapMembershipManage},
	},
	{ // 5
		Table: "documents",
		Op:    OpInsert,
		Caps:  []iamdomain.Capability{iamdomain.CapDocumentCreate},
	},
	{ // 6 — the documents/UPDATE arm. Widened (additive) across two milestones.
		// M2 (0271): covers two function-local latent P0001 incidents —
		// ForceReleaseSession / ForceReleaseSessionTx
		// (documents/repository/repository.go:798,828) assert only
		// CapMembershipManage; MarkObsolete's obsolete_service.go:88->93 asserts
		// only CapDocumentObsolete. Neither co-asserts document.edit, so the
		// pre-0271 arm ({document.edit}) fail-closed unconditionally on both
		// paths. See M2 validation-contract.md §1.1.
		// M6 (0275): gains CapDocumentReview — the F6.2 mark-reviewed workflow
		// asserts only document.review then UPDATEs documents (last_reviewed_at +
		// review_due_at); without the arm every mark-reviewed UPDATE is
		// fail-closed P0001, the same defect class as 0269/0270/0271. Additive
		// registry-driven growth per M6 validation-contract.md §3 (touchpoint 6).
		Table: "documents",
		Op:    OpUpdate,
		Caps: []iamdomain.Capability{
			iamdomain.CapDocumentEdit,
			iamdomain.CapDocumentObsolete,
			iamdomain.CapMembershipManage,
			iamdomain.CapDocumentReview,
		},
	},
	{ // 7
		Table: "controlled_documents",
		Op:    OpInsert,
		Caps:  []iamdomain.Capability{iamdomain.CapControlledDocumentCreate},
	},
	{ // 8
		Table: "controlled_documents",
		Op:    OpUpdate,
		Caps: []iamdomain.Capability{
			iamdomain.CapControlledDocumentObsolete,
			iamdomain.CapControlledDocumentSupersede,
		},
	},
	{ // 9
		Table: "cd_sequence_counters",
		Op:    OpAny,
		Caps:  []iamdomain.Capability{iamdomain.CapControlledDocumentCreate},
	},
	{ // 10
		Table: "document_profiles",
		Op:    OpAny,
		Caps:  []iamdomain.Capability{iamdomain.CapTaxonomyManage},
	},
	{ // 11
		Table: "document_process_areas",
		Op:    OpAny,
		Caps:  []iamdomain.Capability{iamdomain.CapTaxonomyManage},
	},
	{ // 12
		Table: "document_families",
		Op:    OpAny,
		Caps:  []iamdomain.Capability{iamdomain.CapTaxonomyManage},
	},
	{ // 13 — 'template.submit' is a deliberately retained harmless superset
		// (no writer asserts submit while writing this table); pruning is a
		// tightening deferred to M9 arm-hygiene. See validation-contract.md §1.3.
		Table: "templates_template",
		Op:    OpAny,
		Caps: []iamdomain.Capability{
			iamdomain.CapTemplateCreate,
			iamdomain.CapTemplateEdit,
			iamdomain.CapTemplateSubmit,
			iamdomain.CapTemplateApprove,
			iamdomain.CapTemplatePublish,
			iamdomain.CapTemplateArchive,
		},
	},
	{ // 14 — 'template.review' removed (ADR 0082 phase c, unit 3.1a S5): the
		// legacy reviewer stage (Service.Review) — the only writer that asserted
		// it on this table (added by 0269) — was deleted with the legacy
		// template-approval path, and CapTemplateReview is retired from the IAM
		// registry in the same change-set. Re-rendered as
		// internal/platform/tripwire/golden/0301_tripwire_template_review_retired.sql
		// (the golden; the folded migration copy is under
		// archive/migrations/post-baseline-2026-07-fold/).
		Table: "templates_template_version",
		Op:    OpAny,
		Caps: []iamdomain.Capability{
			iamdomain.CapTemplateCreate,
			iamdomain.CapTemplateEdit,
			iamdomain.CapTemplateSubmit,
			iamdomain.CapTemplateApprove,
			iamdomain.CapTemplatePublish,
		},
	},
	{ // 15
		Table: "iam_users",
		Op:    OpAny,
		Caps:  []iamdomain.Capability{iamdomain.CapUserManage},
	},
	{ // 16
		Table: "iam_groups",
		Op:    OpAny,
		Caps:  []iamdomain.Capability{iamdomain.CapUserManage},
	},
	{ // 17
		Table: "iam_group_members",
		Op:    OpAny,
		Caps:  []iamdomain.Capability{iamdomain.CapUserManage},
	},
	{ // 18 — tenant scoped via group_id (v_tenant_id := NULL in the trigger);
		// iam_group_roles has no tenant_id column.
		Table: "iam_group_roles",
		Op:    OpAny,
		Caps:  []iamdomain.Capability{iamdomain.CapUserManage},
	},
	{ // 19 — M7 F7.2 (ADR 0070): tenant onboarding INSERTs metaldocs.tenants
		// under tenant.onboard. tenants has no tenant_id column — NEW.id IS the
		// tenant id (the row being provisioned is the tenant itself). INSERT-only:
		// no update/offboard mutation surface exists yet (F7.3+ owns lifecycle).
		Table: "tenants",
		Op:    OpInsert,
		Caps:  []iamdomain.Capability{iamdomain.CapTenantOnboard},
	},
	{ // 20 — M7 F7.3 (ADR 0070): the export/erase handlers each assert exactly
		// one of tenant.export / tenant.erase then INSERT metaldocs.tenant_lifecycle_jobs
		// (kind discriminates which). Multi-cap, match-one (OR semantics) — the
		// same INSERT surface is shared by both workflows, mirroring the
		// documents/UPDATE (#6) and controlled_documents/UPDATE (#8) multi-cap
		// arm precedent.
		Table: "tenant_lifecycle_jobs",
		Op:    OpInsert,
		Caps:  []iamdomain.Capability{iamdomain.CapTenantExport, iamdomain.CapTenantErase},
	},
	{ // 21 — issue #89/A8.1 (ADR 0092 D1): metaldocs.capability_bindings is the
		// new grant relation (migration 0318); this migration (0319) is its own
		// arm-attachment migration, the same "create table, then attach the
		// trigger separately" precedent as #19/#20 (tenants, tenant_lifecycle_jobs).
		// Backfill writers (iam_user_roles, user_process_areas, iam_group_roles
		// grants/revokes) are user.manage or membership.manage today; match-one
		// admits either until A8.2 introduces a dedicated native-grant writer.
		Table: "capability_bindings",
		Op:    OpAny,
		Caps:  []iamdomain.Capability{iamdomain.CapUserManage, iamdomain.CapMembershipManage},
	},
	{ // 22 — issue #89/A8.1 companion entry: metaldocs.roles is a tenant-id-less
		// global catalog (v_tenant_id := NULL in the trigger), mirroring the
		// iam_group_roles (#18) precedent exactly.
		Table: "roles",
		Op:    OpAny,
		Caps:  []iamdomain.Capability{iamdomain.CapUserManage},
	},
}
