//go:build go1.22

// Package controlleddocumentsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package controlleddocumentsapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionCookieScopes sessionCookieContextKey = "sessionCookie.Scopes"
)

// Defines values for ActiveDocumentResponseApprovalState.
const (
	Approved    ActiveDocumentResponseApprovalState = "approved"
	Cancelled   ActiveDocumentResponseApprovalState = "cancelled"
	Draft       ActiveDocumentResponseApprovalState = "draft"
	Rejected    ActiveDocumentResponseApprovalState = "rejected"
	Scheduled   ActiveDocumentResponseApprovalState = "scheduled"
	UnderReview ActiveDocumentResponseApprovalState = "under_review"
)

// Valid indicates whether the value is a known member of the ActiveDocumentResponseApprovalState enum.
func (e ActiveDocumentResponseApprovalState) Valid() bool {
	switch e {
	case Approved:
		return true
	case Cancelled:
		return true
	case Draft:
		return true
	case Rejected:
		return true
	case Scheduled:
		return true
	case UnderReview:
		return true
	default:
		return false
	}
}

// Defines values for ControlledDocumentStatus.
const (
	ControlledDocumentStatusActive     ControlledDocumentStatus = "active"
	ControlledDocumentStatusObsolete   ControlledDocumentStatus = "obsolete"
	ControlledDocumentStatusSuperseded ControlledDocumentStatus = "superseded"
)

// Valid indicates whether the value is a known member of the ControlledDocumentStatus enum.
func (e ControlledDocumentStatus) Valid() bool {
	switch e {
	case ControlledDocumentStatusActive:
		return true
	case ControlledDocumentStatusObsolete:
		return true
	case ControlledDocumentStatusSuperseded:
		return true
	default:
		return false
	}
}

// Defines values for ControlledDocumentVisibilityScope.
const (
	Company    ControlledDocumentVisibilityScope = "company"
	Restricted ControlledDocumentVisibilityScope = "restricted"
)

// Valid indicates whether the value is a known member of the ControlledDocumentVisibilityScope enum.
func (e ControlledDocumentVisibilityScope) Valid() bool {
	switch e {
	case Company:
		return true
	case Restricted:
		return true
	default:
		return false
	}
}

// Defines values for ListControlledDocumentsParamsStatus.
const (
	ListControlledDocumentsParamsStatusActive     ListControlledDocumentsParamsStatus = "active"
	ListControlledDocumentsParamsStatusObsolete   ListControlledDocumentsParamsStatus = "obsolete"
	ListControlledDocumentsParamsStatusSuperseded ListControlledDocumentsParamsStatus = "superseded"
)

// Valid indicates whether the value is a known member of the ListControlledDocumentsParamsStatus enum.
func (e ListControlledDocumentsParamsStatus) Valid() bool {
	switch e {
	case ListControlledDocumentsParamsStatusActive:
		return true
	case ListControlledDocumentsParamsStatusObsolete:
		return true
	case ListControlledDocumentsParamsStatusSuperseded:
		return true
	default:
		return false
	}
}

// ActiveDocumentResponse defines model for ActiveDocumentResponse.
type ActiveDocumentResponse struct {
	ApprovalInstanceId  *openapi_types.UUID                  `json:"approval_instance_id,omitempty"`
	ApprovalState       *ActiveDocumentResponseApprovalState `json:"approval_state,omitempty"`
	ContentHash         *string                              `json:"content_hash,omitempty"`
	DocumentId          *openapi_types.UUID                  `json:"document_id,omitempty"`
	PublishedDocumentId *openapi_types.UUID                  `json:"published_document_id,omitempty"`
	RevisionVersion     *int                                 `json:"revision_version,omitempty"`
}

// ActiveDocumentResponseApprovalState defines model for ActiveDocumentResponse.ApprovalState.
type ActiveDocumentResponseApprovalState string

// AtomicCreateResponse defines model for AtomicCreateResponse.
type AtomicCreateResponse struct {
	ControlledDocument ControlledDocument `json:"controlled_document"`
	Document           DocumentRef        `json:"document"`
}

// ControlledDocument defines model for ControlledDocument.
type ControlledDocument struct {
	Code                      string                       `json:"code"`
	CreatedAt                 time.Time                    `json:"created_at"`
	DepartmentCode            *string                      `json:"department_code,omitempty"`
	Id                        openapi_types.UUID           `json:"id"`
	OverrideTemplateVersionId *openapi_types.UUID          `json:"override_template_version_id,omitempty"`
	OwnerUserId               string                       `json:"owner_user_id"`
	ProcessAreaCode           string                       `json:"process_area_code"`
	ProfileCode               string                       `json:"profile_code"`
	SequenceNum               *int                         `json:"sequence_num,omitempty"`
	Status                    ControlledDocumentStatus     `json:"status"`
	TenantId                  openapi_types.UUID           `json:"tenant_id"`
	Title                     string                       `json:"title"`
	UpdatedAt                 time.Time                    `json:"updated_at"`
	Visibility                ControlledDocumentVisibility `json:"visibility"`
}

// ControlledDocumentStatus defines model for ControlledDocument.Status.
type ControlledDocumentStatus string

// ControlledDocumentVisibility defines model for ControlledDocumentVisibility.
type ControlledDocumentVisibility struct {
	AreaCodes []string                          `json:"area_codes"`
	Scope     ControlledDocumentVisibilityScope `json:"scope"`
	UserIds   []string                          `json:"user_ids"`
}

// ControlledDocumentVisibilityScope defines model for ControlledDocumentVisibility.Scope.
type ControlledDocumentVisibilityScope string

// CreateAtomicRequest defines model for CreateAtomicRequest.
type CreateAtomicRequest struct {
	DepartmentCode            *string                      `json:"department_code,omitempty"`
	DocumentName              string                       `json:"document_name"`
	FormData                  *map[string]interface{}      `json:"form_data,omitempty"`
	ManualCode                *string                      `json:"manual_code,omitempty"`
	ManualCodeReason          *string                      `json:"manual_code_reason,omitempty"`
	OverrideTemplateReason    *string                      `json:"override_template_reason,omitempty"`
	OverrideTemplateVersionId *openapi_types.UUID          `json:"override_template_version_id,omitempty"`
	OwnerUserId               string                       `json:"owner_user_id"`
	ProcessAreaCode           string                       `json:"process_area_code"`
	ProfileCode               string                       `json:"profile_code"`
	TemplateVersionId         *openapi_types.UUID          `json:"template_version_id,omitempty"`
	Title                     string                       `json:"title"`
	Visibility                ControlledDocumentVisibility `json:"visibility"`
}

// CreateRevisionRequest defines model for CreateRevisionRequest.
type CreateRevisionRequest struct {
	FormData          *map[string]interface{} `json:"form_data,omitempty"`
	Name              string                  `json:"name"`
	TemplateVersionId *openapi_types.UUID     `json:"template_version_id,omitempty"`
}

// DocumentRef defines model for DocumentRef.
type DocumentRef struct {
	ContentHash string             `json:"content_hash"`
	Id          openapi_types.UUID `json:"id"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	Code string `json:"code"`

	// Field JSON pointer or dot path
	Field   string `json:"field"`
	Message string `json:"message"`
}

// PreviewCodeResponse defines model for PreviewCodeResponse.
type PreviewCodeResponse struct {
	AreaCode    string `json:"area_code"`
	Code        string `json:"code"`
	NextSeq     int    `json:"next_seq"`
	ProfileCode string `json:"profile_code"`
}

// Problem defines model for Problem.
type Problem struct {
	// Code Machine-readable code from canonical taxonomy
	Code     string        `json:"code"`
	Detail   *string       `json:"detail,omitempty"`
	Errors   *[]FieldError `json:"errors,omitempty"`
	Instance *string       `json:"instance,omitempty"`
	Status   int           `json:"status"`
	Title    string        `json:"title"`
	Type     *string       `json:"type,omitempty"`
}

// RevisionResponse defines model for RevisionResponse.
type RevisionResponse struct {
	Document DocumentRef `json:"document"`
}

// Conflict defines model for Conflict.
type Conflict = Problem

// InternalServerError defines model for InternalServerError.
type InternalServerError = Problem

// sessionCookieContextKey is the context key for sessionCookie security scheme
type sessionCookieContextKey string

// ListControlledDocumentsParams defines parameters for ListControlledDocuments.
type ListControlledDocumentsParams struct {
	ProfileCode     *string                              `form:"profileCode,omitempty" json:"profileCode,omitempty"`
	ProcessAreaCode *string                              `form:"processAreaCode,omitempty" json:"processAreaCode,omitempty"`
	DepartmentCode  *string                              `form:"departmentCode,omitempty" json:"departmentCode,omitempty"`
	OwnerUserId     *string                              `form:"ownerUserId,omitempty" json:"ownerUserId,omitempty"`
	Q               *string                              `form:"q,omitempty" json:"q,omitempty"`
	Status          *ListControlledDocumentsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit           *int                                 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset          *int                                 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListControlledDocumentsParamsStatus defines parameters for ListControlledDocuments.
type ListControlledDocumentsParamsStatus string

// AtomicCreateControlledDocumentParams defines parameters for AtomicCreateControlledDocument.
type AtomicCreateControlledDocumentParams struct {
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// PreviewControlledDocumentCodeParams defines parameters for PreviewControlledDocumentCode.
type PreviewControlledDocumentCodeParams struct {
	ProfileCode string `form:"profileCode" json:"profileCode"`
	AreaCode    string `form:"areaCode" json:"areaCode"`
}

// CreateControlledDocumentRevisionParams defines parameters for CreateControlledDocumentRevision.
type CreateControlledDocumentRevisionParams struct {
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// AtomicCreateControlledDocumentJSONRequestBody defines body for AtomicCreateControlledDocument for application/json ContentType.
type AtomicCreateControlledDocumentJSONRequestBody = CreateAtomicRequest

// CreateControlledDocumentRevisionJSONRequestBody defines body for CreateControlledDocumentRevision for application/json ContentType.
type CreateControlledDocumentRevisionJSONRequestBody = CreateRevisionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List controlled documents
	// (GET /controlled-documents)
	ListControlledDocuments(w http.ResponseWriter, r *http.Request, params ListControlledDocumentsParams)
	// Atomically create controlled document and initial revision
	// (POST /controlled-documents)
	AtomicCreateControlledDocument(w http.ResponseWriter, r *http.Request, params AtomicCreateControlledDocumentParams)
	// Preview the next auto-generated document code without allocating it
	// (GET /controlled-documents/preview-code)
	PreviewControlledDocumentCode(w http.ResponseWriter, r *http.Request, params PreviewControlledDocumentCodeParams)
	// Get controlled document by ID
	// (GET /controlled-documents/{id})
	GetControlledDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get the active document instance for a controlled document
	// (GET /controlled-documents/{id}/active-document)
	GetActiveDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Mark controlled document as obsolete
	// (PUT /controlled-documents/{id}/obsolete)
	ObsoleteControlledDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Create a new revision for a controlled document
	// (POST /controlled-documents/{id}/revisions)
	CreateControlledDocumentRevision(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params CreateControlledDocumentRevisionParams)
	// Mark controlled document as superseded
	// (PUT /controlled-documents/{id}/supersede)
	SupersedeControlledDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListControlledDocuments operation middleware
func (siw *ServerInterfaceWrapper) ListControlledDocuments(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListControlledDocumentsParams

	// ------------- Optional query parameter "profileCode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "profileCode", r.URL.Query(), &params.ProfileCode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "profileCode"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "profileCode", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "processAreaCode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "processAreaCode", r.URL.Query(), &params.ProcessAreaCode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "processAreaCode"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "processAreaCode", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "departmentCode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "departmentCode", r.URL.Query(), &params.DepartmentCode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "departmentCode"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "departmentCode", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "ownerUserId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "ownerUserId", r.URL.Query(), &params.OwnerUserId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "ownerUserId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ownerUserId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListControlledDocuments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AtomicCreateControlledDocument operation middleware
func (siw *ServerInterfaceWrapper) AtomicCreateControlledDocument(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params AtomicCreateControlledDocumentParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey openapi_types.UUID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AtomicCreateControlledDocument(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PreviewControlledDocumentCode operation middleware
func (siw *ServerInterfaceWrapper) PreviewControlledDocumentCode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params PreviewControlledDocumentCodeParams

	// ------------- Required query parameter "profileCode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "profileCode", r.URL.Query(), &params.ProfileCode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "profileCode"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "profileCode", Err: err})
		}
		return
	}

	// ------------- Required query parameter "areaCode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "areaCode", r.URL.Query(), &params.AreaCode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "areaCode"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "areaCode", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PreviewControlledDocumentCode(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetControlledDocument operation middleware
func (siw *ServerInterfaceWrapper) GetControlledDocument(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetControlledDocument(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetActiveDocument operation middleware
func (siw *ServerInterfaceWrapper) GetActiveDocument(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetActiveDocument(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ObsoleteControlledDocument operation middleware
func (siw *ServerInterfaceWrapper) ObsoleteControlledDocument(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ObsoleteControlledDocument(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateControlledDocumentRevision operation middleware
func (siw *ServerInterfaceWrapper) CreateControlledDocumentRevision(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateControlledDocumentRevisionParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey openapi_types.UUID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateControlledDocumentRevision(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SupersedeControlledDocument operation middleware
func (siw *ServerInterfaceWrapper) SupersedeControlledDocument(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SupersedeControlledDocument(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/controlled-documents", wrapper.ListControlledDocuments)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/controlled-documents", wrapper.AtomicCreateControlledDocument)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/controlled-documents/preview-code", wrapper.PreviewControlledDocumentCode)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/controlled-documents/{id}", wrapper.GetControlledDocument)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/controlled-documents/{id}/active-document", wrapper.GetActiveDocument)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/controlled-documents/{id}/obsolete", wrapper.ObsoleteControlledDocument)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/controlled-documents/{id}/revisions", wrapper.CreateControlledDocumentRevision)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/controlled-documents/{id}/supersede", wrapper.SupersedeControlledDocument)

	return m
}

type ConflictApplicationProblemPlusJSONResponse Problem

type InternalServerErrorApplicationProblemPlusJSONResponse Problem

type ListControlledDocumentsRequestObject struct {
	Params ListControlledDocumentsParams
}

type ListControlledDocumentsResponseObject interface {
	VisitListControlledDocumentsResponse(w http.ResponseWriter) error
}

type ListControlledDocuments200JSONResponse struct {
	Items []ControlledDocument `json:"items"`
}

func (response ListControlledDocuments200JSONResponse) VisitListControlledDocumentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListControlledDocuments400Response struct {
}

func (response ListControlledDocuments400Response) VisitListControlledDocumentsResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type ListControlledDocuments401Response struct {
}

func (response ListControlledDocuments401Response) VisitListControlledDocumentsResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type ListControlledDocuments403Response struct {
}

func (response ListControlledDocuments403Response) VisitListControlledDocumentsResponse(w http.ResponseWriter) error {
	w.WriteHeader(403)
	return nil
}

type AtomicCreateControlledDocumentRequestObject struct {
	Params AtomicCreateControlledDocumentParams
	Body   *AtomicCreateControlledDocumentJSONRequestBody
}

type AtomicCreateControlledDocumentResponseObject interface {
	VisitAtomicCreateControlledDocumentResponse(w http.ResponseWriter) error
}

type AtomicCreateControlledDocument201JSONResponse AtomicCreateResponse

func (response AtomicCreateControlledDocument201JSONResponse) VisitAtomicCreateControlledDocumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type AtomicCreateControlledDocument400Response struct {
}

func (response AtomicCreateControlledDocument400Response) VisitAtomicCreateControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type AtomicCreateControlledDocument401Response struct {
}

func (response AtomicCreateControlledDocument401Response) VisitAtomicCreateControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type AtomicCreateControlledDocument409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response AtomicCreateControlledDocument409ApplicationProblemPlusJSONResponse) VisitAtomicCreateControlledDocumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type AtomicCreateControlledDocument422Response struct {
}

func (response AtomicCreateControlledDocument422Response) VisitAtomicCreateControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(422)
	return nil
}

type AtomicCreateControlledDocument500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response AtomicCreateControlledDocument500ApplicationProblemPlusJSONResponse) VisitAtomicCreateControlledDocumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PreviewControlledDocumentCodeRequestObject struct {
	Params PreviewControlledDocumentCodeParams
}

type PreviewControlledDocumentCodeResponseObject interface {
	VisitPreviewControlledDocumentCodeResponse(w http.ResponseWriter) error
}

type PreviewControlledDocumentCode200JSONResponse PreviewCodeResponse

func (response PreviewControlledDocumentCode200JSONResponse) VisitPreviewControlledDocumentCodeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PreviewControlledDocumentCode400Response struct {
}

func (response PreviewControlledDocumentCode400Response) VisitPreviewControlledDocumentCodeResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PreviewControlledDocumentCode401Response struct {
}

func (response PreviewControlledDocumentCode401Response) VisitPreviewControlledDocumentCodeResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetControlledDocumentRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetControlledDocumentResponseObject interface {
	VisitGetControlledDocumentResponse(w http.ResponseWriter) error
}

type GetControlledDocument200JSONResponse ControlledDocument

func (response GetControlledDocument200JSONResponse) VisitGetControlledDocumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetControlledDocument401Response struct {
}

func (response GetControlledDocument401Response) VisitGetControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetControlledDocument404Response struct {
}

func (response GetControlledDocument404Response) VisitGetControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetActiveDocumentRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetActiveDocumentResponseObject interface {
	VisitGetActiveDocumentResponse(w http.ResponseWriter) error
}

type GetActiveDocument200JSONResponse ActiveDocumentResponse

func (response GetActiveDocument200JSONResponse) VisitGetActiveDocumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetActiveDocument401Response struct {
}

func (response GetActiveDocument401Response) VisitGetActiveDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetActiveDocument404Response struct {
}

func (response GetActiveDocument404Response) VisitGetActiveDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ObsoleteControlledDocumentRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type ObsoleteControlledDocumentResponseObject interface {
	VisitObsoleteControlledDocumentResponse(w http.ResponseWriter) error
}

type ObsoleteControlledDocument204Response struct {
}

func (response ObsoleteControlledDocument204Response) VisitObsoleteControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ObsoleteControlledDocument401Response struct {
}

func (response ObsoleteControlledDocument401Response) VisitObsoleteControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type ObsoleteControlledDocument404Response struct {
}

func (response ObsoleteControlledDocument404Response) VisitObsoleteControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ObsoleteControlledDocument409Response struct {
}

func (response ObsoleteControlledDocument409Response) VisitObsoleteControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type CreateControlledDocumentRevisionRequestObject struct {
	Id     openapi_types.UUID `json:"id"`
	Params CreateControlledDocumentRevisionParams
	Body   *CreateControlledDocumentRevisionJSONRequestBody
}

type CreateControlledDocumentRevisionResponseObject interface {
	VisitCreateControlledDocumentRevisionResponse(w http.ResponseWriter) error
}

type CreateControlledDocumentRevision201JSONResponse RevisionResponse

func (response CreateControlledDocumentRevision201JSONResponse) VisitCreateControlledDocumentRevisionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateControlledDocumentRevision400Response struct {
}

func (response CreateControlledDocumentRevision400Response) VisitCreateControlledDocumentRevisionResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type CreateControlledDocumentRevision401Response struct {
}

func (response CreateControlledDocumentRevision401Response) VisitCreateControlledDocumentRevisionResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type CreateControlledDocumentRevision404Response struct {
}

func (response CreateControlledDocumentRevision404Response) VisitCreateControlledDocumentRevisionResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type CreateControlledDocumentRevision409Response struct {
}

func (response CreateControlledDocumentRevision409Response) VisitCreateControlledDocumentRevisionResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type SupersedeControlledDocumentRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type SupersedeControlledDocumentResponseObject interface {
	VisitSupersedeControlledDocumentResponse(w http.ResponseWriter) error
}

type SupersedeControlledDocument204Response struct {
}

func (response SupersedeControlledDocument204Response) VisitSupersedeControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SupersedeControlledDocument401Response struct {
}

func (response SupersedeControlledDocument401Response) VisitSupersedeControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type SupersedeControlledDocument404Response struct {
}

func (response SupersedeControlledDocument404Response) VisitSupersedeControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type SupersedeControlledDocument409Response struct {
}

func (response SupersedeControlledDocument409Response) VisitSupersedeControlledDocumentResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List controlled documents
	// (GET /controlled-documents)
	ListControlledDocuments(ctx context.Context, request ListControlledDocumentsRequestObject) (ListControlledDocumentsResponseObject, error)
	// Atomically create controlled document and initial revision
	// (POST /controlled-documents)
	AtomicCreateControlledDocument(ctx context.Context, request AtomicCreateControlledDocumentRequestObject) (AtomicCreateControlledDocumentResponseObject, error)
	// Preview the next auto-generated document code without allocating it
	// (GET /controlled-documents/preview-code)
	PreviewControlledDocumentCode(ctx context.Context, request PreviewControlledDocumentCodeRequestObject) (PreviewControlledDocumentCodeResponseObject, error)
	// Get controlled document by ID
	// (GET /controlled-documents/{id})
	GetControlledDocument(ctx context.Context, request GetControlledDocumentRequestObject) (GetControlledDocumentResponseObject, error)
	// Get the active document instance for a controlled document
	// (GET /controlled-documents/{id}/active-document)
	GetActiveDocument(ctx context.Context, request GetActiveDocumentRequestObject) (GetActiveDocumentResponseObject, error)
	// Mark controlled document as obsolete
	// (PUT /controlled-documents/{id}/obsolete)
	ObsoleteControlledDocument(ctx context.Context, request ObsoleteControlledDocumentRequestObject) (ObsoleteControlledDocumentResponseObject, error)
	// Create a new revision for a controlled document
	// (POST /controlled-documents/{id}/revisions)
	CreateControlledDocumentRevision(ctx context.Context, request CreateControlledDocumentRevisionRequestObject) (CreateControlledDocumentRevisionResponseObject, error)
	// Mark controlled document as superseded
	// (PUT /controlled-documents/{id}/supersede)
	SupersedeControlledDocument(ctx context.Context, request SupersedeControlledDocumentRequestObject) (SupersedeControlledDocumentResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListControlledDocuments operation middleware
func (sh *strictHandler) ListControlledDocuments(w http.ResponseWriter, r *http.Request, params ListControlledDocumentsParams) {
	var request ListControlledDocumentsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListControlledDocuments(ctx, request.(ListControlledDocumentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListControlledDocuments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListControlledDocumentsResponseObject); ok {
		if err := validResponse.VisitListControlledDocumentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AtomicCreateControlledDocument operation middleware
func (sh *strictHandler) AtomicCreateControlledDocument(w http.ResponseWriter, r *http.Request, params AtomicCreateControlledDocumentParams) {
	var request AtomicCreateControlledDocumentRequestObject

	request.Params = params

	var body AtomicCreateControlledDocumentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AtomicCreateControlledDocument(ctx, request.(AtomicCreateControlledDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AtomicCreateControlledDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AtomicCreateControlledDocumentResponseObject); ok {
		if err := validResponse.VisitAtomicCreateControlledDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PreviewControlledDocumentCode operation middleware
func (sh *strictHandler) PreviewControlledDocumentCode(w http.ResponseWriter, r *http.Request, params PreviewControlledDocumentCodeParams) {
	var request PreviewControlledDocumentCodeRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PreviewControlledDocumentCode(ctx, request.(PreviewControlledDocumentCodeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PreviewControlledDocumentCode")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PreviewControlledDocumentCodeResponseObject); ok {
		if err := validResponse.VisitPreviewControlledDocumentCodeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetControlledDocument operation middleware
func (sh *strictHandler) GetControlledDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetControlledDocumentRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetControlledDocument(ctx, request.(GetControlledDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetControlledDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetControlledDocumentResponseObject); ok {
		if err := validResponse.VisitGetControlledDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetActiveDocument operation middleware
func (sh *strictHandler) GetActiveDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetActiveDocumentRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetActiveDocument(ctx, request.(GetActiveDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetActiveDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetActiveDocumentResponseObject); ok {
		if err := validResponse.VisitGetActiveDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ObsoleteControlledDocument operation middleware
func (sh *strictHandler) ObsoleteControlledDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request ObsoleteControlledDocumentRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ObsoleteControlledDocument(ctx, request.(ObsoleteControlledDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ObsoleteControlledDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ObsoleteControlledDocumentResponseObject); ok {
		if err := validResponse.VisitObsoleteControlledDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateControlledDocumentRevision operation middleware
func (sh *strictHandler) CreateControlledDocumentRevision(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params CreateControlledDocumentRevisionParams) {
	var request CreateControlledDocumentRevisionRequestObject

	request.Id = id
	request.Params = params

	var body CreateControlledDocumentRevisionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateControlledDocumentRevision(ctx, request.(CreateControlledDocumentRevisionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateControlledDocumentRevision")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateControlledDocumentRevisionResponseObject); ok {
		if err := validResponse.VisitCreateControlledDocumentRevisionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SupersedeControlledDocument operation middleware
func (sh *strictHandler) SupersedeControlledDocument(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request SupersedeControlledDocumentRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SupersedeControlledDocument(ctx, request.(SupersedeControlledDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SupersedeControlledDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SupersedeControlledDocumentResponseObject); ok {
		if err := validResponse.VisitSupersedeControlledDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Dttb+S20X+F0PN8uENXlu9yQRHnk+tLUrdJzzhf8iU1FrPiaJexROpIau3NwkB/RH9hf0nBF0nULqVd",
	"+16QA/rJK3JmOJz3IeltkouqFhy5VsnZNpGoasEV2o8LwYuS5dr8zgXXyO1PqOuS5aCZ4FktxaLE6k+/",
	"KcHNnMpXWIH59f8Si+Qs+b+sXyBzsyq7cljJw8PDLKGocslqQy4582tqQSgSVBqoSB5mySXXKDmU1yjX",
	"KL+TUsjPyZRZkDDLgyBUEIVyzaiQiQH1+Ib8ea7ZGl+LvKmQ67delmamlqJGqZkTLNS1FGso54wrDTzH",
	"OaNmvBCyAp2cJU3DaDJL9KbG5CxRWjK+NHLoEJUGbQkjb6rk7NeESih0MksaTlHOJa4Z3iUtAhpihk/a",
	"lPa3xN8w1/ZnbtYvzfBNZEEv4fkK1MostwdA/WaP3UHdLEqmVkjnj8U0e1JM8PkapWJOsxXjrDICeNEh",
	"GDUt0anGD4mF2a2hca5FxfILiaBxXD1m01IYmXRMHjKeiw6l1X4onEPYvcUUlm+J7xsmkRrFxpgJKN9E",
	"dhlhJrJHilGF5lY4dA56oBUKGlPNKoyphmINUltltnR5U5awKDE507LBCM6RWhdrlJJRnGus6hI0tuof",
	"MZuD64o7jnLeKJSewr6JSpGjUnOQCPNROdVSFKzEcQCF7xs0vm09dFQinb3OEuPUjQq9GmxASWaJWChR",
	"ojY/VVOjVEhHPFYjh+OdSjNdxtlvavpoOzAOumAl05vH+8svPe6uCzjWu33tyD6msFni/7j97Wq9E/WA",
	"5YHtDwRwnJP9Mtj9TsRvWbNfTGOlolL3AyAlbKxJ5KIexHkjS+AbG8MNmo3iMTvwe33Uejtyd4vPQuYD",
	"ulGhWAG6KPvW2L+KhJ5ItBhPKxwq9JH+R+RLvQpjfQ9v7HNOQdssD5Qyk7mhvAoWHnhdz3IFvIFynJNg",
	"fi4RfElxRJx6FPB0UDscxA6IJxrSDuMMAtwB8KdupYtAB+h/othyRCgZiyFDGx1wOO4bb30VM+odT7fk",
	"I13laYraEZtdK7bLsJSJFlaT1eRTWLEgA8oxvr5nWNKucTiyFioMkgtZYTvwt+s3/yC1sA0BEZJQoUkN",
	"ehUz7wqVgmWM/M423Fpd4mrxYnu5cuX9haATRex09TI6wfFezxW+P1RdHyyApv0s9K9uSc9WfMuuORvV",
	"3VBDP0G+YhxTiUBNzUUMGCmkqEgOXHCWQ0k03Asuqk28otXAyqiE0BjRMK1ORaPA8CL5vW0A4xVkVw9W",
	"cO808fU338x6vbw6PY1pZryocwOhh0l20MHa+NfVTKNa6oPbmFV+jI5oovexZXfeSKY314aSW1ShMlxd",
	"CHHLIsZy7aZJbucJU6pBShYbcvXm+h3JoGbZ+kUGjV5lpVgyfpIYvSVniUNI2sibVKihpCJXc79iL1qo",
	"2d9x484WGC/EPhfnV5eEcZYzKAkV5CdD67XIFXm2fvH8hHxnijFBQDdQEoWVPY5YSshBkFxU5PL85J+8",
	"S1ZnSY9/fnVpklPbNCcvTk5PTm0RUSOHmiVnyVcnpydfmewHemUllrUHDRnjC3GfnG0fZoNBZ7Uq2wYn",
	"GA9HgmXuyOFYaKVhaQbtXzfCllwUhdqlIEWjcWQ020YYDKYyirbZcscqFqqhTGe49kdju0MZ3tdC6vGZ",
	"bOv+XvbrTgJlVNzxUgDtoPUqy1fAl5jWoNSdkIMpa4s7A6LR4UiF4Zc3ShUby7b+V89tf/CQth5nbWOJ",
	"1nuNV9vjtkuanCU/MqX36y5lbUpChRpNyPx16xznfYNy0/uNzw0XLh30p3V7YWkU3dRs5xLhqST6luSp",
	"FGxx+LNCeUmfgv7+KUhdQO4xn3xwMLZGySqmB0t02ec0duY2Ip2iUPgIMjez4Un0y9PTifPe/XPeYdLp",
	"8vRRCTt+lDfZKDu6kXS0d5Isbg2xV247w6k1lIzaDc2xLRdenb7YB2y4cV3k2uwfqYP7ah+uEHLBKEXu",
	"8mJTVSA33ldJ792EBt6qYamGp46B89/Mkvu0hiXjls0U77GqdduPRKbStgdOflaoiLWlzNkC6YEJaCIb",
	"rlmF5BkXmmxQk7yRSsi0YktpNvn8Wz9C3IhB0xLyW6SkEJJcrUAh+f7EFqZCRSJUePQbUXE8UK0QKMre",
	"ji8pVrXQyPNNavJ5aAZOCr0NHupibhwyKv0XQTePMu9J840cwTwMDdZw+rDnYS8+GgvRU/aIM/jjtk/k",
	"Ed+MsdntO+suuAzCy5f7hLtemXHLjAH82rE6TTl2YTX0QickKMsNcXKIuSQBTk1VqE1V2F6AHOWmRiC/",
	"p6bNsrboGtno8QYXpuRJTPpM7Ykf9QydEb1CokEujbs6TGIwCVN2ypsvqWFj6hZiV5kR5IWQOVLj15qh",
	"TF8Sxi1CYFKkhA1K8uz89VtyevrypffgPz831bUSjTQ9UbIwnmEtJ1qOZLXrhNO2C4zWJl27vOv0Ptc/",
	"ukIZ9/nJo5ex5Ah94fJUyh+aL6fvRfdPGz5XZht4jGfEWhLHe02g0SJdIkebInqnsc3+HdMr0WgCZSnM",
	"vvmS2EJm2nXGTc33D3ET+wH10TnFnxR55TP64UnkEyk+VgiN6/3YsPxqH44LPS9Ew3cV/gNG6xTTml++",
	"/kBVZq5CTsMDiTHVDq/1v3S1jjxS+FSqnTtBd08dIjq2qcFC9TpuwW11BzEz+FAD6Doj0y80Ec2/8QB/",
	"FM+OiLfdA/2YPtgVTzvV2v5DhLnB8q3mUK0/gbyNFzSKBC3pY+sYipKtkc4LKao4S+rk2BoH6kdVKiaf",
	"uClTAZl6x7QeUlR2MLIBIsUdefb9m7fk56vX5+++e/4t4bhG6ZCgq55s1XSoENL3U2WQtee2PLTWEu+B",
	"xrqft31l+cntevalt1a7N3ifubnaO2P/7I3Vq+Njw0eMKE74BAjHu64V+nTZoTssG00P1y3EHzg/BEd+",
	"X1CCCLj+X4p4fIoIT+sH35nSEBkNbkZ2a2R/UZIG15QxMJmvjIbjk40WCtZoYlnF9AGgWqJiSx6HGtwb",
	"7c6tML+1d/LqIEC29bdhJmkqLeQI64ZjHCfoZ7NtyRYS5Oby9YgYaeMsZWQZfxNERX6fNrKcBKppEZ8v",
	"WGnUlHYBJArDoWS/j7AR1MOR2bqEHFeipChTYT1eZdt61HICcHUYYpKSezAcn5SYC660bHI9BuASRbpi",
	"RtGbaSiVbaX5HtVC+4Y6neTKX6VlkNvgPg1kw0sqsURQB0BXCFIvEPQ02DQtd3c6MtksRl00TIiRafve",
	"3M0UCLqRmBalDd12bIVQ6lVW9mHCj0gE2mqFQZUBrRjPxBplQNFOmMBcYbVAqVasVhNT2dY/0nrItl2I",
	"fwgQcqjBvtRiGNK5rVnwZUIR8hwzxaFWK6GDOSlKTEeomLnwu/Hvf/rv3ie672zRlLd7g4yvmd7Dddvr",
	"L2r3J7K4nHaAzP707tVyDG5vQ4Pphpcib3mvUEuWt9AKTWrYS0jtE43MIIpmf7wqIM2NDfSS6+aMAUPZ",
	"obAlx5b39kGPNQgVHcy2oS10cwVUrOzVuDc+guaPhdXY+AE0P51RLKApddreNrTw/lPtfg+CcQ4aSrHc",
	"g1EbpbHKFiXw273JIOUPB/uUnwtesOUI0CDh7042tIshO1M+7arp2WzLHw5DeE7xGMhoCXIUxrAemUJx",
	"6bs2VV+QxQ9jHAdq/7vnMNwwLU1B+v8QOgw4KCgOAz5OBH3CCV5u2YZp583Wrzem4VH2Ns11VHaBxL/O",
	"Ssys7xTGnncFbY75/M+//k3sE5oZcQ9nZvayzVbqjZTIdWoiHKmlWOBJcFvT6FXyMNtd5ZIa2npjiUBu",
	"78oq4LBEW+ib1WzcnBEbTmckzB4z0r7DcUzY/iGI4cHyDKrI6u/sP0cQ63qpfWBElJYIlSXnakc12ITx",
	"0X06114FpGt1lWUd8lw0XJM2YFuyrb6ID8kB/U6VsSWMDtOg9XORpvG3+oayryCIrSACsgPICO22/yad",
	"zc1Ia28z4k9QvIh9nBuuHqzVR9+pdXxIt0Jqw/rM6s+v02aQkHL77nSf8EWkRyxZgfkmL9HSs3db7Z3W",
	"gOFogzzBuzFkIRlfDqzPB74ZadubGQkr9dmIQU2teN6K2j23m3Vn+0YnbMlTURSecGTTWgJX9hH8wIA9",
	"zZgMpVCqF5+rQQa2aQYiiD+yNXJ7x80pMXUps182AIRru8o1QuBN6zRQkr++e3dFfDUU4IqFiWHQ/jPC",
	"zcN/AwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
